### ISSUE TITLE
TypeError: detectObjectsFromVideo() got an unexpected keyword argument 'camera_input'

### ISSUE THREAD

**Issue by gujiachen** [OlafenwaMoses/ImageAI#101]
when i run camera_feed_detection, I got the error：“TypeError: detectObjectsFromVideo() got an unexpected keyword argument 'camera_input'”.  So how can i fix it?

**Comment by OlafenwaMoses** [comment]
Kindly comment your code.

**Comment by joyarx** [comment]
see the source of Detection.py line 620:                 input_video = cv2.VideoCapture(input_file_path)
so the right code should be: 
video_path = detector.detectObjectsFromVideo(
    input_file_path=0,
