### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by BhushanGarware** [OlafenwaMoses/ImageAI#112]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6e36ae1d6cb7> in <module>()
----> 1 detector.loadModel()

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/__init__.py in loadModel(self, detection_speed)
    182                 raise ValueError("You must set a valid model type before loading the model.")
    183             elif(self.__modelType == "retinanet"):
--> 184                 model = resnet50_retinanet(num_classes=80)
    185                 model.load_weights(self.modelPath)
    186                 self.__model_collection.append(model)

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/keras_retinanet/models/resnet.py in resnet50_retinanet(num_classes, inputs, **kwargs)
     84 
     85 def resnet50_retinanet(num_classes, inputs=None, **kwargs):
---> 86     return resnet_retinanet(num_classes=num_classes, backbone='resnet50', inputs=inputs, **kwargs)
     87 
     88 

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/keras_retinanet/models/resnet.py in resnet_retinanet(num_classes, backbone, inputs, modifier, **kwargs)
     78 
     79     # create the full model
---> 80     model = retinanet.retinanet_bbox(inputs=inputs, num_classes=num_classes, backbone=resnet, **kwargs)
     81 
     82     return model

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py in retinanet_bbox(inputs, num_classes, nms, name, **kwargs)
    345         ```
    346     """
--> 347     model = retinanet(inputs=inputs, num_classes=num_classes, **kwargs)
    348 
    349     # we expect the anchors, regression and classification values as first output

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py in retinanet(inputs, backbone, num_classes, anchor_parameters, create_pyramid_features, submodels, name)
    300     """
    301     if submodels is None:
--> 302         submodels = default_submodels(num_classes, anchor_parameters)
    303 
    304     _, C3, C4, C5 = backbone.outputs  # we ignore C2

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py in default_submodels(num_classes, anchor_parameters)
    208     """
    209     return [
--> 210         ('regression', default_regression_model(anchor_parameters.num_anchors())),
    211         ('classification', default_classification_model(num_classes, anchor_parameters.num_anchors()))
    212     ]

/home/deepml/anaconda3/lib/python3.5/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py in default_regression_model(num_anchors, pyramid_feature_size, regression_feature_size, name)
    123 
    124     outputs = keras.layers.Conv2D(num_anchors * 4, name='pyramid_regression', **options)(outputs)
--> 125     outputs = keras.layers.Reshape((-1, 4), name='pyramid_regression_reshape')(outputs)
    126 
    127     return keras.models.Model(inputs=inputs, outputs=outputs, name=name)

/home/deepml/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    594 
    595             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 596             output = self.call(inputs, **kwargs)
    597             output_mask = self.compute_mask(inputs, previous_mask)
    598 

/home/deepml/anaconda3/lib/python3.5/site-packages/keras/layers/core.py in call(self, inputs)
    389                 pass
    390             if input_shape is not None:
--> 391                 target_shape = self.compute_output_shape(input_shape)[1:]
    392         return K.reshape(inputs, (-1,) + target_shape)
    393 

/home/deepml/anaconda3/lib/python3.5/site-packages/keras/layers/core.py in compute_output_shape(self, input_shape)
    374     def compute_output_shape(self, input_shape):
    375         return (input_shape[0],) + self._fix_unknown_dimension(
--> 376             input_shape[1:], self.target_shape)
    377 
    378     def call(self, inputs):

/home/deepml/anaconda3/lib/python3.5/site-packages/keras/layers/core.py in _fix_unknown_dimension(self, input_shape, output_shape)
    362                 known *= dim
    363 
--> 364         original = np.prod(input_shape, dtype=int)
    365         if unknown is not None:
    366             if known == 0 or original % known != 0:

/home/deepml/anaconda3/lib/python3.5/site-packages/numpy/core/fromnumeric.py in prod(a, axis, dtype, out, keepdims, initial)
   2583     """
   2584     return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out, keepdims=keepdims,
-> 2585                           initial=initial)
   2586 
   2587 

/home/deepml/anaconda3/lib/python3.5/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     81                 return reduction(axis=axis, out=out, **passkwargs)
     82 
---> 83     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     84 
     85

**Comment by OlafenwaMoses** [comment]
Kindly install the latest version of **ImageAI**

`pip3 install imageai --upgrade`

**Comment by rola93** [comment]
any news on this? should be closed otherwise cc @OlafenwaMoses
