### ISSUE TITLE
ImportError: cannot import name 'VideoObjectDetection'

### ISSUE THREAD

**Issue by Devraj004** [OlafenwaMoses/ImageAI#116]
Hi Ola,
Not sure what is the issue , When i ran my program first time it loaded perfectly. but when tried second time start getting import error. I checked all the modules and folders are available at correct path. 

Here is the error.

Traceback (most recent call last):
  File "cv2.py", line 14, in <module>
    from imageai.Detection import VideoObjectDetection
  File "C:\Python27\Python27\imageai\Detection\__init__.py", line 1, in <module>

    import cv2
  File "C:\Python27\Python27\cv2.py", line 14, in <module>
    from imageai.Detection import VideoObjectDetection
ImportError: cannot import name 'VideoObjectDetection'

need your help to resolve this.

**Comment by Devraj004** [comment]
My bad, I realized that the python file name is cv2 which itself a opencv module in python and that's why i was getting import error.
I renamed the file and the issue got resolved.
Many thanks Ola. You guys have really created a awesome python library. 

Kind Regards
Devraj

**Comment by OlafenwaMoses** [comment]
Glad to know you have resolved this. You are welcome.
