### ISSUE TITLE
Cannot interpret feed_dict key as Tensor: Tensor Tensor("keras_learning_phase:0", shape=(), dtype=bool) is not an element of this graph.

### ISSUE THREAD

**Issue by nikparmar** [OlafenwaMoses/ImageAI#117]
Hii,
I am using this library with Flask and running the server using gunicorn and gevent. We are getting this error and I believe this is a known issue in keras and have some work arounds. Did anyone test this library with flask on threads?

**Comment by shrinivas93** [comment]
Facing same issue. Anyone found the solution?
