### ISSUE TITLE
Keras version should be higher when using 2.0.2

### ISSUE THREAD

**Issue by thebigbai** [OlafenwaMoses/ImageAI#118]
Hello,

In the imageai 2.0.1, the keras 2.0.9 is ok. 

But when I updated to imageai 2.0.2, there was a RuntimeError: 
```
The Session graph is empty.  Add operations to the graph before calling run()
```

I think it was because the keras version is not latest, so I updated my keras to version 2.2.4. This problem was solved. I do suggest to add this to the document as the document only listed that keras should be 2.X.

thanks for your nice project

**Comment by OlafenwaMoses** [comment]
Thanks for sharing this. I will review this and update accordingly.
