### ISSUE TITLE
Custom Training and Testing Sets

### ISSUE THREAD

**Issue by jameswellsiv** [OlafenwaMoses/ImageAI#119]
I currently have made my own training and testing sets for doing a custom trained classifier. I am just wondering should I include photos that do not include the object in those sets?

**Comment by jameswellsiv** [comment]
Also I would like to add that right now I am training an CNN of the SqueezeNet architecture and the accuracy and loss are stagnant with each epoch. Loss will always be around 0.47 and accuracy will be at 97%. I dont think I am correctly training this classifier.

**Comment by OlafenwaMoses** [comment]
> I currently have made my own training and testing sets for doing a custom trained classifier. I am just wondering should I include photos that do not include the object in those sets?

If the number of possible objects that are observable are within the range of the classes of images you have, you need not to worry. However, if there are objects outside the ones collected during application of the model, you don't necessarily need to collect images for objects outside the range ( an enormous classes of objects). The model will give a very low percentage score most of the time to the it's first prediction should the item be out of the trained range; this you can use to determine if a strange object has been encountered.

**Comment by OlafenwaMoses** [comment]
> Also I would like to add that right now I am training an CNN of the SqueezeNet architecture and the accuracy and loss are stagnant with each epoch. Loss will always be around 0.47 and accuracy will be at 97%. I dont think I am correctly training this classifier.

This has been observed and will be solved soon. You can use the other model types such as the **ResNet50** of **DenseNet**.
