### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by urosm993** [OlafenwaMoses/ImageAI#124]
Is there a way I can control memory allocation?

I have only 3GB of memory, so I get this message.
 Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.15GiB

Somewhere I read about enabling config.gpu_options.allow_growth = True, but it seems to me that option is already enabled. Any clues?

**Comment by dmcEric** [comment]
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) 

this codes will help.
