### ISSUE TITLE
Support for MobileNet and Google's Object Detection API

### ISSUE THREAD

**Issue by xhlulu** [OlafenwaMoses/ImageAI#127]
I just went through the documentation and I wanted to say that this is a great library! I'll definitely use it if I have the chance to do so in the future.

Is ImageAI planning to support models from the Google object detection API? I have used MobileNet for my projects previously and it offers great benefits compared to other state-of-the-art models (Yolo v3), and I was thinking about creating a simple API wrapping around MobileNet. However, I see that this library is already offering a lot of what I was looking for, but with Yolo v3, so I was wondering if the team is planning on adding MobileNet.

Thank you!

**Comment by OlafenwaMoses** [comment]
We don't have plans to integrate Google object detection API.
