### ISSUE TITLE
How to edit yolov3 model(models.py) in order to be able to detect custom objects, classess = 1

### ISSUE THREAD

**Issue by dreambit** [OlafenwaMoses/ImageAI#129]
I have custom image dataset, classess = 1, model is trained on this dataset.
i have an errior
_Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1]_

Could you specify how to adjust model to handle this?

**Comment by OlafenwaMoses** [comment]
ImageAI currently doesn't support training your own custom detection model. It only supports training custom recognition/classification models, and that requires that you have at least 2 classes of objects in your dataset. 

For training custom detection models, refer to this conversation. #8
