### ISSUE TITLE
Is possible to use Open Images Dataset V4?

### ISSUE THREAD

**Issue by unpxre** [OlafenwaMoses/ImageAI#130]
Can i use some of models pre-trained on open images dataset? ( https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#open-images-trained-models )

If it is possible how to do that? I think i must use use own detection model type?

**Comment by OlafenwaMoses** [comment]
ImageAI currently doesn't provide pre-trained model for Open Images.
