### ISSUE TITLE
Licensing keras-retinanet

### ISSUE THREAD

**Issue by hgaiser** [OlafenwaMoses/ImageAI#139]
Hi, I am one of the maintainers of the [keras-retinanet](https://github.com/fizyr/keras-retinanet) repository. 

It appears you copied our repository into your project, which in itself is fine, but only if you keep the [LICENSE](https://github.com/fizyr/keras-retinanet/blob/master/LICENSE) file as well and state any changes you made to the code. You might want to check for other copied projects to see if similar problems arise there.

On a sidenote, why not use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)? If you want to make custom changes, I suggest making a git submodule from a forked repository. This will make it significantly easier to keep track of updated changes and will keep the LICENSE file in place.

**Comment by hgaiser** [comment]
@OlafenwaMoses any update on this? This can simply be resolved by adding the LICENSE file. Changing the structure to use submodules would be cleaner, but requires a bit more work.

**Comment by OlafenwaMoses** [comment]
Thanks for reaching out. I have been pretty busy recently. I will review and make the necessary updates to the structure. 

Meanwhile, I have added the license for keras-retinanet. See details via link below.

https://github.com/OlafenwaMoses/ImageAI/commit/afc630743b14538b3c67fcad475db0bdd2ea2b5b

**Comment by hgaiser** [comment]
Thank you for the reply, this issue can be considered resolved then. I do think submodules would help in keeping up-to-date with dependencies (it seems your keras-retinanet is already quite old), but I understand the issue of being too busy ;)
