### ISSUE TITLE
Using "extract_detected_objects =True " in Detection may cause  error.

### ISSUE THREAD

**Issue by zzqxztc** [OlafenwaMoses/ImageAI#143]
I use function about detectObjectsFromImage and set **"**output_type="file", extract_detected_objects = False**"**.
Sometimes, the program raises an error "SystemError: tile cannot extend outside image".
The Model used in program is "RetinaNet".

**Comment by zzqxztc** [comment]
i found "box_points" may gets "-1" value, such as "[  -1  16 471 534]".It will raise an error "SystemError: tile cannot extend outside image".
I put code"
                        if detection_details[0] < 0 : detection_details[0] = 0
                        if detection_details[1] < 0 : detection_details[1] = 0
                        if detection_details[2] < 0 : detection_details[2] = 0
                        if detection_details[3] < 0 : detection_details[3] = 0
"
in Function "detectObjectsFromImage" can temporarily fix this error.
However, i don't konw why it happened.

**Comment by OlafenwaMoses** [comment]
This will be investigated and fixed in next update.

**Comment by Serhiy-Shekhovtsov** [comment]
Looks like the bug is still there.
