### ISSUE TITLE
retinanet model must be ’resnet50_coco_best_v2.0.1.h5’

### ISSUE THREAD

**Issue by Fatsheepgogogo** [OlafenwaMoses/ImageAI#144]
I have a fire detection retinanet-model  by transfer learning  ’resnet50_coco_best_v2.1.0.h5’，
When I replace ’resnet50_coco_best_v2.0.1.h5’ with my retinanet model，
I got ValueError: Dimension 0 in both shapes must be equal。

**Comment by OlafenwaMoses** [comment]
The Object Detection classes provided are tailored for detecting **COCO** objects. Follow the discussion on this  thread  #8 for more on this .
