### ISSUE TITLE
Displaying live web-cam video

### ISSUE THREAD

**Issue by kostikmostik** [OlafenwaMoses/ImageAI#148]
Hello ImageAI team,

I want to express my admiration for your work! Thank you for doing this!

I also want to ask you a question. I'm running web-cam detection, and I'm wondering if it is possible to also display the detected video in real-time? 

If image AI doesn't support this feature, is there a way to do this through OpenCV somehow?

Thank you in advance!

**Comment by OlafenwaMoses** [comment]
To ensure you can obtain and display the detection in real-time, I will recommend that you run **ImageAI** on a machine with **NVIDIA GPU** and the GPU version of [Tensorflow](https://pypi.org/project/tensorflow-gpu/) installed.
