### ISSUE TITLE
How To Install ImageAI On Visual Studio

### ISSUE THREAD

**Issue by ChetanArvindPatil** [OlafenwaMoses/ImageAI#149]
Hi All,

I use Visual Studio for Python and trying to install ImageAI using Python Environment that supports pip. I am running into following error.

`----- Installing 'install --index-url=https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl' -----
Looking in indexes: https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl
Collecting install
  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install
----- Failed to install 'install --index-url=https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl' -----
`

Can anyone suggest how to do it correctly?

Thanks.

**Comment by OlafenwaMoses** [comment]
Kindly install ImageAI via PyPi via the command below.

`pip3 install imageai`
