### ISSUE TITLE
How to output the custom predict result?

### ISSUE THREAD

**Issue by woshichuanqilz** [OlafenwaMoses/ImageAI#152]
I want the output image with mark rectangle on the image. 

I check the function 
```
def predictImage(self, image_input, result_count=1, input_type="file"):
```
seems no output option. 

How to make it?

**Comment by OlafenwaMoses** [comment]
You can only get the box points to create a rectangular mark on the object in an image if you are using an **object detection** model. ImageAI doesn't support detecting custom objects yet. Keep up to date with #8 to know the latest on this.
