### ISSUE TITLE
It is possible to train prediction having multiple level hierarchy?

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#153]
It is possible to train prediction having multiple level hierarchy?
Something like:

Animals
mamals
cat
dog
reptiles
iguana

products
berries
strawberry
bluebery
etc
vegetables
potato
onion

All in one model.

**Comment by Gytis123** [comment]
Or predict using multiple models?

**Comment by OlafenwaMoses** [comment]
ImageAI currently doesn't support multi-label recognition. This will be considered in future updates.
