### ISSUE TITLE
Prediction diferent models

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#155]
Is it possible to create multiple CustomImagePrediction() instances which have set different models for image predictions? I tried but it gives me unpredictable results.

Something like:
ident = CustomImagePrediction()
ident.setModelPath(identprof)
...

pet= CustomImagePrediction()
pet.setModelPath(pets)

**Comment by OlafenwaMoses** [comment]
In the next update, using multiple custom recognition models will be supported.

**Comment by OlafenwaMoses** [comment]
@Gytis123 Thanks very much for your patience. We have released a new version (v2.0.3) that allows you to run multiple custom models at once. See the link below on this.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMPREDICTION.md#custompredictionmultiple

Also visit https://github.com/OlafenwaMoses/ImageAI to learn more on all the new features.
