### ISSUE TITLE
Converting tensorflow model to .h5

### ISSUE THREAD

**Issue by dudeperfect95** [OlafenwaMoses/ImageAI#157]
Im interested in using 
faster_rcnn_inception_resnet_v2_atrous_coco model from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md in ImageAI, but Im newbie in this subject. What I would like to know is whether is it possible to somehow convert this model to .h5 model so ImageAI can use it?

**Comment by OlafenwaMoses** [comment]
ImageAI currently doesn't support using your own custom object detection models. Keep up to date with #8 to know the latest on this.
