### ISSUE TITLE
Boxpoints

### ISSUE THREAD

**Issue by Devarsh8** [OlafenwaMoses/ImageAI#158]
Sir
eachObject in detection  convey name, probability  & boxpoints. 

Here is the value of boxpoints for the rectangle upperleft and lowerright coordinates

**Comment by OlafenwaMoses** [comment]
The **box_points** contains values for the  X and Y coordinates in order of **(x1, y1, x2, y2)**. **x1** and **y1** refers to the lowerleft and **x2** and **y2** refers to the upperright.

**Comment by anu0012** [comment]
Hey @OlafenwaMoses I am unable to use box_points argument. It is not showing in eachObject dictionary. Only name and probability are there.

**Comment by OlafenwaMoses** [comment]
Ensure you install the latest version of ImageAI. See the command below.

`pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl`
