### ISSUE TITLE
Monkey is detected as person, any help?

### ISSUE THREAD

**Issue by ericchuawc** [OlafenwaMoses/ImageAI#160]
Followed the 10 lines codes tutorial
https://towardsdatascience.com/object-detection-with-10-lines-of-code-d6cb4d86f606

I have tried to scan this monkey pic
http://3.bp.blogspot.com/-vCYfcDOXCJU/T2Mo2y59JEI/AAAAAAAAEdU/HVzAnMhOShs/s1600/Monkey-Passport-Pictures-0013.jpg

and it shows it as 
person  :  99.99912977218628

Output image
https://imgur.com/a/lywq6qS

**Comment by ericchuawc** [comment]
2nd attempt with a different monkey, same issue

https://imgur.com/a/4fl550i

person  :  51.38605833053589

**Comment by OlafenwaMoses** [comment]
Monkey is not in the list of items ImageAI can recognize right now. See the list as given in the documentation below.

https://imageai.readthedocs.io/en/latest/detection/index.html

**Comment by ericchuawc** [comment]
i see, but how do i add monkey to the detection list?

**Comment by OlafenwaMoses** [comment]
Keep up to date with this thread. #8
