### ISSUE TITLE
loading a model for video detection

### ISSUE THREAD

**Issue by rajivchandrasekar** [OlafenwaMoses/ImageAI#163]
You are trying to load a weight file containing 107 layers into a model with 116 layers. 
Sir im working on project involving classification of vehicles which is supposed to be trained by means of custom data .And that is the error im facing please guide me through.

Thankyou.

**Comment by sardeenz** [comment]
Not entirely sure of your situation, but make sure your detector type matches your model type. i.e. 

detector.setModelTypeAsTinyYOLOv3()
detector.setModelPath(os.path.join(execution_path , "yolo-tiny.h5"))
