### ISSUE TITLE
How to conver the model format of“.h5” to the“.pb”？

### ISSUE THREAD

**Issue by lianghx7** [OlafenwaMoses/ImageAI#165]
I want to convert a model in .h5 format to a model in .pb format for use under TensorFlow. What should I do?  Thanks.

**Comment by OlafenwaMoses** [comment]
We will provide support for this very soon.

**Comment by lianghx7** [comment]
Your help is much appreciated.  I am looking forward to the next update of
imageai. 😊

MOSES OLAFENWA <notifications@github.com> 于2019年3月16日周六 下午7:07写道：

**Comment by OlafenwaMoses** [comment]
@lianghx7 , thanks very  much for your patience. We have released a new version (v2.0.3) which now suports converting your  Keras models into Tensorflow's (**.pb**) format. See the link below on how use this.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMPREDICTION.md#converttensorflow

**Comment by lianghx7** [comment]
Thank you for your contribution, I will try to use the new version of
ImageAI.
Best wishes for you and ImageAI.   😄

MOSES OLAFENWA <notifications@github.com> 于2019年6月14日周五 上午12:23写道：
