### ISSUE TITLE
ImportError: No module named imageai.Detection

### ISSUE THREAD

**Issue by youjinChung** [OlafenwaMoses/ImageAI#167]
I've been using ImageAI in another folder, and it worked totally fine.
now I am trying to use them again in another folder, starting with testing object detection.
But I got the message 'ImportError: No module named imageai.Detection'.
I uninstalled ImageAI and installed again using pip3 and they said it installed successfully, but got the same error when I run the code.

**Comment by OlafenwaMoses** [comment]
Do you make use of Virtual Environment for your Project? Ensure you installed **ImageAI** and its dependencies in the same runtime as your project's.

**Comment by sivasai8143** [comment]
i want to run **from imageai.Detection import ObjectDetection** program as a window service. please help me @OlafenwaMoses

**Comment by FalconMadhab** [comment]
Just run your code using python3. It solved the issue for me.
Eg. python3 yolo_test.py

**Comment by johannb75** [comment]
@youjinChung Did you found a solution ?

**Comment by adnanbandey** [comment]
I'm facing the same issue :/

**Comment by joeltgray** [comment]
I've just solved this issue for myself, first ensure you're using the right version of python. 
Next try deleting your virtual environment and creating a new one using 'venv', and insure it's in a directory with no other virtual environments.

Follow the venv docs here, if you have multiple versions of python installed, make you're running these commands from the directory which contains the correct version of python. Version 3.7.* worked for me. 
https://docs.python.org/3/library/venv.html

Follow the package installation guide in the imageai docs. (Page 5)
https://buildmedia.readthedocs.org/media/pdf/imageai/latest/imageai.pdf

After remaking the environments, using the correct version of python, and installing everything carefully, it worked for me.
