### ISSUE TITLE
Issue with ImageAI : Custom Prediction Model Training 

### ISSUE THREAD

**Issue by fninsiima** [OlafenwaMoses/ImageAI#17]
Hello.

I'm training to do a prediction for a custom dataset of leaves.

Firstly, before training, I see something like:  
`input_2 (InputLayer)            (None, **224, 224,** 3)  0` 
Does this mean the dataset is supposed to be resized to **(244,244)** 

Currently, it's just one type of leaf, so i set **num_objects=1**: 
`model_trainer.trainModel(num_objects=1, num_experiments=100, 
                         enhance_data=True, batch_size=32, show_network_summary=True)`

Right now, it produces a value error:
----------------------------------------------------------------------------------------------------------
`ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
```
from keras.utils import to_categorical
y_binary = to_categorical(y_int)
```

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.
` 

Any ideas on how to rectify this?                                 ________________________________________________________________________________________________

**Comment by OlafenwaMoses** [comment]
Please refer to #15
