### ISSUE TITLE
 cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by Danielv123** [OlafenwaMoses/ImageAI#171]
\idenprof> py .\train.py
Traceback (most recent call last):
  File ".\train.py", line 1, in <module>
    from imageai.Prediction.Custom import ModelTraining
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\imageai\Prediction\__init__.py", line 3, in <module>
    from PIL import Image
  File "C:\Users\danie\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\danie\AppData\Roaming\Python\Python37\site-packages\PIL\__init__.py)

I have no idea where to start debugging this. Am I using outdated modules or something?

Install commands:

pip install --user tensorflow numpy scipy pillow matplotlib h5py keras

pip install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl

**Comment by OlafenwaMoses** [comment]
See the link below on resolving this.

https://stackoverflow.com/questions/26505958/why-cant-python-import-image-from-pil/31728305

**Comment by kylefoley76** [comment]
The solutions at stackexchange did not work.  The most straightforward solution recommended

`pip install --no-index -f https://dist.plone.org/thirdparty/ -U PIL
pip install Pillow
pip uninstall PIL
pip uninstall Pillow
pip install Pillow`

**Comment by AlbertoMQ** [comment]
Same as above

**Comment by nscedetas** [comment]
> Same as above

I had the same error (ImportError: cannot import name '_imaging' from 'PIL') when upgrading to Python 3.8.4 - July 13, 2020 64bit for Windows, 
 I did `pip uninstall Pillow `and found that I had another old version lying around.  I uninstalled again until there were no versions left.  Then I did a `pip install Pillow `and it worked just fine.

**Comment by shraddhapp** [comment]
I tried every solution present here, 

1. Uninstalling till everything leftout
2. reinstalling
3. upgrading pip and pillow
4. installing with conda
5. Uninstalling and Installing from Jupyter
6. Manually deleting the folders and installing it again..

Nothing is working for me :(

```
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_28488/3611555843.py in <module>
----> 1 from PIL import Image as img

C:\Program Files (x86)\Python39\lib\site-packages\PIL\Image.py in <module>
    112     # Also note that Image.core is not a publicly documented interface,
    113     # and should be considered private and subject to change.
--> 114     from . import _imaging as core
    115 
    116     if __version__ != getattr(core, "PILLOW_VERSION", None):

ImportError: cannot import name '_imaging' from 'PIL' (C:\Program Files (x86)\Python39\lib\site-packages\PIL\__init__.py
```
