### ISSUE TITLE
i am facing this kind of problem when i am typing the live video prediction code...Please i am new to this..kindly help me out..

### ISSUE THREAD

**Issue by nswaglerevs** [OlafenwaMoses/ImageAI#173]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-f6b9cf59408f> in <module>()
     16 video_path = detector.detectObjectsFromVideo(camera_input=camera,
     17                                 output_file_path=os.path.join(execution_path, "camera_detected_video")
---> 18                                 , frames_per_second=20, log_progress=True, minimum_percentage_probability=40)

TypeError: detectObjectsFromVideo() got an unexpected keyword argument 'camera_input'

**Comment by OlafenwaMoses** [comment]
Post your full code here.

**Comment by nswaglerevs** [comment]
from imageai.Detection import VideoObjectDetection
import os
import cv2

execution_path = os.getcwd()


camera = cv2.VideoCapture(0)

detector = VideoObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath(os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()


video_path = detector.detectObjectsFromVideo(camera_input=camera,
                                output_file_path=os.path.join(execution_path, "camera_detected_video")
                                , frames_per_second=20, log_progress=True, minimum_percentage_probability=40)



Image prediction and video prediction code is working but this live streaming code isn't  working..please kindly help me with this..
Thank you..

**Comment by ayadav10491** [comment]
Facing the same issue

**Comment by OlafenwaMoses** [comment]
Please visit the tutorial linked below on resolving this.

https://heartbeat.fritz.ai/analyze-and-visualize-detected-video-objects-using-keras-and-imageai-d84c99b0ae8e
