### ISSUE TITLE
How does parameter "enhance_data" actually work?

### ISSUE THREAD

**Issue by alexandrubau** [OlafenwaMoses/ImageAI#174]
I'm trying to improve the accuracy on my Custom Trained Models and from what I read a good technique is to augment the images: rotate, skew, flip, etc.
Should I augment the images or is it enough to use *enhance_data=True*?
What does this parameter actually do?

**Comment by OlafenwaMoses** [comment]
Currently, **enhance_data** parameter only performs horizontal flipping. More options will be provided later.
