### ISSUE TITLE
How to use cuda in Object Detection 

### ISSUE THREAD

**Issue by cy69855522** [OlafenwaMoses/ImageAI#175]
How to use cuda in Object Detection ？

**Comment by OlafenwaMoses** [comment]
All you need is to ensure you have the GPU version of Tensorflow installed. See the instructions in the link below.

https://github.com/OlafenwaMoses/ImageAI/blob/master/README.md#real-time-and-high-performance-implementation

**Comment by zahilahham** [comment]
Hello @OlafenwaMoses  ! I'm trying to run imageai in a conda environment on ubuntu and getting the following error 

"Ensure you specified correct input image, input type, output type and/or output image path" 

- OS: Ubuntu 18.04
- "conda list cudnn" output : 
# Name                    Version                   Build  Channel
cudnn                     7.6.5                cuda10.1_0
- Tensorflow-gpu: 1.14.0
- "numba -s" output:
`__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake
Number of accessible CPU cores                : 12
Listed accessible CPUs cores                  : 0-11
CFS restrictions                              : None
CPU Features                                  : 
64bit adx aes avx avx2 bmi bmi2 clflushopt cmov cx16 f16c fma fsgsbase invpcid
lzcnt mmx movbe pclmul popcnt prfchw rdrnd rdseed sahf sgx sse sse2 sse3 sse4.1
sse4.2 ssse3 xsave xsavec xsaveopt xsaves

__OS Information__
Platform                                      : Linux-4.15.0-88-generic-x86_64-with-debian-buster-sid
Release                                       : 4.15.0-88-generic
System Name                                   : Linux
Version                                       : #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
OS specific info                              : debianbuster/sid
glibc info                                    : glibc 2.10

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.7.6
Python Locale                                 : en_US UTF-8

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
Found 1 CUDA devices
id 0     b'GeForce GTX 1650'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 1
`

Do you know what could possibly cause this error ? It's being thrown when the `detector.detectObjectsFromImage` function is called. Looking forward to your reply.
