### ISSUE TITLE
Error when using YOLO model

### ISSUE THREAD

**Issue by arbibz001** [OlafenwaMoses/ImageAI#176]
Hi,

When i try to use the models to detect object in an image. The resnet and Yolotiny are working fine. But when i use Yolo.h5 as model, I get the following error:

![image](https://user-images.githubusercontent.com/17982924/55147182-36c5bd00-5146-11e9-858b-720c9087723c.png)

Please help me as i want to try out the yolo model to detect object.

Regards,

Zohair

**Comment by hellocourse** [comment]
I  have the same problem  as you ,  have you solve this problem yet?   
Please help us to find out why.
many thanks~

**Comment by OlafenwaMoses** [comment]
Hello, do you have the latest versions of Keras installed?

**Comment by OlafenwaMoses** [comment]
Install latest version of  **ImageAI**
`pip3 install imageai --upgrade`
