### ISSUE TITLE
How to get the coordinates of the predicted image

### ISSUE THREAD

**Issue by tryinggo** [OlafenwaMoses/ImageAI#178]
How to get the coordinates of the predicted image

**Comment by DreamWallower** [comment]
这个是一个很棒的项目。
简单易懂，精致易用。
可是在预测物体时只返回了类别和概率，没有返回预测物体在原图像中的位置
但可以通过修改源码，让`detectObjectsFromImage/detectCustomObjectsFromImage`等方法返回预测物体的坐标。
打开__init__.py，找到`detectObjectsFromImage/detectCustomObjectsFromImage`的位置
你可以发现`imageai`时依赖`opencv`的，并且使用`opencv`绘制结果图的

```python
each_object_details["name"] = self.numbers_to_names[label]
each_object_details["detection_details"] = detection_details # add here 添加这句返回坐标
each_object_details["percentage_probability"] = str(score * 100)
```

希望能帮助到你

**Comment by DreamWallower** [comment]
> How to get the coordinates of the predicted image

这个是一个很棒的项目。
简单易懂，精致易用。
可是在预测物体时只返回了类别和概率，没有返回预测物体在原图像中的位置
但可以通过修改源码，让`detectObjectsFromImage/detectCustomObjectsFromImage`等方法返回预测物体的坐标。
打开__init__.py，找到`detectObjectsFromImage/detectCustomObjectsFromImage`的位置
`imageai`时依赖`opencv`的，并且使用`opencv`绘制结果图的
```python
each_object_details["name"] = self.numbers_to_names[label]
each_object_details["detection_details"] = detection_details # add here 添加这句返回坐标
each_object_details["percentage_probability"] = str(score * 100)
```

希望能帮助到你

**Comment by OlafenwaMoses** [comment]
Please follow the tutorial linked below.

https://heartbeat.fritz.ai/analyze-and-visualize-detected-video-objects-using-keras-and-imageai-d84c99b0ae8e
