### ISSUE TITLE
I am unable use tensorflow-gpu

### ISSUE THREAD

**Issue by sivasai8143** [OlafenwaMoses/ImageAI#179]
i have uninstalled tensorflow and installed tensorflow-gpu and installed CUDA, but i am facing below error.OlafenwaMoses please help me out.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-26ea2fbd0d06> in <module>()
----> 1 from imageai.Detection import VideoObjectDetection
      2 import os,sys
      3 import cv2
      4 import time
      5 import datetime,shutil

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\imageai\Detection\__init__.py in <module>()
      1 import cv2
      2 
----> 3 from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
      4 from imageai.Detection.keras_retinanet.utils.image import read_image_bgr, read_image_array, read_image_stream, preprocess_image, resize_image
      5 from imageai.Detection.keras_retinanet.utils.visualization import draw_box, draw_caption

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\imageai\Detection\keras_retinanet\models\resnet.py in <module>()
     17 import warnings
     18 
---> 19 import keras
     20 from imageai.Detection import keras_resnet
     21 from imageai.Detection.keras_resnet import models

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\keras\__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\keras\utils\__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\keras\utils\conv_utils.py in <module>()
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\keras\backend\__init__.py in <module>()
     87 elif _BACKEND == 'tensorflow':
     88     sys.stderr.write('Using TensorFlow backend.\n')
---> 89     from .tensorflow_backend import *
     90 else:
     91     # Try and load external backend.

C:\Users\my00596849\AppData\Local\Continuum\Anaconda3\envs\sivasenvname\lib\site-packages\keras\backend\tensorflow_backend.py in <module>()
      4 
      5 import tensorflow as tf
----> 6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages
      8 from tensorflow.python.ops import tensor_array_ops

ModuleNotFoundError: No module named 'tensorflow.python'

**Comment by anchu-simplecrm** [comment]
try on google colab
