### ISSUE TITLE
Depth camera wrong detections

### ISSUE THREAD

**Issue by MaryBD** [OlafenwaMoses/ImageAI#181]
Hi all, I try to detect the closest margins to the camera, and as shown it returns me the false detection everywhile. Is there something wrong with the depth camera? Does it need calibration? Thanks.
The object is about half meter from camera, and camera returns very often some dots or a circle like object in the distance about 20 cm from camera (as shown).
![image](https://user-images.githubusercontent.com/13030224/55390064-5ab24580-552e-11e9-89e4-e42b0664e49d.png)

![checkdepthplant](https://user-images.githubusercontent.com/13030224/55390098-69006180-552e-11e9-9382-b2990e4b4bab.PNG)

**Comment by OlafenwaMoses** [comment]
Did you use ImageAI's Object Detection for this ?

**Comment by MaryBD** [comment]
No I detect the closest points (withithin a range) to the camera using depth camera.
