### ISSUE TITLE
release tag 1.0.2

### ISSUE THREAD

**Issue by Borda** [OlafenwaMoses/ImageAI#184]
Hello, looking at the Release, there is probably some inconsistency in names - the very first release is tagged `1.0.2` I am wondering if it would be rather `0.0.2`? @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses @johnolafenwa ^^

**Comment by Borda** [comment]
it has not been resolved... :-D

**Comment by OlafenwaMoses** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by OlafenwaMoses** [comment]
**ImageAI** is now at version 2.1.1

**Comment by Borda** [comment]
I see, but your release of 1.0.2 is quite ahead of your 0.1 so you have some issue in the release history... I would recommend just to drop this release https://github.com/OlafenwaMoses/ImageAI/releases/tag/1.0.2
