### ISSUE TITLE
detectCustomObjectsFromVideo() got an unexpected keyword argument 'return_detected_frame'

### ISSUE THREAD

**Issue by Anouk04** [OlafenwaMoses/ImageAI#185]
When I run detectCustumObjectsFromVideo() I get the error: detectCustomObjectsFromVideo() got an unexpected keyword argument 'return_detected_frame'

This is my full code:

from imageai.Detection import VideoObjectDetection 
import os

execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()

custom_objects = detector.CustomObjects(cup=True, spoon=True, bottle=True)

video_path = detector.detectCustomObjectsFromVideo(custom_objects=custom_objects, input_file_path=os.path.join(execution_path, "tea-making-part_Trim_Trim.mp4"), output_file_path=os.path.join(execution_path, "cups_detected"), frames_per_second=20, log_progress=True, return_detected_frame=True)
print(video_path)

TypeError: detectCustomObjectsFromVideo() got an unexpected keyword argument 'return_detected_frame'

I also get the same error when trying to run the per_second_function (or per_frame_function) 

from imageai.Detection import VideoObjectDetection
import os

def forSeconds(second_number, output_arrays, count_arrays, average_output_count):
    print("SECOND : ", second_number)
    print("Array for the outputs of each frame ", output_arrays)
    print("Array for output count for unique objects in each frame : ", count_arrays)
    print("Output average count for unique objects in the last second: ", average_output_count)
    print("------------END OF A SECOND --------------")

video_detector = VideoObjectDetection()
video_detector.setModelTypeAsRetinaNet()
video_detector.setModelPath(os.path.join(execution_path, "resnet50_coco_best_v2.0.1.h5"))
video_detector.loadModel()

video_detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "tea-making-part_Trim_Trim.mp4"), output_file_path=os.path.join(execution_path, "video_second_analysis") ,  frames_per_second=20, per_second_function=forSeconds,  minimum_percentage_probability=30, return_detected_frame=True)

TypeError: detectObjectsFromVideo() got an unexpected keyword argument 'per_second_function'

Can you help me with this?
Thank you!

**Comment by OlafenwaMoses** [comment]
In the **detectObjectsFromVideo()** function, set **return_detected_frame=False**

**Comment by nex0ma** [comment]
%%time
from imageai.Detection import VideoObjectDetection
import os
import cv2

execution_path = os.getcwd()

camera = cv2.VideoCapture(0) 
camera = cv2.VideoCapture("udp://127.0.0.1:23000")
camera.set(3, 1900)
camera.set(4, 1200)
camera.set(cv2.CAP_PROP_FRAME_WIDTH, 1900)
camera.set(cv2.CAP_PROP_FRAME_HEIGHT, 1200)
camera.set(cv2.CAP_PROP_FPS,10) #60)
detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath(os.path.join(execution_path , "yolo.h5"))
detector.loadModel()
detector.loadModel(detection_speed="fast")
# "normal"(default), "fast", "faster" , "fastest" and "flash"


%%time
from imageai.Detection import VideoObjectDetection
import os

execution_path = os.getcwd()

data = []

def forFrame(frame_number, output_array, output_count, detected_frame):
    print("FOR FRAME " , frame_number)
    print("Output for each object : ", output_array)
    print("Output count for unique objects : ", output_count)
    print("Returned Objects is : ", type(detected_frame))
    print("------------END OF A FRAME --------------")
    
def collect_detected_objs(*args):
    print(args)
    
def forSeconds(second_number, output_array, output_count_array, average_counting):
    print("Second Number : ", second_number)
    print("Array for the outputs of each frame ", output_array)
    print("Array for output count for unique objects in each frame : ", output_count_array)
    print("Output average count for unique objects in the last second: ", average_counting)
    
print("------------END OF A SECOND --------------")

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5")) # Download the model via this link https://github.com/OlafenwaMoses/ImageAI/releases/tag/1.0
detector.loadModel()

# video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "traffic.mp4"),
#                                 output_file_path=os.path.join(execution_path, "traffic_detected"),
#                                 frames_per_second=5, #20, 
#                                 per_second_function=collect_detected_objs, 
#                                 log_progress=True)


# video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "08.00.00-09.00.00[R][0@0][0].mp4"),
#                                 output_file_path=os.path.join(execution_path, "08.00.00-09.00.00[R][0@0][0].detected"),
#                                 frames_per_second=5, #20, 
#                                 per_second_function=collect_detected_objs, 
#                                 log_progress=True)

custom_objects = detector.CustomObjects(car=True, motorcycle=True)
video_path = detector.detectObjectsFromVideo(custom_objects=custom_objects, 
                                input_file_path=os.path.join(execution_path, "08.00.00-09.00.00[R][0@0][0].mp4"),
                                output_file_path=os.path.join(execution_path, "08.00.00-09.00.00[R][0@0][0].detected"),
                                frames_per_second=5, #20, 
                                per_second_function=collect_detected_objs, 
                                log_progress=True,
                                return_detected_frame=False)

print(video_path)


------------END OF A SECOND --------------

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

TypeError: detectObjectsFromVideo() got an unexpected keyword argument 'custom_objects'

**Comment by suraj9741** [comment]
how we can accept element inside the def forFrame
