### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by soermejo** [OlafenwaMoses/ImageAI#189]
Is it possible to add new data to a model and continue to train that model with the new data ?

**Comment by OlafenwaMoses** [comment]
This will be added to the next release that will be available soon.

**Comment by OlafenwaMoses** [comment]
Hello @soermejo , thanks for your patience. This feature has been added in the latest version (v2.0.3). See the link below on how to use it.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMTRAINING.md#continuoustraining

Also, visit https://github.com/OlafenwaMoses/ImageAI for all the new features in this release.
