### ISSUE TITLE
 Error during import "VideoObjectDetection"

### ISSUE THREAD

**Issue by erdalalim** [OlafenwaMoses/ImageAI#191]
Hi everyone, I want to run video analysis per second..
Iam trying to import:
from imageai.Detection import VideoObjectDetection
but  **I get error : No module named 'imageai'..**

Iam using Anaconda/Jupyter notebook.
I install ImageAI via Anaconda prompt , pip install.
 
 I  check ImageAI folder,there is no any VideoObjectDetection.py script..

Also I downloaded and ImageAI.zip from here (github) but even there is no **VideoObjectDetection**..
from where I can import?

**Comment by OlafenwaMoses** [comment]
Kindly follow the tutorial linked below on resolving this.

https://heartbeat.fritz.ai/detecting-objects-in-videos-and-camera-feeds-using-keras-opencv-and-imageai-c869fe1ebcdb
