### ISSUE TITLE
Recognition in real time (photos and videos) adding a box around the subject

### ISSUE THREAD

**Issue by andrefilipesp** [OlafenwaMoses/ImageAI#193]
Hello.

I followed the tutorial to code this project and wanted to know how can I do real time recognition and add a box around the person face or other subjects, with information about what it is and if it is possible.

I'm new to coding and I am learning python as I go. Thanks if anyone can help :)

Image example of what I pretend to do:
[https://imgur.com/a/R0IOneG](https://imgur.com/a/R0IOneG)

**Comment by OlafenwaMoses** [comment]
ImageAI doesn't support Face Recognition. You can use face recognition in Python and any programming language in few lines of code using DeepStack , a new project we have released. See the link below.

http://dev.deepstack.cc/docs/python/getting-started.html
