### ISSUE TITLE
Custom Model Type Detector

### ISSUE THREAD

**Issue by BrenevAndrey** [OlafenwaMoses/ImageAI#194]
Hi, I've trained my model and now I'd like to detect this objects. [Here](https://imageai.readthedocs.io/en/latest/detection/index.html) I found that *"The models supported are RetinaNet, YOLOv3 and TinyYOLOv3"*.  
Is there any custom model type detector, exept this three? Or is there any other way to detect objects on the model I trained?
Here ids the code I use:
>from imageai.Detection import ObjectDetection   
import os  
execution_path = os.getcwd()  
detector = ObjectDetection()  
detector.setModelTypeAsRetinaNet()  
detector.setModelPath( os.path.join(execution_path , "model_ex-020_acc-0.500000.h5"))  
detector.loadModel()  
detections=detector.detectObjectsFromImage(input_image=os.path.join(execution_path,"icon.jpg"),  
 output_image_path=os.path.join(execution_path , "iconnew.jpg"))  
for eachObject in detections:  
print(eachObject["name"] , " : " , eachObject["percentage_probability"] )  

Compilation  of this code gives an error about disparity layers.
Thank you for your reply.

**Comment by JStuve** [comment]
I too am waiting for this. It seems that it was mentioned that this feature will be release in the next update. That was back on Feb 22nd of this year.

**Comment by bread-on-toast** [comment]
Hopefully there will be progress soon...

**Comment by OlafenwaMoses** [comment]
Keep up to date with this thread. #8
