### ISSUE TITLE
How to parse output video as a stream instead of saving it as a .avi file?

### ISSUE THREAD

**Issue by PranoveAB** [OlafenwaMoses/ImageAI#195]
Hey!,

Till now I was able to connect to an IP camera and get live feed input, which saves it as an .avi file.
This saved file is not efficient enough. Is there a way to get a output video as a stream like the input stream?

**Comment by PranoveAB** [comment]
Anybody with the same question please, perhaps with a solution? :)

**Comment by OlafenwaMoses** [comment]
You can use the sample code linked below to display the detected video stream.

https://gist.github.com/OlafenwaMoses/a943de4a9c4125d9b2580061b726a6fa

Also study extensively the sample codes provided in the documentation linked below.

https://imageai.readthedocs.io/en/latest/video/index.html
