### ISSUE TITLE
what is the time if i use SqueezeNet to predict a 32x100 picture?

### ISSUE THREAD

**Issue by mengpengfei** [OlafenwaMoses/ImageAI#197]
what is the time if i use SqueezeNet to predict a 32x100 picture?

**Comment by OlafenwaMoses** [comment]
You mean the time it takes to predict a picture of dimension 32 x 100? That will depend on the RAM of your computer.

**Comment by mengpengfei** [comment]
yes ,i known that,can you give me the result on your computer,,thank you very much
