### ISSUE TITLE
The object detection model (RetinaNet) supported by ImageAI can detect 80 different types of objects.

### ISSUE THREAD

**Issue by kangqing** [OlafenwaMoses/ImageAI#199]
Regarding these 80 objects, I would like to ask if I can customize more objects. For example, I want to filter out the fruits in the picture, not just apples, bananas, and oranges. I need it to recognize more fruits and what do I need to do?Looking forward to your answer, thank you

**Comment by OlafenwaMoses** [comment]
Please refer to this thread. #8
