### ISSUE TITLE
ValueError: Ensure you specified correct input image, input type, output type and/or output image path  in Google colab

### ISSUE THREAD

**Issue by karshan77** [OlafenwaMoses/ImageAI#201]
Hi,

Please, check my code below:

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image.png"), output_image_path=os.path.join(execution_path , "imagenew.png"))

for eachObject in detections:
    print(eachObject["name"] , " : " , eachObject["percentage_probability"] )

I am executing object detecting program in Google Colab. I am getting the value error. But, when I am running in jupyter notebook I am not facing any issues. It was working fine. In colab only I am facing the issue.
And I am keeping my notebook and image.png in the same directory.

Thanks.

**Comment by OlafenwaMoses** [comment]
Can you share your notebook with me via my email guymodscientist@gmail.com

**Comment by TrueOleg** [comment]
Any updates on this issue? (I am facing the same error)

**Comment by asurafon** [comment]
i´m having the same problem!!! looks like the problem only happen with Retinanet.
