### ISSUE TITLE
detector.setModelTypeAsYOLOv3() TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by truongnctrieu** [OlafenwaMoses/ImageAI#206]
Hello buddy, 

I got an issue while trying to run code.
Could you please take time to look over for me? 
Thanks for your service.

Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/..... /FirstDetection.py", line 7, in <module>
    _detector.setModelTypeAsYOLOv3()
TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'_

Process finished with exit code 1

**Comment by OlafenwaMoses** [comment]
Can you paste your full code below? Also did you alter/edit the original **ImageAI** source code?

**Comment by GetRektBoy724** [comment]
i also get this error
my code : 
`
#!/usr/bin/python3
from imageai.Detection import ObjectDetection as detector

model_path = "./models/yolo.h5"
input_path = "./input/image.jpg"
output_path = "./output/newimage.jpg"

detector.setModelTypeAsYOLOv3()
detector.setModelPath(model_path)
detector.loadModel()
detection = detector.detectObjectsFromImage(input_image=input_path, output_image_path=output_path)

for eachItem in detection:
    print(eachItem["name"] , " : ", eachItem["percentage_probability"])

`
pls help @OlafenwaMoses

**Comment by GetRektBoy724** [comment]
i run the code from linux
the error was 
`
Traceback (most recent call last):
  File "./objectdetectionfromimage2.py", line 8, in <module>
    detector.setModelTypeAsYOLOv3()
TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'
`
i have all requirements installed and i run it with python 3.8
