### ISSUE TITLE
(question) able to train on top of provided models?

### ISSUE THREAD

**Issue by littlehome-eugene** [OlafenwaMoses/ImageAI#207]
I'm using InceptionV3 as a base. 
I'd like to train it further (modify weights of *.h5 file) by training custom objects.. 

custom model training (https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMPREDICTION.md) talks about creating a new custom model with data.  

I'm wondering if we could further develop models such as `inception_v3_weights_tf_dim_ordering_tf_kernels.h5` 

Thank you for wonderful library

**Comment by OlafenwaMoses** [comment]
We will be provided support for this (transfer learning) in next release coming out soon

**Comment by OlafenwaMoses** [comment]
Hello @littlehome-eugene , as promised , a new version ([v2.0.3](https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMTRAINING.md#transferlearning)) has been released with support for **transfer learning** . You can now train further on pre-trained models. Follow the link below to see how to use this feature.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMTRAINING.md#transferlearning

Also, visit the https://github.com/OlafenwaMoses/ImageAI for all the new features.
