### ISSUE TITLE
Close up Objects in Context not detected

### ISSUE THREAD

**Issue by srikanthgr1** [OlafenwaMoses/ImageAI#21]
I tried running some tests 
Here is what i found I am not sure whether this is an issue to be report or not but nevertheless I am reporting it assuming this might help you 

The below code was used 

`from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
custom_objects = detector.CustomObjects(person=True, car=True)
detections = detector.detectCustomObjectsFromImage(input_image=os.path.join(execution_path , "img1.png"),
                                                   output_image_path=os.path.join(execution_path , "image1_new.png"), 
                                                   custom_objects=custom_objects, minimum_percentage_probability=65)

for eachObject in detections:
   print(eachObject["name"] + " : " + eachObject["percentage_probability"] )
   print("--------------------------------")`

The output was not as expected. This may be problem with resnet also.

![img1](https://user-images.githubusercontent.com/10865036/42246329-d8716abc-7f39-11e8-90c5-9daa5e4b7473.png)
![image1_new](https://user-images.githubusercontent.com/10865036/42246330-d8de177a-7f39-11e8-9186-0170354a0032.png)

**Comment by OlafenwaMoses** [comment]
The problem is that the "minimum_percentage_probability" you stated (65) is too high. Try and keep it at 50. See below the result I obtained using the same image and a "minimum_percentage_probability" of 50.

![imagenew](https://user-images.githubusercontent.com/5909998/42257832-71b2e820-7f50-11e8-96bc-b2138c05cbad.png)

**Comment by srikanthgr1** [comment]
Thank you very much. I am learning all these concepts recently. Sorry abt the wrong questions.

**Comment by OlafenwaMoses** [comment]
It's okay, and you are most welcome.
