### ISSUE TITLE
how can i know track objects is who

### ISSUE THREAD

**Issue by 756537479** [OlafenwaMoses/ImageAI#211]
when i use traking model  to track objects, how can i know who is who，thanks

**Comment by OlafenwaMoses** [comment]
**ImageAI** currently doesn't provide objects or person tracking. You might want to use methods like Kalman filter with the data generated by ImageAI for this purpose. See the link below on examples for Kalman filter.

https://towardsdatascience.com/kalman-filters-a-step-by-step-implementation-guide-in-python-91e7e123b968

**Comment by 756537479** [comment]
thanks
