### ISSUE TITLE
FeatureRequest: Using of own keras-retinanet models & custom training for object-detection

### ISSUE THREAD

**Issue by JoeRu** [OlafenwaMoses/ImageAI#215]
Dear Moses, i did evaluate imageai and want to say **great work**. 
So this is an _feature-request_:
The training of custom sets does result in a training-weights that can predict; I would like to see a feature to add a training for custom object-detection as well.

As well i like to ask - wether it is possible to use a custom-weight file from keras-retinanet or yolov3 or yolov3-tiny with your api?

Johannes

**Comment by OlafenwaMoses** [comment]
Kindly refer to this thread #8
