### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed 

### ISSUE THREAD

**Issue by Angus1996** [OlafenwaMoses/ImageAI#218]
When I　was using the Imageai　in windows　platform, it works.However, I try it in ubuntu, it reported this error.
My　gpu is rtx 2070, tensorflow 1.13.1, cuda10.0
Is there anyone who know how to solve it?

**Comment by OlafenwaMoses** [comment]
Refer to this discussion.

https://github.com/tensorflow/tensorflow/issues/11812
