### ISSUE TITLE
custom_model_prediction.py

### ISSUE THREAD

**Issue by Sarthak-Shah** [OlafenwaMoses/ImageAI#221]
Though i have trained my model and given the proper path to locate .JSON and .h5 files after model training, it's not revoking predictions and probabilities as per new model.
somehow its playing in Resnet model only and using that predefined person's designation only.

**Comment by OlafenwaMoses** [comment]
What classes of objects do you want to predict? What prediction results are you getting from your custom trained model?

**Comment by Sarthak-Shah** [comment]
Hi ,
     I want to predict one Android application's typical icons whch used to slightly alter according to different Android UI and resolution.
So I am developing one class from which my trained model will detect that icon and click it by finding coordinate further using UIautomator.

On Thu, May 30, 2019, 7:22 PM MOSES OLAFENWA <notifications@github.com<mailto:notifications@github.com>> wrote:

What classes of objects do you want to predict? What prediction results are you getting from your custom trained model?

**Comment by OlafenwaMoses** [comment]
Please refer to #8 for object detection
