### ISSUE TITLE
Continous model training

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#223]
Hello.

Is it possible to add new images to existing dataset or expand the dataset with new items (folders) and then continue training existing model (expanding model)?

**Comment by OlafenwaMoses** [comment]
1) It is possible to add new images to the existing dataset
2) You can only expand the dataset with new items by using **transfer learning** on the existing model and not **continuous training**. For example , if your previous dataset was 10 objects and now it becomes 15, you will instead write the training function as seen below. 

`trainer.trainModel(num_objects=15, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True,transfer_from_model="existing_model.h5", initial_num_objects=10)`

**Comment by Gytis123** [comment]
thanks
