### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#226]
Hello,

Is it possible to stop training when model hits accuracy 1.000000? Because there's no point to continue training if unimproved models not saved.

**Comment by OlafenwaMoses** [comment]
You can always stop the training once it has reached the desired accuracy. However, ensure your model is not over-fitting. Over-fitting usually leads to incredibly high accuracy when you train and test with few images. This results into poor predictions when applied to new images.

**Comment by Gytis123** [comment]
How to prevent over-fitting?

**Comment by OlafenwaMoses** [comment]
1) Sufficient amount of training Images (at least 500 images per class)
2) Apply data augmentation in your training by setting **enhance_data=True** in your **.trainModel()** function.
