### ISSUE TITLE
How to do transfer_from_model from yolo or retinanet models?

### ISSUE THREAD

**Issue by nguyenlequocdat04** [OlafenwaMoses/ImageAI#227]
```
from imageai.Prediction.Custom import ModelTraining
import os
trainer = ModelTraining()
trainer.setModelTypeAsResNet()
trainer.setDataDirectory("dataset")
trainer.trainModel(num_objects=1, num_experiments=50, enhance_data=True, 
                   batch_size=32, show_network_summary=True,
                   transfer_from_model="model/resnet50_coco_best_v2.0.1.h5", 
                   initial_num_objects=1000)
```
I try to make a model can detect 80 objects in "resnet50_coco_best_v2.0.1" but have some additions. But i got error:
`ValueError: You are trying to load a weight file containing 116 layers into a model with 107 layers.`
Am i doing it right? If not, can you suggest any solution. Thanks so much!

**Comment by OlafenwaMoses** [comment]
The `resnet50_coco_best_v2.0.1.h5` model is for object detection. However, the _**ModelTraining()**_ class is for training prediction models and not for detection models. That is why it thrown an error when you attempted to transfer from the detection model.

We are working on providing support for training custom object detection models and it will be released soon. Follow this thread for more on this. #8
