### ISSUE TITLE
Custom Model Testing issue

### ISSUE THREAD

**Issue by Aniket1492** [OlafenwaMoses/ImageAI#232]
I have developed Model using ImageAI, where its working fine with from imageai.Prediction.Custom import CustomImagePrediction library

now i am using same model for Object detection and i am getting this following issue. 

  File "C:\Python35\lib\site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 4 layers into a model with 116 layers.

**Comment by nguyenlequocdat04** [comment]
The model you trained is for prediction, not detection. You can see how to use your model here: 
https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMPREDICTION.md
I realized it from my #227 issue :))

**Comment by OlafenwaMoses** [comment]
Thanks for making the clarification @nguyenlequocdat04 . 
@Aniket1492 Follow this thread #8
