### ISSUE TITLE
the size of image in the model

### ISSUE THREAD

**Issue by ChanKimSiong** [OlafenwaMoses/ImageAI#236]
1) If I would like to train my model, the size of image in the model need to be same? 
2) If the size is different, will have any problem? 
3) The light and position of object in image will affect the prediction?
Below is Example :
![silver_ring_4](https://user-images.githubusercontent.com/49263589/60320729-2f17ed80-99ad-11e9-9b8e-4e37b5e62e79.jpg)
![silver_ring_5](https://user-images.githubusercontent.com/49263589/60320732-317a4780-99ad-11e9-8d14-2355e5b07fe9.jpg)

**Comment by OlafenwaMoses** [comment]
The size of the images do not need to be the same. **ImageAI** will automatically resize the images to a default value of **224** x **224**.
