### ISSUE TITLE
Image prediction with object that is not in dataset.

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#238]
I have trained DataSet with 6 objects:
1. apple
2. strawberry
3. pie
4. coconut
5. sweets
6. chocolade

When i send photo resembling the object from trained dataset it predicts correct
object name with always aprox. 99.98% accuracy.

Problem arises when i send photo with object which is not in trained dataset
(for example: phone or other random object not in the trained dataset). It predicts and returns some
object (which exist in trained dataset) name (for example: apple or other within dataset depending on sent photo) with also aprox. 99.98 accuracy.

Is it somehow possible to prevent this problem?
And how can i know if object is not exist in trained dataset.

**Comment by OlafenwaMoses** [comment]
Hello @Gytis123 , the model generated after the training is a fixed-class classification model which means for any image you input, it will attempt to classify it as any of the objects in your dataset.

**N.B:** Please not that for every input sent to the trained model, prediction results with probabilities will be generated for all the classes in your dataset. However, the correct class will have the highest probability.
