### ISSUE TITLE
Train with ResNet50

### ISSUE THREAD

**Issue by ChanKimSiong** [OlafenwaMoses/ImageAI#239]
Morning Sir, I would like to add some category (like ring) in resnet50_weights_tf_dim_ordering_tf_kernels.h5 . 
1) Have any code that I can use?
2) I have a doubt which is py source code or py project can be compile to dll or exe?

**Comment by OlafenwaMoses** [comment]
See this tutorial.

https://medium.com/deepquestai/transfer-learning-with-5-lines-of-code-5e69d0290850

**Comment by ChanKimSiong** [comment]
Sir, thank for your tutorial. It work for me. I have one question, predict one time need almost 16 seconds , have any approach to decrease the time?

**Comment by ChanKimSiong** [comment]
I have found the solution :
 prediction.loadModel(prediction_speed="fast"). 
Thank for your time, Sir.

**Comment by OlafenwaMoses** [comment]
You are most welcome. @ChanKimSiong
