### ISSUE TITLE
imageai-2.0.1-py3-none-any.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by vikaskyadav** [OlafenwaMoses/ImageAI#24]
I am trying to run the setup using your medium article and found this error in the last installation step.

I am using the Jupiter notebook with default ipython kernel on ubuntu 16.04LTS

**Comment by OlafenwaMoses** [comment]
Did you ensure you chose Python 3.x for the Jupyter Notebook?  ImageAI currently doesn't support Python 2.7.

**Comment by justaskumelis** [comment]
What version of python3 are you using? ImageAI does not work with latest python3, try using python 3.5.2.

**Comment by mmmahhhhe** [comment]
my windows has install python3.5 ,tensforflow1.2 ,ubuntu py3.6 tf1.8 .but when i install other page like h5py scipy ,system will point htlm5lib and others need specific version package .so could you tell me some package's version of your computer ? tensorflow tensorboard markdown bleach mezzanine h5py  scipy keras numpy thank you very much

**Comment by OlafenwaMoses** [comment]
@mmmahhhhe Please upgrade your Tensorflow to at least version 1.4.0 and do let me know if the error persists.

**Comment by OlafenwaMoses** [comment]
Meanwhile, a new version of ImageAI ( version 2.0.2 ) is now available with full documentation in English and Chinese. 

English 
https://imageai.readthedocs.io

Chinese
https://imageai-cn.readthedocs.io
