### ISSUE TITLE
TF2 support

### ISSUE THREAD

**Issue by ptoulza** [OlafenwaMoses/ImageAI#241]
Hello,

Thank you for your great work.
I'm wondering if you plan to support TF2 ? For the moment, I got some errors on TF sessions.
Do you have any roadmap for this support ?
Thx again.

Pierre

**Comment by sissiwup** [comment]
I have tried also, TF2.0 is not supported yet.

**Comment by OlafenwaMoses** [comment]
Not yet. We will work on providing support soon.

**Comment by OlafenwaMoses** [comment]
Let's move this discussion here #263
