### ISSUE TITLE
faster than flash

### ISSUE THREAD

**Issue by if4lcon** [OlafenwaMoses/ImageAI#243]
using Linux and resnet without gpu make detection time very slow I'm waiting for 16 seconds only for just one image. can I make it more faster ?

**Comment by OlafenwaMoses** [comment]
You can use the **TinyYOLOv3** model and by setting **detector.setModelTypeAsTinyYOLOv3()** and downloading the model file in the link below.

https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo-tiny.h5

**Comment by OlafenwaMoses** [comment]
Please not that there is limit to the speed your non-GPU system can achieve. Also note that accuracy decreases as speed increases.

**Comment by if4lcon** [comment]
Thank you man for your great effort I decided to use Azure API for now until my hosting provider release affordable cloud GPU server
