### ISSUE TITLE
Prediction Result Not So Accurate

### ISSUE THREAD

**Issue by ChanKimSiong** [OlafenwaMoses/ImageAI#244]
This is the code i use to predict image :
from imageai.Prediction.Custom import CustomImagePrediction
import os
import sys
execution_path = os.getcwd()
prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath(os.path.join(execution_path, "gold/models/model_ex-009_acc-0.831250.h5"))
prediction.setJsonPath(os.path.join(execution_path, "gold/json/model_class.json"))
prediction.loadModel(num_objects=4)
predictions, probabilities = prediction.predictImage(os.path.join(execution_path, sys.argv[1]), result_count=5)
for eachPrediction, eachProbability in zip(predictions, probabilities):
	print(eachPrediction , " : " , eachProbability)

Train Model code : 
from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("gold")
model_trainer.trainModel(num_objects=4, num_experiments=16, enhance_data=True, batch_size=32, show_network_summary=True)

This is the image I use to predict : 
![test_earrings_5](https://user-images.githubusercontent.com/49263589/61165889-e3db0e80-a558-11e9-937b-0294827544f3.jpg)

This is the number of image : 
Found 2492 images belonging to 4 classes.
Found 800 images belonging to 4 classes.

Prediction Result : 
necklace  :  74.86147284507751
ring  :  20.74337750673294
bracelet  :  3.1486723572015762
earrings  :  1.2464756146073341

The result is not so accurate. Have any method to increase the accuracy?

**Comment by OlafenwaMoses** [comment]
If you want the prediction to be more accurate, I advice that you do the following:
- train the model for at least 100 experiments
- use transfer learning ( https://medium.com/deepquestai/transfer-learning-with-5-lines-of-code-5e69d0290850  )

**Comment by ChanKimSiong** [comment]
Sir, thank for your suggestion. I will try it. Once I get the result, i will update here.

**Comment by ChanKimSiong** [comment]
Hi Sir, I already use transfer learning to train my model and I set num_experiments= 20. I use 300 image to train and 100 image to test. The accuracy is increase but still have some image is not so accurate. 

Is the amount of image not enough or the num_experiments is too less?
I want to know the image prediction is based on which part of image(like background or object or position or ...) to predict?
