### ISSUE TITLE
Prediction Accuracy

### ISSUE THREAD

**Issue by ChanKimSiong** [OlafenwaMoses/ImageAI#249]
[https://github.com/OlafenwaMoses/ImageAI/issues/244](url)

Hi Sir, this is the feedback of above issue. I already use transfer learning to train my model and I set num_experiments= 20. I use 300 image to train and 100 image to test. The accuracy is increase but still have some image is not so accurate. 

Is the amount of image not enough or the num_experiments is too less?
I want to know the image prediction is based on which part of image(like background or object or position or ...) to predict?

**Comment by OlafenwaMoses** [comment]
Try to collect more images for training. This will definitely increase the accuracy on new images.

**Comment by ChanKimSiong** [comment]
How about the num_experiments? Do I need to set it to 50 or above?
May I know the image prediction is based on which part of image(like background or object or position or ...) to predict? So i can use the condition(like background or object or position or ...) to collect image to increase the accuracy.

**Comment by OlafenwaMoses** [comment]
The higher the *num_experiments*, the higher the chance of the training generating a more accurate model.

As per getting more images, ensure the images are as diverse as possible in variations of backgrounds and environment. The models trained are deep learning models that learn by themselves the necessary features to correctly predict the images.

**Comment by ChanKimSiong** [comment]
Morning Sir, thanks for your suggestion. I will collect more images and set the num_experiments to 100. After I get the result, i will feedback here.
