### ISSUE TITLE
Realtime detection with VideoCapture

### ISSUE THREAD

**Issue by andreqwert** [OlafenwaMoses/ImageAI#259]
Good afternoon!

Is there any possibility to launch model showing bounding boxes from web-camera? I figured out only how to get bounding boxes coordinates in command line but the videostream is not switched on at this moment and I don't understand how to switch it on?

**Comment by OlafenwaMoses** [comment]
See this tutorial.

https://heartbeat.fritz.ai/analyze-and-visualize-detected-video-objects-using-keras-and-imageai-d84c99b0ae8e
