### ISSUE TITLE
Training custom object detection model stuck 

### ISSUE THREAD

**Issue by schko** [OlafenwaMoses/ImageAI#262]
Ran on Colab and locally, stuck on:
Epoch 1/200

Any suggestions? Tried tf nightly download (incompatibility with Keras), and older tensorflow versions.

**Comment by OlafenwaMoses** [comment]
Depending on the size of your dataset, an epoch can take between 15 mins to an hour. Also, did you change the Tensorflow-GPU on your runtime to 1.13.1? It was advised in the comments and documentation I provided. 

I suggest you install Tensorflow GPU 1.13.1 and restart your run time before initiating training.

`pip3 install tensorflow-gpu==1.13.1`

**Comment by schko** [comment]
Thanks, this works now!

**Comment by rola93** [comment]
I can't upgrade to 1.13, need to use 1.12 for compatibility with cuda/cudnn configuration.

Is there any other change you can suggest? it's taking ages with 1845 samples...
