### ISSUE TITLE
how to add new type of object in Custom Object Detection

### ISSUE THREAD

**Issue by AdrianNg** [OlafenwaMoses/ImageAI#264]
`The object detection model (RetinaNet) supported by ImageAI can detect 80 different types of objects. `

Hi team.  I have a new type of object "scooter" want to use but it is not in the listed "80 different types of objects". Could you please tell me how I can achieve that ?

Thanks,

A

**Comment by OlafenwaMoses** [comment]
Support for training YOLOv3 on your custom objects has been supported. We will add RetinaNet later. See the links below.

Tutorials: https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff

Documentations

_Training:_ https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTIONTRAINING.md

_Detection:_
https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTION.md

_Video Detection:_
https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMVIDEODETECTION.md

**Comment by Jess-caaaa** [comment]
hi , @OlafenwaMoses , thx for the reply. 
is there any way to combine my own 'scooter' model and your resnet50_coco_best_v2.0.1.h5 in one screen detection ?
for example ,  i want to detect both my 'scooter' and your 'car' in one screen.

thanks,

**Comment by MarinaJIN** [comment]
Thanks for the amazing work!
I have the same question:
What if we want to add new objects progressively into the dataset? Is there any better way instead of re-train the whole datasset from the beginning?

**Comment by Jess-caaaa** [comment]
Sorry , as far as I know, you have to re-train the whole dataset.



Sent from myMail for iOS


Friday, 28 February 2020, 9:11 PM +1300 from notifications@github.com  <notifications@github.com>:
