### ISSUE TITLE
Image processing prior to custom object detection training?

### ISSUE THREAD

**Issue by schko** [OlafenwaMoses/ImageAI#269]
I am interested in custom training for object detection in video for novel objects (e.g. eagles). Is there any recommendation on a rescaling the raw images prior to labeling via LabelImg for the purposes of object detection in video? 

Or should I just leave the images in their original size when labeling? I saw online for another purpose rescaling to 800x600 but unsure if it applies to ImageAI.

**Comment by OlafenwaMoses** [comment]
You can keep the images at their original size. The training network will automatically re-scale the image to sizes between 288 to 488 as it runs through many experiments.

**Comment by schko** [comment]
Thanks so much for your help!

**Comment by OlafenwaMoses** [comment]
Hello please see an urgent bug fix update here #278
