### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].

### ISSUE THREAD

**Issue by PushkarChatterji** [OlafenwaMoses/ImageAI#271]
Hi,

I have trained the yolov3 on a custom data set of 200+ images with 1 class for 200 epochs.

When I try to load this trained model back for video detection using your code, I get the error in the title of this post.

Any suggestions?

**Comment by OlafenwaMoses** [comment]
Multiple models were saved during the training. Have you tried any of the other models?

**Comment by OlafenwaMoses** [comment]
Also, have you tried to detect the object from an image?

**Comment by PushkarChatterji** [comment]
The saved model(s) run perfectly for images.
But not for video input

**Comment by OlafenwaMoses** [comment]
Incredible. I will run a check on this and give you feedback. You can also send me the model as well as the **detection_config.json** file via my email guymodscientist@gmail.com to accelerate the debug.

**Comment by PushkarChatterji** [comment]
Got it. I'll send you a dropbox link for the model as it's too big for gmail...

**Comment by OlafenwaMoses** [comment]
Hello, I just ran the video detection code using the model and json files you shared with me. It seems to work perfectly. See the Google drive link below for the results I obtained.

https://drive.google.com/file/d/12nrZ72DSITTBSrnMCy1q_nmkKe1lWHSj/view?usp=sharing

**Comment by OlafenwaMoses** [comment]
I will advice that you do the following:

- remove the spaces in the video filename and try again
- check the versions of Tensorflow, Keras and OpenCV installed an comment them here.

**Comment by PushkarChatterji** [comment]
Hmm...thats interesting that it worked for you.... (the bounding boxes are like the height and the width have been switched...)

Removing the spaces in the file name didn't work for me. I am getting the same error:

Here are the versions:
tensorflow-gpu = 1.13.1
Keras = 2.2.4
opencv-python= 4.1.0.25

And here's the code I am trying to run:

from imageai.Detection import VideoObjectDetection
import os


detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath("/models/detection_model-ex-50--loss-13.44.h5")
detector.loadModel()

video_path = detector.detectObjectsFromVideo(input_file_path="video_test_ok.avi",
                                output_file_path="traffic_detected.avi"
                                , frames_per_second=24, log_progress=True)
print(video_path)

**Comment by OlafenwaMoses** [comment]
Now I know where the issue is. You are using the wrong class for your video object detection. 

- **from image.Detection import VideoObjectDetection** : This class is for the inbuilt, pre-trained object detection model. NOT YOUR CUSTOM MODEL.

- **from imageai.Detection.Custom import CustomVideoObjectDetection**: This is the class for your custom detection model. Visit the link below for all the details.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMVIDEODETECTION.md

**Comment by PushkarChatterji** [comment]
Indeed! My bad.

Everything works perfectly now. Thank you!

Off topic:
When I use the json config file with the anchor values calculated at training time, I get the bounding boxes in the following shape in running the saved model:
![test-detected](https://user-images.githubusercontent.com/51086460/62632361-09322100-b93b-11e9-8001-d881972b612f.jpg)
 
However, when i swap the values around in the anchor file, i get the desired bounding boxes:
![Screenshot from holo1-detected3 avi](https://user-images.githubusercontent.com/51086460/62632475-31218480-b93b-11e9-9da7-df82fd473a07.png)

Possibly something being swapped with writing to json?

**Comment by OlafenwaMoses** [comment]
Can you put in the comment the arrangement of the anchor values **before** and **after** your swap?

**Comment by PushkarChatterji** [comment]
Here is the original:
{
    "labels" : [
        "customer"
    ],
    "anchors" : [
        [
            129,
            65,
            73,
            64,
            104,
            49
        ],
        [
            134,
            45,
            73,
            38,
            119,
            34
        ],
        [
            38,
            29,
            95,
            28,
            63,
            26
        ]
    ]
}



Here is the swapped:
{
    "labels" : [
        "customer"
    ],
    "anchors" : [
        [
            65,
            129,
            64,
            73,
            49,
            104
        ],
        [
            45,
            134,
            38,
            73,
            34,
            119
        ],
        [
            29,
            38,
            28,
            95,
            26,
            63
        ]
    ]
}

**Comment by OlafenwaMoses** [comment]
OH MY! Bug discovered and fixed. Kindly see this update here. #278

**Comment by achipalamwazani** [comment]
I used a pretrained models provided, and am trying to run the sample code. I am using the right class: from imageai.Detection.Custom import CustomVideoObjectDetection. However, I am still running in the same error till right now, trying to detect object from video file. Has anyone managed to resolve this issue please:

P.S: I am able to detect objects from a camera, however, it is detecting everything, and I would like to detect only objects of my interest

**Comment by ayushpandey2708** [comment]
I'm having similar error when I implemented-
yolo_model = yolo_body(Input(shape=(None, None, 3)), num_anchors//3, num_classes)
yolo_model.load_weights("model_data/trained_weights_final.h5")

the error is as following-

InvalidArgumentError                      Traceback (most recent call last)
c:\users\91884\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\framework\common_shapes.py in _call_cpp_shape_fn_impl(op, input_tensors_needed, input_tensors_as_shapes_needed, require_shape_fn)
    685           graph_def_version, node_def_str, input_shapes, input_tensors,
--> 686           input_tensors_as_shapes, status)
    687   except errors.InvalidArgumentError as err:

c:\users\91884\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    515             compat.as_text(c_api.TF_Message(self.status.status)),
--> 516             c_api.TF_GetCode(self.status.status))
    517     # Delete the underlying status object from memory otherwise it stays alive

InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,75] and [18,1024,1,1]. for 'Assign_1082' (op: 'Assign') with input shapes: [1,1,1024,75], [18,1024,1,1].

kindly help.

**Comment by ayushpandey2708** [comment]
I have solved this problem by-
yolo_model.load_weights("model_data/trained_weights_final.h5",by_name=True,skip_mismatch=True)

but now I'm having error in prediction,here is sample code-
def predict(sess, image_path):
    
    start_time = time.time()
  
    image_data, image = preprocess_image(image_path)
    
    image_shape = image_data.shape[1:3]
    
    boxes, scores, classes = yolo_eval(yolo_model.output, anchors, num_classes, image_shape)

    out_boxes, out_scores, out_classes = sess.run([boxes, scores, classes], 
                                                  feed_dict={yolo_model.input:image_data,
                                                             K.learning_phase(): 0})
    print ("Time taken:", time.time()-start_time, "sec")
    print('Found {} boxes for {}'.format(len(out_boxes), image_path.split("/")[1]))
    
    colors = get_colors_for_classes(num_classes)

    draw_boxes(image, out_boxes, out_classes, class_names, out_scores)

    output_path = "output_"+ str(image_path.split("/")[1])+ ".jpg"
    image.save(output_path, quality=90)

    output_image = Image.open(output_path)
    
    plt.grid(visible=False)
    plt.xticks([])
    plt.yticks([])
    imshow(output_image)
predict(sess, "yolo/dog.jpg")



please help.

**Comment by ayushpandey2708** [comment]
I was having this error because of missing draw_boxes and get_colors_for_classes in utils.py
add these from here-
**[https://github.com/dudeperf3ct/DL_Notebooks/tree/master/Object%20Detection/Keras/yolo](url)**

problem solved.
