### ISSUE TITLE
Custrom detection GPU RAM required for different batch sizes

### ISSUE THREAD

**Issue by nineclicks** [OlafenwaMoses/ImageAI#274]
Currently on my local GPU with 4gb of RAM I am unable to use batch sizes greater than 2. That appears to use about 3GB of RAM. Does the RAM use increase with batch size linearly? Or otherwise does anyone have an estimate of the amount needed for batch sizes of 4 or 8? The tutorial mentions the k80 with 24GB of RAM as I understand.

**Comment by Meulen92** [comment]
On my RTX2070 8GB I can confirm I cannot go higher than batch_size=6.

**Comment by nineclicks** [comment]
Thank you, this answers my question.
