### ISSUE TITLE
TypeError: trainModel() got an unexpected keyword argument 'continue_from_model'

### ISSUE THREAD

**Issue by DiMiTriFrog** [OlafenwaMoses/ImageAI#277]
I have a training model of dataset and I would like to load this model for continue training (I use colab and I training with the time it's on).

When I use the parameter of trainModel(continue_from_model(path)) I have this error ->

```
TypeError                                 Traceback (most recent call last)
<ipython-input-12-d1ae75a75d0e> in <module>()
      4 model_trainer.setModelTypeAsResNet()
      5 model_trainer.setDataDirectory("/content/nude")
----> 6 model_trainer.trainModel(num_objects=4, num_experiments=200, enhance_data=True, batch_size=32, continue_from_model="/content/nude/models/model_ex-001_acc-0.303472.h5", show_network_summary=True)

TypeError: trainModel() got an unexpected keyword argument 'continue_from_model'
```

I'm following this guide : https://buildmedia.readthedocs.org/media/pdf/imageai/latest/imageai.pdf

**Comment by OlafenwaMoses** [comment]
Kindly install the latest version of ImageAI (v2.1.2) by running the command below.

`pip3 install imageai --upgrade`
