### ISSUE TITLE
using hololens-ex-60--loss-2.76.h5 to object detection error occurred

### ISSUE THREAD

**Issue by Professorchen** [OlafenwaMoses/ImageAI#279]
the code i want to run as follow:
```
from imageai.Detection import ObjectDetection

detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath('./model/hololens-ex-60--loss-2.76.h5')
detector.loadModel()
```
then consle show this
```
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].
```
how can i solve this problem?

**Comment by OlafenwaMoses** [comment]
The Hololens detection model is a custom model. There fore you should use 
`from imageai.Detection.Custom import CustomObjectDetection
detector = CustomObjectDetection()`
and not 
`from imageai.Detection import ObjectDetection
detector = ObjectDetection()` in your code.

**Comment by OlafenwaMoses** [comment]
See the  full code here.

https://gist.github.com/OlafenwaMoses/d399e61386fc4adb4e67e834cde50c00#file-custom_hololens_detection-py

**Comment by Professorchen** [comment]
> The Hololens detection model is a custom model. There fore you should use
> `from imageai.Detection.Custom import CustomObjectDetection` and `detector = CustomObjectDetection()`
> and not
> `from imageai.Detection import ObjectDetection` and `detector = ObjectDetection()` in your code.

thank you for your answer
