### ISSUE TITLE
Custom Model Training

### ISSUE THREAD

**Issue by jedibatman** [OlafenwaMoses/ImageAI#28]
I noticed that in #15 it was highlighted that you need at minimum 2 classes of objects to be able to utilize this functionality.

That seems like an arbitrary requirement so I was wanting to understand if this is a technical limitation or if this is just an opinionated decision that has been made.

**Comment by jedibatman** [comment]
Thank you for the prompt response!

**Comment by OlafenwaMoses** [comment]
You are welcome.
