### ISSUE TITLE
how to use gpu to train my custom model

### ISSUE THREAD

**Issue by Professorchen** [OlafenwaMoses/ImageAI#280]
when i train a custom model on my dataset how can i know whether gpu is worked ？
here is my code:
```
from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("./pic/flower")
model_trainer.trainModel(num_objects=5, num_experiments=100, enhance_data=True, batch_size=48, show_network_summary=True)
```

**Comment by OlafenwaMoses** [comment]
All you need is to ensure you have the GPU version of **Tensorflow** installed and not the CPU version.

**Comment by Professorchen** [comment]
if i have installed  both the GPU version of Tensorflow and the CPU version, which one will be used?

**Comment by OlafenwaMoses** [comment]
It will use the last installed version.

**Comment by Professorchen** [comment]
I'm puzzled. As CUSTOMTRAINING.md recommended, I use Google Colab to run my code, but it still take hours to train custom model. I wonder how do I know the GPU is working.

**Comment by OlafenwaMoses** [comment]
It depends on the size your dataset. 

Also, did you changed your Colab Notebook's runtime to GPU before training?

**Comment by Professorchen** [comment]
Yes, of course, I have changed the setting to GPU before traning.
My dataset is consist of 3,170 train image and 500 test image. All of those image belong to 5 classes. Each epoch costs about an hour.

**Comment by OlafenwaMoses** [comment]
Can you share the link to the Notebook here? I just ran a train test on Colab in the **IdenProf** dataset (9000 train images, 2000 test images) and it took a maximum of **5 mins** per epoch. 

Link to my Notebook:  https://colab.research.google.com/drive/1HzjOfOg-mp6TILKZe-3ROkgEAG9xLi9N

**Comment by Professorchen** [comment]
my Link : https://colab.research.google.com/drive/1z6F7Y408mM20-kaZTcDeg6UUbGVwJbVR
Can you give me your email address so that I can invite you to edit my Notebook ？

**Comment by Professorchen** [comment]
Maybe the speed depends on the network speed ? I'm in China. So I have to use vpn to connect to Google Colab.

**Comment by OlafenwaMoses** [comment]
guymodscientist@gmail.com

**Comment by Professorchen** [comment]
I have shared my Notebook(https://colab.research.google.com/drive/1z6F7Y408mM20-kaZTcDeg6UUbGVwJbVR) with you. I reinstall tensorflow-gpu and uninstall tensorflow, but it still took about 20 mins per epoch.

**Comment by OlafenwaMoses** [comment]
I just downloaded the[ **Idenprof**](https://github.com/OlafenwaMoses/IdenProf) dataset with 11,000 images into the notebook without mounting the drive and train on the dataset. It trains just normally at a max of 5mins per epoch.

**Comment by Professorchen** [comment]
I have solved my problem. Thank you very much!

**Comment by OlafenwaMoses** [comment]
You are most welcome. Please kindly comment how you resolved it so that others experiencing the same problem can benefit from the details.

**Comment by rakib-ahsan** [comment]
> I have solved my problem. Thank you very much!

@Multhree  It would be really nice if you could inform us how you solved the problem?

**Comment by rakib-ahsan** [comment]
> I just downloaded the[ **Idenprof**](https://github.com/OlafenwaMoses/IdenProf) dataset with 11,000 images into the notebook without mounting the drive and train on the dataset. It trains just normally at a max of 5mins per epoch.

@OlafenwaMoses It would be of great help if you could share a link to your Notebook that trains at max 5 mins per epoch.

**Comment by rakib-ahsan** [comment]
Just avoiding connecting to google drive would train a model a lot faster!
