### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'idenprof/train'

### ISSUE THREAD

**Issue by vishal271998** [OlafenwaMoses/ImageAI#282]
I'm using google colab.
I changed the dir to contents/idenprof and I'm able to display any image inside the dataset but this issue still persists.
The code is attached in the picture.
![idenprof2](https://user-images.githubusercontent.com/52848931/62818446-f13de580-bb64-11e9-8c8c-28f547de4407.JPG)
![idenprof](https://user-images.githubusercontent.com/52848931/62818408-9c01d400-bb64-11e9-82d0-9b32b5b4b347.JPG)

**Comment by vishal271998** [comment]
I also used the 'download zip to colab and unzip' approach but it's giving the same error.
My notebook url:
https://colab.research.google.com/drive/1RgO4XCvhM9o88FW2UrU3Ua6jtFqItyua#scrollTo=2Bqr8jMhRFNE

**Comment by vishal271998** [comment]
Can you please tell me how to solve this error ?

**Comment by OlafenwaMoses** [comment]
This is a file path. Ensure the folder **Idenprof** exist in the main folder of your notebook and contains the corresponding **train** and **test** sub-folders.
