### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by acleitao76** [OlafenwaMoses/ImageAI#285]
Amazing work guys just tested and got so excited with the results. Can you help me pointing me to a model for recognize bibnumbers plates for marathons (I just need the model I'm trying to use ImageAI as the base to improve accuracy of my ocr software)

**Comment by OlafenwaMoses** [comment]
You can easily train a new model to detect each **bibnumbers** so that you can independently process each using your existing OCR setup. Visit the tutorial linked below on training the model.

https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff
