### ISSUE TITLE
ValueError: Ensure you specified correct input image, input type, output type and/or output image path

### ISSUE THREAD

**Issue by cerlymarco** [OlafenwaMoses/ImageAI#286]
I don't understand why this happens on jupyter notebook...

```
detector = ObjectDetection()
detector.setModelTypeAsTinyYOLOv3()
detector.setModelPath("D:/DATA/yolo-tiny.h5")
detector.loadModel()
custom_objects = detector.CustomObjects(person=True)

original = cv2.imread('img.jpg')

detections = detector.detectCustomObjectsFromImage(input_image=original, input_type="array", custom_objects=custom_objects, minimum_percentage_probability=80)

```

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\PIL\Image.py in save(self, fp, format, **params)
   1986             try:
-> 1987                 format = EXTENSION[ext]
   1988             except KeyError:

KeyError: ''

During handling of the above exception, another exception occurred:
...
ValueError: Ensure you specified correct input image, input type, output type and/or output image path

**Comment by OlafenwaMoses** [comment]
Try to specify an output image path in the **detectCustomObjectsFromImage()** function.

`E.g output_image_path='img-detected.jpg'`

**Comment by cerlymarco** [comment]
Thanks

**Comment by Prasan97** [comment]
@OlafenwaMoses Good day ! ,

This is my Code snippet 


**import imageai

import tensorflow as tf
#tf.compat.v1.Session()

#tf.compat.v1.keras.backend.get_session()
import keras
from imageai.Detection import ObjectDetection
import os

execution_path=os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()

detector.setModelPath( os.path.join(execution_path, "resnet50_coco_best_v2.0.1.h5" ))
detector.loadModel()

detections=detector.detectObjectsFromImage(input_image=os.path.join(execution_path,"2.jpg"),output_image_path=os.path.join(execution_path,"image2new.jpg"))

for eachObject in detections:
    print(eachObject["name"],":", eachObject["Percentage Probability"])**

My error is 

**ValueError: Ensure you specified correct input image, input type, output type and/or output image path** 


could you help me to find a way to tackle this.
thanks in advance

**Comment by asurafon** [comment]
> @OlafenwaMoses Good day ! ,
> 
> This is my Code snippet
> 
> **import imageai
> 
> import tensorflow as tf
> #tf.compat.v1.Session()
> 
> #tf.compat.v1.keras.backend.get_session()
> import keras
> from imageai.Detection import ObjectDetection
> import os
> 
> execution_path=os.getcwd()
> 
> detector = ObjectDetection()
> detector.setModelTypeAsRetinaNet()
> 
> detector.setModelPath( os.path.join(execution_path, "resnet50_coco_best_v2.0.1.h5" ))
> detector.loadModel()
> 
> detections=detector.detectObjectsFromImage(input_image=os.path.join(execution_path,"2.jpg"),output_image_path=os.path.join(execution_path,"image2new.jpg"))
> 
> for eachObject in detections:
> print(eachObject["name"],":", eachObject["Percentage Probability"])**
> 
> My error is
> 
> **ValueError: Ensure you specified correct input image, input type, output type and/or output image path**
> 
> could you help me to find a way to tackle this.
> thanks in advance

I hava the same problem with retinnet model!! Can you help us please!!!!

**Comment by JaccoVE** [comment]
I had the same issue and was able to fix by making sure everything runs on the CPU instead of the GPU. Add these lines at start of your Python file:

# Use CPU instead of GPU
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""

**Comment by pallocchi** [comment]
Same issue here 🙋🏻‍♂️and after debugging I've found the real error:
```
cannot write mode RGBA as JPEG
```
So, I changed `output_image_path=test.jpg` to  `output_image_path=test.png` and now it's working.

**Comment by ejgeo** [comment]
Setting image path to take multiple images and output the results

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""
from imageai.Detection import ObjectDetection

detector  = ObjectDetection()

model_path = "./models/yolo-tiny.h5"
input_path = "./input"
output_path = "./output"


detector.setModelTypeAsTinyYOLOv3()

detector.setModelPath(model_path)

detector.loadModel()

custom_objects = detector.CustomObjects(cow = True)
detection = detector.detectObjectsFromImage(input_image = input_path, input_type="array", output_image_path = output_path, output_type="array")

for eachItem in detection:
    print(eachItem["name"] , " : ", eachItem["percentage_probability"], ":", eachItem["box_points"])
    print("----------------")

**Comment by Thanossrs** [comment]
detections = detector.detectCustomObjectsFromImage(custom_objects=custom_objects, input_image=original,  output_image_path='imgnew.png',input_type="array",output_type="array", minimum_percentage_probability=40)
Traceback (most recent call last):

  File "C:\Users\Thanossrs\anaconda3\lib\site-packages\imageai\Detection\__init__.py", line 833, in detectCustomObjectsFromImage
    feed_dict={

  File "C:\Users\Thanossrs\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 726, in __hash__
    raise TypeError("Tensor is unhashable. "

TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-6-33147170a0fd>", line 1, in <module>
    detections = detector.detectCustomObjectsFromImage(custom_objects=custom_objects, input_image=original,  output_image_path='imgnew.png',input_type="array",output_type="array", minimum_percentage_probability=40)

  File "C:\Users\Thanossrs\anaconda3\lib\site-packages\imageai\Detection\__init__.py", line 918, in detectCustomObjectsFromImage
    raise ValueError(

ValueError: Ensure you specified correct input image, input type, output type and/or output image path

**Comment by Thanossrs** [comment]
could someone help me with the above errors?

**Comment by Zordiac** [comment]
Instead of ObjectDetection, use CustomObjectDetection:

`from imageai.Detection.Custom import CustomObjectDetection

detector = CustomObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath("hololens-ex-60--loss-2.76.h5")
detector.setJsonPath("detection_config.json")
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image="holo1.jpg", output_image_path="holo1-detected.jpg")
for detection in detections:
    print(detection["name"], " : ", detection["percentage_probability"], " : ", detection["box_points"])`

**Comment by luc18** [comment]
I also encountered this problem, but I finally found out that it was a compatibility problem with other languages.
Solved after modifying the path of the image:
For example: change the path : "D:/图片分割/Figure" to D:/file/Figure
