### ISSUE TITLE
offer a standard docker image?

### ISSUE THREAD

**Issue by williamfzc** [OlafenwaMoses/ImageAI#290]
nice project!

docker is a good way to handle environment issues, which provided a standard workspace. It can make imageai working normally in different systems.

any plan for it?

thanks to your project :)

**Comment by OlafenwaMoses** [comment]
A docker might be a good idea. There are a number of questions on what features should be supported.

- recognition?
- detection ?
- training of both ?
- GPU support?
- Jupyter Notebook interface?

Also, note that **ImaegAI** is provided for integration and embedding in new and existing applications.

**Comment by williamfzc** [comment]
thanks! much more complicated than what i thought at the beginning.
