### ISSUE TITLE
multiple object learning

### ISSUE THREAD

**Issue by christophe-duc** [OlafenwaMoses/ImageAI#292]
Hi,

  I am training a Custom.DetectionModelTrained and would like to be able to have it learned multiple new objects.

  I have multiple datasets each one with the required annotations for each object.

  I am able to train a model on each of those datasets. How can I combine all of those models into one as each one generate it's one detection_config.json file.

  If you have any pointers to a doc, I would greatly appreciate it.

Thanks.

**Comment by OlafenwaMoses** [comment]
You can train a single model to detect all the objects. All you need is to add all the images and annotations for all the objects in the train and validation folders respectively and specify their names in your **setTrainConfig()**  as in the example below. 

_object_names_array =["tree","window","door"]_

**Comment by christophe-duc** [comment]
Yeap sorry just figured it out now, was going to delete the issue when I saw your response.

But thanks!

**Comment by architlatkar27** [comment]
Hey, can you tell me the directory structure for multiple objects?

**Comment by ekesdf** [comment]
Just dump all your dataset in to one folder with the same structure as your current datasets

mainfolder
---train:
-----annotations:
-------1.xml
-----images:
-------1.jpg
---val:
-----annotaitons
--- same as train
