### ISSUE TITLE
ValueError: Empty training data.

### ISSUE THREAD

**Issue by 731323083** [OlafenwaMoses/ImageAI#294]
HI,

when I When I run my Python，I get the following error message:

Number of experiments (Epochs) :  1
1/2 [==============>...............] - ETA: 37s - loss: 1.1703 - acc: 0.5000Trac
eback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\AI\TrainAI.py", line 10, in <modu
le>
    trainer.trainModel(num_objects=2, num_experiments=1, enhance_data=False, bat
ch_size=8, show_network_summary=True) # Download the model via this link https:/
/github.com/OlafenwaMoses/ImageAI/releases/tag/models-v3
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\imageai\Prediction\Custom\__init__.py", line 322, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_sched
uler])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator

    steps_name='steps_per_epoch')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\tensorflow\python\keras\engine\training_generator.py", line 322, in mode
l_iteration
    steps_name='validation_steps')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\tensorflow\python\keras\engine\training_generator.py", line 300, in mode
l_iteration
    aggregator.finalize()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\tensorflow\python\keras\engine\training_utils.py", line 111, in finalize

    raise ValueError('Empty training data.')
ValueError: Empty training data.

My code is as follows；

from imageai.Prediction.Custom import ModelTraining
import os

trainer = ModelTraining()
trainer.setModelTypeAsResNet()
trainer.setDataDirectory("C:\\Users\\Administrator\\PycharmProjects\\AI\\data")
trainer.trainModel(num_objects=2, num_experiments=1, enhance_data=True, batch_size=32, show_network_summary=True)

thanks for your help！

**Comment by OlafenwaMoses** [comment]
How many images per object do you have in your train and test folders?

**Comment by 731323083** [comment]
> How many images per object do you have in your train and test folders?

I have 10 images in train->cat , 10 images in train->dog , 1 image in test->cat and 1 image in test->dog

W0817 23:15:57.445278  2892 callbacks.py:875] `period` argument is deprecated. P
lease use `save_freq` to specify the frequency in number of samples seen.
Using Enhanced Data Generation
Found 20 images belonging to 2 classes.
Found 2 images belonging to 2 classes.
JSON Mapping for the model classes saved to  C:\Users\Administrator\PycharmProje
cts\AI\data\json\model_class.json
Number of experiments (Epochs) :  1

**Comment by OlafenwaMoses** [comment]
- First, your batch size can't be less then the images in your test and train folders
- Secondly, you should have at least 300 for train and 100 for test per object to create a model with minimal viable accuracy.

**Comment by 731323083** [comment]
> * First, your batch size can't be more than the images in your test and train folders
> * Secondly, you should have at least 300 for train and 100 for test per object to create a model with minimal viable accuracy.

thanks for your help !
