### ISSUE TITLE
loadModel() got an unexpected keyword argument 'detection_speed'

### ISSUE THREAD

**Issue by radoncoder** [OlafenwaMoses/ImageAI#297]
Greetings -- love the work you have done on this project.  Have been trying everything out over the past couple of days.  Ran into an issue when I provided the "detection_speed" argument to loadModel.

I'm using the anaconda platform and installed ImageAI via pip (i.e. pip3 equivalent) as instructed on the page, version 2.1.3.  Code that reproduces the error is below:

import os
from imageai.Detection.Custom import DetectionModelTrainer
from imageai.Detection.Custom import CustomObjectDetection

base_path = base_path = os.path.normpath(r"E:\ai_training")

model = "detection_model-ex-20--loss-4.11.h5"
detector = CustomObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath(os.path.join(base_path,"models",model))
detector.setJsonPath(os.path.join(base_path,"json","detection_config.json"))
detector.loadModel(detection_speed="fast")

TypeError                                 Traceback (most recent call last)
<ipython-input-53-81fbe48ab599> in <module>
     11 detector.setModelPath(os.path.join(base_path,"models",model))
     12 detector.setJsonPath(os.path.join(base_path,"json","detection_config.json"))
---> 13 detector.loadModel(detection_speed="fast")
     14 

TypeError: loadModel() got an unexpected keyword argument 'detection_speed'

EDIT: I saw I had a slightly later version.  Rolled back to 2.1.0 and still had the error.

**Comment by OlafenwaMoses** [comment]
Please refer to #296
