### ISSUE TITLE
Where can I find the "resnet50_coco_best_v2.0.1.h5" file?

### ISSUE THREAD

**Issue by Elephantameler** [OlafenwaMoses/ImageAI#3]
Thank you for your sharing!
I have a little question about that.
At the example of object detection, I directly run and can't find the trained model. So where can I find them.

**Comment by OlafenwaMoses** [comment]
Just before the "FirstObjectDetection.py" example,  there is a link  "RetinaNet" to download the trained model. Also, all the trained models are available on the release page. 
You can also follow this link to all the trained models. 
https://github.com/OlafenwaMoses/ImageAI/releases/tag/1.0

**Comment by Savitha2018** [comment]
Available at
https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/resnet50_coco_best_v2.0.1.h5
