### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#301]
Hello.

Is it possible and how to predict images from multiple threads simultaneously?

**Comment by Gytis123** [comment]
Update.

Predict image from multiple threads simultaneously using same model?

**Comment by acleitao76** [comment]
Are you getting some error? I didn't try pure multithreaded yet but inside flash Keras pops a error. There is a way to fix it https://github.com/OlafenwaMoses/ImageAI/issues/289 this post has my inquire about the same. Do a google search(I really don't remember the site where I found the answer) on keras multithread and you will see the solution.. .but for this you gonna have to fix the problem at the library. I'm finishing a project and didn't have the time to do it yet

**Comment by OlafenwaMoses** [comment]
@Gytis123  Kindly refer to #289
