### ISSUE TITLE
'cavity is not in list'

### ISSUE THREAD

**Issue by plenari** [OlafenwaMoses/ImageAI#303]
when I use Detection.Custom.DetectionModelTrainer ,raise such errors.
hello,if there is  a docker images for us  to train?

**Comment by OlafenwaMoses** [comment]
- What type of model are you trying to train?
- What are the objects in the dataset?
- Can you share your training code?

**Comment by plenari** [comment]
Sorry, it's my fault.  I moved the  images after commenting. Great job !!!!

**Comment by Poonamjo** [comment]
Hello Plenari,

I am facing similar issue : 'Radiator_73' not in list.
Can you help with this?
What you did to resolve this?

**Comment by plenari** [comment]
maybe check .xml will help. Perhaps, labelimg make a worng tag.

**Comment by Poonamjo** [comment]
I corrected the name tag. Thank you its working now.
