### ISSUE TITLE
How to deal with "negative" images for training a custom detection model?

### ISSUE THREAD

**Issue by Meulen92** [OlafenwaMoses/ImageAI#307]
Hey Moses,

First of all, many thanks for your awesome work on ImageAI.

Right now I'm training this custom YOLOv3 object detection model, but I'm dealing with lots of false positives with the resulting model (1000 train images, 250 validation images, mAP: 0.9766).

Can I somehow incorporate training images that contain my false positive scenario, but without bounding boxes, like how they describe here: https://github.com/qqwweee/keras-yolo3/issues/294?

Thanks in advance.

Sincerely

**Comment by OlafenwaMoses** [comment]
Thanks for the compliments. I really appreciate your kind words. 

In dealing with false positives, there are many ways to it.
- Using the method described in the issue  qqwweee/keras-yolo3#294
- increase the `minimum_percentage_probability` in your **.detectObjectsFromImage** or **.detectObjectsFromVideo** function to higher values, e.g `50` and above. The default value is `30`.

**Comment by Meulen92** [comment]
Thank you! Will do.
Keep up the great work. :)
