### ISSUE TITLE
ValueError: 'Radiator_73' is not in list

### ISSUE THREAD

**Issue by Poonamjo** [OlafenwaMoses/ImageAI#308]
I am training the model with customdataset of Radiator.
While running the code I am getting the below error:

Generating anchor boxes for training images and annotation...
Average IOU for 9 anchors: 0.83
Anchor Boxes generated.
Detection configuration saved in  Radiator/json/detection_config.json
Training on: 	['Radiator']
Training with Batch Size:  4
Number of Experiments:  200
Training with transfer learning from pretrained Model
/usr/local/lib/python3.6/dist-packages/keras/callbacks.py:1335: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
Epoch 1/200
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-1b2eed1de58c> in <module>()
      7 # In the above,when training for detecting multiple objects,
      8 #set object_names_array=["object1", "object2", "object3",..."objectz"]
----> 9 trainer.trainModel()

10 frames
/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/generator.py in __getitem__(self, idx)
    110 
    111                 # determine the index of the label
--> 112                 obj_indx = self.labels.index(obj['name'])
    113 
    114                 # determine the location of the cell responsible for this object

ValueError: 'Radiator_73' is not in list

**Comment by OlafenwaMoses** [comment]
An information is missing in your dataset. It can be:
- a missing image
- a missing annotation file for an image
- didn't add object name to ` object_names_array` in your **setTrainConfig** function

**Comment by Poonamjo** [comment]
I used below code :
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="Radiator")
trainer.setTrainConfig(object_names_array=["Radiator"], batch_size=4, num_experiments=200, train_from_pretrained_model="pretrained-yolov3.h5")
# In the above,when training for detecting multiple objects,
#set object_names_array=["object1", "object2", "object3",..."objectz"]
trainer.trainModel()

Also, I checked the data all the images n annotations were present.
Each time when I run the code again, it shows same error but with different no. of image
For e.g.
ValueError: 'Radiator_160' is not in list
ValueError: 'Radiator_26' is not in list
ValueError: 'Radiator_59' is not in list  .. etc.

I am not sure where I am wrong.
I checked the annotations as well.
Is there any specific format for name of images?

**Comment by Poonamjo** [comment]
Please help with this.

**Comment by Poonamjo** [comment]
Do anything else has to be added?
I created the dataset for Radiator:
Radiator
- train
   - annotations
      -Radiator_1.xml
      -Radiator_2.xml
        ....Radiator_170.xml
   -images
      -Radiator_1.jpg
      -Radiator_2.jpg
        ....Radiator_170.jpg
- validation
   - annotations
      -Radiator_171.xml
      -Radiator_172.xml
        ....Radiator_170.xml
   -images
      -Radiator_171.jpg
      -Radiator_172.jpg
        ....Radiator_200.jpg
Downloaded the pretrained yolo model and ran the above code

**Comment by OlafenwaMoses** [comment]
Kindly visit #303 and review the last comments. You might get insights on resolving your issue from there.

**Comment by Poonamjo** [comment]
I changed the name tag and its working now.
Just one more thing I want to use resnet model instead of yolo.
would it be possible.
I tried using set model type as resnet () but it did not worked.

**Comment by OlafenwaMoses** [comment]
I am happy to know you have resolved this issue. ImageAI currently support only YOLOv3. Support for training with **RetinaNet** will be added in future versions.
