### ISSUE TITLE
Help needed - Google Cloud Platform

### ISSUE THREAD

**Issue by acleitao76** [OlafenwaMoses/ImageAI#312]
Is there any instance template that can run ImageAi training out of the box? I'm struggling to put an instance up and running because of dependencies .
Or maybe any tutorial on how to setup all dependencies to train on a gpu available machine?

**Comment by auphofBSF** [comment]
I have found this article worked well and is the basis for all my configurations
https://medium.com/google-cloud/using-google-cloud-ai-platform-notebooks-as-a-web-based-python-ide-e729e0dc6eed 

the Notebook code and article from @OlafenwaMoses  [Train Object Detection AI with 6 lines of code](https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff)
) works in the Jupyter Notebook on the GC-AI-Platform.

I created 2 VM instances - the 2nd without GPU and fewer cores less memory and disk is for validating code etc. (Much lower cost)

The VM's can also be connected to COLAB, work really well and a better UX than the JupyterLab Notebook.  Connect these VM instances by using gcloud ssh on local machine and ssh forwarding  the VM Juypyter to local sockets for Colab (Connect Local)

!!!!! DONT leave your instances especially GPU instances running unnecessarily - VERY EXPENSIVE

**Comment by acleitao76** [comment]
I never notice those AI platform notebooks. Just tried it... amazing... but taking no module named imageai even after !pip3 install imageai --update. Any ideas?

**Comment by acleitao76** [comment]
for those who got the same problem. go to Kernel -> Restart Kernel

**Comment by acleitao76** [comment]
@auphofBSF up and running buddy... thx a lot for your help...

**Comment by auphofBSF** [comment]
your welcome
