### ISSUE TITLE
Doesn't seem to identify images - even test data

### ISSUE THREAD

**Issue by expressIndustries** [OlafenwaMoses/ImageAI#315]
I've setup a Colab notebook and have the test (idenprof) data running.   As you'll see in the CoLab notebook I've shared - I've followed the demo provided.

The system trains (100 experiments) and makes a model.  When I feed the system images of firefighters, police, chefs or others - it never predicts properly.  

CoLab notebook:
https://colab.research.google.com/drive/109WHJ5IRMG9iO4DrRHkNiqzXd-ciZTTY

Here are the failures....these are VERY clear examples of each image class.

chef  :  54.75713014602661
URL = "https://i.imgur.com/bowui5h.jpg"   #firefighter

chef  :  54.5409619808197
URL = "https://i.imgur.com/c0nBBTc.jpg" #pilot

chef  :  54.324376583099365
URL = "https://i.ytimg.com/vi/JXGv9rscmro/hqdefault.jpg" #pilot

Can anyone tell me why this is not identifying with any accuracy?  Not even 5% accuracy at this point.

**Comment by OlafenwaMoses** [comment]
- What model type did you train?
- I need access to the notebook to review the code.

**Comment by OlafenwaMoses** [comment]
Kindly send the invitation to guymodscientist@gmail.com
