### ISSUE TITLE
Load detection_config.json from trained custom model to continue training on Colab

### ISSUE THREAD

**Issue by gitobsza** [OlafenwaMoses/ImageAI#317]
When doing the transfer learning of object detection. Can we load the generated detetion_config.json from previous trained model  to retrain the network?
Currently I'm training on google colab and I could only get 24-26 epoch with the 12hr time limit and I want to continue the training.

**Comment by OlafenwaMoses** [comment]
This isn't supported yet. However, it will be very good to provide the option to continue with the previously generated `detetion_config.json` file. 

The option will be added soon.

**Comment by gitobsza** [comment]
Thankyou
