### ISSUE TITLE
TPU Training

### ISSUE THREAD

**Issue by flozi00** [OlafenwaMoses/ImageAI#321]
Is it possible to add TPU support for training the custom modells ?

It should be easy using following code after model.compile function

`try:
    model = tf.contrib.tpu.keras_to_tpu_model(
        model,
        strategy=tf.contrib.tpu.TPUDistributionStrategy(
            tf.contrib.cluster_resolver.TPUClusterResolver('grpc://' + TPU_ADDRESS)))
except:
    pass`

from:
https://nbviewer.jupyter.org/github/cedrickchee/data-science-notebooks/blob/master/notebooks/tensorflow/google_cloud_tpu/guide_to_tensorflow_keras_on_tpu_mnist.ipynb

**Comment by OlafenwaMoses** [comment]
@flozi00  Thanks for sharing this useful information. However, I have concerns on backward compatibility with previous versions of **Tensorflow** and **Keras**. I haven't work with the TPU before.

**Comment by flozi00** [comment]
Maybe it would be a nice feature in one of the future versions

**Comment by kettenbach-it** [comment]
TPU support would be a killer feature!
Consider that training on TPUs is much faster and cheaper then training on GPUs

**Comment by OlafenwaMoses** [comment]
@kettenbach-it Thanks for the comment. We will consider support for this in our future updates.
