### ISSUE TITLE
VideoObjectDetection exports video in BGR instead of RGB in TinyYOLOv3

### ISSUE THREAD

**Issue by Vijayabhaskar96** [OlafenwaMoses/ImageAI#33]
This is a Tiny issue,most likely caused by opencv's default BGR format,should be able to fix by cv2.COLOR_BGR2RGB

**Comment by OlafenwaMoses** [comment]
Thank you very much @Vijayabhaskar96 for bringing my notice to this. It has been fixed and new wheel updated. To get this new version, just uninstall the current ImageAI you have and install it again from the URL provided in the repository's description.
