### ISSUE TITLE
How to ignore warnings 

### ISSUE THREAD

**Issue by He-haitao** [OlafenwaMoses/ImageAI#334]
warnings output makes me not comfortable, and how to ignore it in the api

**Comment by AbimbolaOO** [comment]
Hello He-haitao,

ImageAI doesn't currently support provide a way to suppress warnings. Hopefully, in a future version of ImageAI, there would be a way to suppress warnings.

**Comment by OlafenwaMoses** [comment]
@He-haitao You can use the solution provided here

https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings
