### ISSUE TITLE
GPU support for production ready system

### ISSUE THREAD

**Issue by sleebapaul** [OlafenwaMoses/ImageAI#34]
When you're planning to implement GPU acceleration for these models. Else at production, the performance will be hopeless.

**Comment by OlafenwaMoses** [comment]
I am pleased to inform you that all features supported by ImageAI automatically uses the NVIDIA GPU if available. All you need is to ensure you install the GPU version of Tensorflow. These instructions has been fully stated in the repository's README. I will advise you read it carefully. 

Besides, ImageAI has been used in many production and research work around the work by undergraduate students,  graduate students and experts in big corporations.

**Comment by sleebapaul** [comment]
Thanks, @OlafenwaMoses . I couldn't check it on the go. My bad.

**Comment by OlafenwaMoses** [comment]
It's okay. You are welcome.

**Comment by OlafenwaMoses** [comment]
Apart from the features contained in current version of ImageAI,  We are also planning to add more features soon such as Image Segmentation, Face/Gender/Age and Emotion detection, Scene classification and more. We will Also be bringing ImageAI to the Android, iOS and .NET developer platform too. 

We need all the support you and everyone else can provide to make all of these possible. Kindly visit the link below to know all about it and how to contribute to the project. 

https://igg.me/at/imageai/

**Comment by cagnulein** [comment]
@sleebapaul did you use GPU at the end in production? Which GPU card did you use? I would like to do the same for an alarm system, and i would like help my CPU (i7 7th generation 8 core) with a GPU.
