### ISSUE TITLE
Not able to train  DetectionModelTrainer in TinyYolo

### ISSUE THREAD

**Issue by ruvelrp** [OlafenwaMoses/ImageAI#340]
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsTinyYOLOv3()
trainer.setDataDirectory(data_directory="xyz_images")
trainer.setTrainConfig(object_names_array=["xyz"], batch_size=4, num_experiments=50,train_from_pretrained_model="yolo-tiny.h5")
trainer.trainModel()

I am getting exception 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-a9bcf143824c> in <module>()
      2 
      3 trainer = DetectionModelTrainer()
----> 4 trainer.setModelTypeAsTinyYOLOv3()
      5 trainer.setDataDirectory(data_directory="xyz_images")
      6 #trainer.setTrainConfig(object_names_array=["xyz"], batch_size=4, num_experiments=50)

AttributeError: 'DetectionModelTrainer' object has no attribute 'setModelTypeAsTinyYOLOv3'

Please look into it and please help me I am in need :/

**Comment by OlafenwaMoses** [comment]
Kindly note that for training custom detection models, only **YOLOv3** is supported for now.

**Comment by ruvelrp** [comment]
Can we expect TinyYolo Training anytime soon?

**Comment by OlafenwaMoses** [comment]
We can't promise that yet. Timeline for implementation has not been decided.

**Comment by rola93** [comment]
shouldn't this be closed?

**Comment by OlafenwaMoses** [comment]
Thanks @rola93

**Comment by joshberry** [comment]
@OlafenwaMoses @rola93 Should this issue have really been closed? I see that tiny yolo has been implemented for the detector, but I don't see any indication in the source code that it's been implemented for the training, which is what @ruvelrp reported.

I too unable to figure out how to train a custom model using tiny yolo. If it's there an I'm missing it, can you please point me to an example or section of the source code where it's implemented. 

Thanks! ❤️ the project so far...

**Comment by rola93** [comment]
As far as I understand, the issue is solved: the model can't be loaded because it's not implemented

**Comment by nguyenanhtuan1008** [comment]
I have same issue like this. Does anyone implement for Yolo v3 Tiny model?

**Comment by Wheest** [comment]
I have an [open pull request](https://github.com/OlafenwaMoses/ImageAI/pull/613) which tries to implement this.  I've got most of the way, but have a couple of bugs I haven't been able to bash yet.  Thoughts or comments appreciated.
