### ISSUE TITLE
difference between the different speed modes like "flash", "faster", "fast" etc. 

### ISSUE THREAD

**Issue by Rakeshchandrajoshi** [OlafenwaMoses/ImageAI#346]
Can you clarify me that what is the difference between the different speed modes like "flash", "faster", "fast" etc. in technical terms. What is the process that changed when we switch from one mode to other. Does it affect accuracy?

**Comment by OlafenwaMoses** [comment]
Find answers to your question below
- Each speed modes processes the image at different resolution
- The faster modes operates at lower resolutions
- In the faster modes, accuracy becomes lower due to the decrease in image resolution
