### ISSUE TITLE
It doesn't start training

### ISSUE THREAD

**Issue by hasslercastro** [OlafenwaMoses/ImageAI#356]
Thank you for your great effort! 

Yolo doesn't start training
I get the following message: 

Using TensorFlow backend.
Generating anchor boxes for training images and annotation...
/home/h/yolo_v3/yolov3-tf2/enviroment/yolito/lib/python3.7/site-packages/imageai/Detection/Custom/gen_anchors.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  similarity = w*h/(c_w*c_h)

Theses folders are created (cache, json, logs, models)  but it doesn't seem to start training after the message below appears, @OlafenwaMoses  should I wait more, is it something related to my tensorflow version?

tf_version -> 1.13
keras -> 2.3.0 

(I've also tried with other versions  (tf 2.0 , tf 1.5) )

**Comment by rola93** [comment]
It may have started, but it can some time before it gives you any output.

Check that ImageAI is in its last version

Are you using a GPU?

**Comment by hasslercastro** [comment]
Thank you @rola93 
This was the problem : RuntimeWarning: divide by zero encountered in double_scalars
similarity = wh/(c_wc_h)
It was due to the way I was generating the VOC files, even thouhgt neither the width nor the height were 0 , the values weren't not correct, I fixed that , and now i'm training hoping to get good results 
closing this issue.
