### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by acleitao76** [OlafenwaMoses/ImageAI#360]
Hey guys I'm back. First I want to say a huge thank you to the person who implemented thread_safe parameter!!! Well done!!!!! I owe you a beer. (just went to the pull requests to get your name thanks @witoong623 )

Ok I was able to retrain my model from scratch and its working amazingly. Now I'm developing the real code.  This is how I'm calling the detection:
`    returned_image, detections, images_detected = detector.detectObjectsFromImage(input_image=strfilepath,
                                                                                  output_type="array",
                                                                                  extract_detected_objects=True,
                                                                                  minimum_percentage_probability=20,
                                                                                  thread_safe=True)`

and I'm getting _**'NoneType' object has no attribute 'copy'**_  problem seems to be at line 762 in the __init__.py file 

`image_frame = image.copy()`

The comments on that method states that if I send Output_type = Array and extract_detected_objects  = True I should get the original image, a array with the detections and a array with the extracted images but for some reason I can't pass this line. Is this a bug? Or am I using it wrong?

Big thx to @rola93 and @OlafenwaMoses for the help training and fixing my model

**Comment by rola93** [comment]
I guess your path `strfilepath` is wrong.  Try to validate if it is ok. My guess is that the path is wrong, therefore the image is not read, and it results in `image_frame` being None.

In addition to this, it would be better if you provide the stack trace

**Comment by acleitao76** [comment]
I just found out the problem. Just so people know if they get the same problem. I'm using WatchDog for monitoring changes in a directory. Watchdog fire the eventhandler even before the copy of the file is finished. So it's the right path but the file isn't there yet.

**Comment by rola93** [comment]
Great news! thanks for sharing it

can you close thread?

Thanks!
