### ISSUE TITLE
How can I open camera window with object detection model and detect realtime?

### ISSUE THREAD

**Issue by ulgacemre** [OlafenwaMoses/ImageAI#361]

**Comment by OlafenwaMoses** [comment]
If you want to run detection and display results in real-time, you will need to run on a computer system with **NVIDIA GPU**. I will recommend **GTX 1070** or higher

**Comment by DeveloperRachit** [comment]
![Screenshot from 2019-11-12 11-58-05](https://user-images.githubusercontent.com/35888852/68647370-be303700-0543-11ea-9477-ead5e9ee10c0.png)

**Comment by DeveloperRachit** [comment]
that Specifications i have in my GPU but training is too slow i am using 4 batch size

**Comment by OlafenwaMoses** [comment]
@DeveloperRachit Please note the difference between training and detecting in real time. The amount of time it takes to train depends on your dataset size.

**Comment by codebugged** [comment]
Hi @OlafenwaMoses  
Can you please share the code for detecting and showing it in live feed
