### ISSUE TITLE
ValueError: You are trying to load a weight file containing 45 layers into a model with 147 layers.

### ISSUE THREAD

**Issue by matheusdasilveiramello22** [OlafenwaMoses/ImageAI#362]
I'm new to this area of artificial intelligence and computer vision and I'm trying to understand, I'm having this error:

This is my code:
```
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
```

I am using the last ImageAI version.
Python 3.7.4
TensorFlow 1.14.0

![image](https://user-images.githubusercontent.com/15657692/65623190-a0ac0b80-df9d-11e9-9a02-571e88c9f420.png)

Is it possible to solve this ? How can i solve this ? I need this .h5 file to set my model, is it possible to train with this file ? 

Sorry for asking seemingly dumb questions

**Comment by OlafenwaMoses** [comment]
Please visit and study the tutorials linked below

https://towardsdatascience.com/object-detection-with-10-lines-of-code-d6cb4d86f606

https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff

**Comment by matheusdasilveiramello22** [comment]
I ll try solve with your articles and if I fail I'll reply here, thanks Olaf :-)

**Comment by matheusdasilveiramello22** [comment]
I follow your tutorial and works.
Is it possible transform YOLOv3 data

**Comment by zhangby2085** [comment]
Check the model you downloaded yolo.h5, try to do it again.

**Comment by abhisheknagarajan** [comment]
yolo = Detection.ObjectDetection()
yolo.setModelTypeAsYOLOv3()
yolo.setModelPath(modelpath)
yolo.loadModel()

I am trying to load my custom build model (classification_weight.hdf5) and I am getting the following error. In fact I don't want to use Pretrained model in this problem:

Error:

ValueError                                Traceback (most recent call last)
<ipython-input-25-a6e774c8c064> in <module>
      2 yolo.setModelTypeAsYOLOv3()
      3 yolo.setModelPath(modelpath)
----> 4 yolo.loadModel()

~\Anaconda3\lib\site-packages\imageai\Detection\__init__.py in loadModel(self, detection_speed)
    193                                  len(self.numbers_to_names.keys()))
    194 
--> 195                 model.load_weights(self.modelPath)
    196 
    197                 self.__model_collection.append(model)

~\Anaconda3\lib\site-packages\keras\engine\training.py in load_weights(self, filepath, by_name, skip_mismatch, options)

~\Anaconda3\lib\site-packages\keras\saving\hdf5_format.py in load_weights_from_hdf5_group(f, layers)
    686   layer_names = filtered_layer_names
    687   if len(layer_names) != len(filtered_layers):
--> 688     raise ValueError('You are trying to load a weight file '
    689                      'containing ' + str(len(layer_names)) +
    690                      ' layers into a model with ' + str(len(filtered_layers)) +

ValueError: You are trying to load a weight file containing 7 layers into a model with 147 layers.
