### ISSUE TITLE
Getting a frame without bounding boxes, labels and probabilities

### ISSUE THREAD

**Issue by jvidyad** [OlafenwaMoses/ImageAI#364]
Hello,
    When I set return_detected_frame=True, the returned frame has the bounding boxes, the associated labels and probabilities. Is there any way to get the image for the frame without these?

**Comment by OlafenwaMoses** [comment]
You can set `display_percentage_probability=False and `display_object_name=False` in the **detection** function to hide the label and probability. 

Support for hiding the bounding box will be added soon.

**Comment by jvidyad** [comment]
OK. Thanks for the info. I tried displaying the returned frame using matplotlib.pyplot.imshow, but the quality of the displayed picture was worse than the quality of the original video. Why is that?? Is there any way  the quality of the returned frame can be improved?

**Comment by jvidyad** [comment]
Hello,
   Can someone please help me here?

**Comment by jvidyad** [comment]
Hello,
   Can someone please help me here?
