### ISSUE TITLE
 cannot import name 'VideoObjectDetection'

### ISSUE THREAD

**Issue by germanolira** [OlafenwaMoses/ImageAI#365]
from imageai.Detection import VideoObjectDetection
ImportError: cannot import name 'VideoObjectDetection' from 'imageai.Detection' (C:\Users\******************\imageai\Detection\__init__.py)

Why?

**Comment by rola93** [comment]
which version are you running? I have just tested it and it works ok, I'm running the last version, imageai-2.1.5
