### ISSUE TITLE
Non-maximal suppression in ImageAI

### ISSUE THREAD

**Issue by jvidyad** [OlafenwaMoses/ImageAI#368]
Hello,
   Does ImageAI do non-maximal suppression to get rid of multiple bounding boxes for an object??

**Comment by rola93** [comment]
yep, it is implemented [here](https://github.com/OlafenwaMoses/ImageAI/blob/c97df915d9fc2bf6fc1deee5a02ec9d9a1ca8ceb/imageai/Detection/Custom/__init__.py#L1308)

**Comment by PankajSShepHertz** [comment]
How to apply Non-maximal suppression, when using the detectCustomObjectsFromImage
