### ISSUE TITLE
Which is the simple way to use intel-tensorflow instead of tensorflow

### ISSUE THREAD

**Issue by cagnulein** [OlafenwaMoses/ImageAI#370]
Hi, i've got several intel system and i would like to use ImageAI on them.
Tensorflow python package doesn't use the embedded GPU so i would like to try ImageAI with intel-tensorflow python package.

Does anyone has some tips in order to achieve the result?
Thanks

**Comment by cagnulein** [comment]
mmm probably is just necessary to install intel-tensorflow instead of tensorflow

**Comment by rola93** [comment]
I didn't know of its existence. Can you share your results on this?

**Comment by cagnulein** [comment]
i will do, but i missunderstood the meaning of the intel-tensorflow package: it isn't for intel-egpu but only for activating a particular feature for intel's cpu.

**Comment by OlafenwaMoses** [comment]
**ImageAI** automatically uses your **GPU** as far as you have the **GPU** version of Tensorflow installed on your machine.
