### ISSUE TITLE
General Information

### ISSUE THREAD

**Issue by cyb3rclon3** [OlafenwaMoses/ImageAI#375]
Hi, I am using Yolov3 model to train my dataset. I was wondering if you help me explain what does the output actually says. 
1) How are bounding box location estimated? Is there any formula or code that I am missing or more precisely how is percentage_probability calculated?
2) What is the meaning of the number over bounding box in detected image? Is it IoU? 

Please help

**Comment by OlafenwaMoses** [comment]
- The `percentage probability` of an object is the confidence score that the object is what it is classified to be. Objects with confidence less than the **mininum_percentage_probability** will be ignored
- The `IoU` is a value used during **training/evaluation** to determine the proximity of the generated bounding box values and the ground truth. 
- The score displayed on a detected image is the object's class confidence score.

**Comment by dsdeeptisharma** [comment]
Hi, I just have a question. Will this ImageAI recognizes food images too? Can it  tell that its a banana or orange after seeing the image

**Comment by OlafenwaMoses** [comment]
You have to 
- collect images the food classes you want to recognize (recommended 300 or above per class)
- train a model recognition/detection model using **ImageAI**
**Recognition:** https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMTRAINING.md

**Detection:** https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTIONTRAINING.md

- apply the model on new images using **ImageAI**
