### ISSUE TITLE
Hello, can I use the custom trained model  as a pre-trained model for training again?

### ISSUE THREAD

**Issue by c7jie** [OlafenwaMoses/ImageAI#384]
I have many kinds of data. I don't want to train by once, because it will take a lot of time and I need to keep collecting data.

**Comment by OlafenwaMoses** [comment]
@c7jie  Yes you can.

**Comment by rola93** [comment]
This is the second time i read about this same topic. Maybe should add this _feature_on docs to avoid future questions.

Should close this issue since it was answered.

Thanks for your answer @OlafenwaMoses !

**Comment by OlafenwaMoses** [comment]
Alright @rola93 . Will make updates soon. Thanks to you too.

**Comment by c7jie** [comment]
> @c7jie Yes you can.
Thanks
