### ISSUE TITLE
Can I use Custom Detection Model Training to identify images in the following TIF format without converting to JPG images?

### ISSUE THREAD

**Issue by HaoNiu1997** [OlafenwaMoses/ImageAI#392]
Sir,I want to train some grayscale pictures taken by electron microscopy. The pictures are as follows. The left and right images are a picture. The left side is opened with special software, and the picture on the right is directly displayed. Is the program reading the right picture when it is being trained? Can I accurately identify the image I want to recognize when I make a prediction? Can I identify when there are multiple categories on one image?
![图片](https://user-images.githubusercontent.com/57083238/67776217-fee77500-fa9a-11e9-969b-9f9104cc0a67.png)

**Comment by AbimbolaOO** [comment]
No, you can't do so. Firstly, you need to understand that TIF is a very high-resolution image format used for print at the press. Most computer vision algorithm work with JPEG and PNG because they don't need to metadata store by TIF format.
