### ISSUE TITLE
Multiple detection box for single object

### ISSUE THREAD

**Issue by mahmoodtareq** [OlafenwaMoses/ImageAI#4]
First let me say amazing work. Unfortunately in my pc and [colab](https://colab.research.google.com), it outputs image like below.
![imagenew](https://user-images.githubusercontent.com/28574399/41509248-cfeea5e0-7272-11e8-9eed-b3c8672ee8a8.jpg)
Pretty much every object has more than one boxes. I copy pasted the code from [your gist](https://gist.github.com/OlafenwaMoses/38e68a0f3bcb7350785b67d2e6bc06ce). Also downloaded model [from here](https://github.com/OlafenwaMoses/ImageAI/releases/tag/1.0).

**Comment by OlafenwaMoses** [comment]
Hello,
I have worked on this error and performed object detection on the exact image. The result remains okay as you can see below. Perform the detection operation on other images and let me know if the bug shows up in any.
![imagereport](https://user-images.githubusercontent.com/5909998/41598576-7176126c-73c8-11e8-865e-976c74feeba6.jpg)

**Comment by OlafenwaMoses** [comment]
Also, ensure you haven't altered the inner implementations of the ImageAI installation you have on your system. Should you think this happened in anyway, uninstall ImageAI and re-install it.

**Comment by mahmoodtareq** [comment]
Re-installed and it is working now. I have tested with some other images. Thanks.

**Comment by OlafenwaMoses** [comment]
You are welcome.
