### ISSUE TITLE
ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via: ``` from keras.utils import to_categorical y_binary = to_categorical(y_int) ```

### ISSUE THREAD

**Issue by tang6237422** [OlafenwaMoses/ImageAI#40]
Dear author:
   I am training model, but error
Code:
    from imageai.Prediction.Custom import ModelTraining
    model_trainer = ModelTraining()
    model_trainer.setModelTypeAsResNet()
    model_trainer.setDataDirectory("/media/bdre/cloud/pets")
    model_trainer.trainModel(num_objects=1, num_experiments=100, enhance_data=True, batch_size=32, 
        show_network_summary=True)
Error:
Traceback (most recent call last):
  File "/home/bdre/pyPorject/com/bdre/safehat/train_molde.py", line 6, in <module>
    model_trainer.trainModel(num_objects=1, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True)
  File "/home/bdre/.local/lib/python3.6/site-packages/imageai/Prediction/Custom/__init__.py", line 249, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "/home/bdre/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1761, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/bdre/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 190, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/bdre/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1525, in train_on_batch
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/bdre/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 925, in _standardize_user_data
    y, self._feed_loss_fns, feed_output_shapes)
  File "/home/bdre/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 322, in check_loss_and_target_compatibility
    y.shape) + ' while using as loss `categorical_crossentropy`. '
ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
```
from keras.utils import to_categorical
y_binary = to_categorical(y_int)
```

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.

Please help me.

**Comment by tang6237422** [comment]
can not train one object.

**Comment by tang6237422** [comment]
can not train one object.

**Comment by allanis79** [comment]
I am getting the same error, can I know how you solved it?

**Comment by OlafenwaMoses** [comment]
> I am getting the same error, can I know how you solved it?

You must have at least 2 different types of object you need the object to recognize.

**Comment by allanis79** [comment]
thanks for your quick reply. 
![0](https://user-images.githubusercontent.com/15155403/50368262-a3279380-053b-11e9-953d-f047ab2e829b.jpg)

see the above image? I want to detect the phone in that image. So I have only one label. Any ideas on how to approach the above problem?

**Comment by tomaszhajduk** [comment]
Hi,

@allanis79. I'd suggest you to add a second category e.g. no-phone. (you'll have two categories: phone and no-phone)
You need to show to classifier how photo with phone looks like and how photo without phone looks like.
If you'll have just one label then classifier will assign all photos to this label.

Hopefully it helps you.

Best regards,
Tomek

**Comment by allanis79** [comment]
thanks, I solved it. :)

**Comment by ilirosmanaj** [comment]
@allanis79 , I guess you created the `no-phone` class, right? If that is the case, how many images did you need for this class - and, if applicable - did you do any comparison on the effect of the number of images for this class?

**Comment by allanis79** [comment]
yes I did create a no phone class. I made around 700 images. I didn't compare it with anything else.

**Comment by TheARKitectsEND** [comment]
I know that this is old and may not be watched, but quick question. If I am doing something similar, basically it is or isn't there, do I need provide consistent images for the 'not there' option or can I provide random images? For the testing does it need to be anything consistent for the 'not there' option?

**Comment by ilirosmanaj** [comment]
I think the more images you provide for the `not-there` class, the better it is. In your case I think it totally makes sense for them to be random and include as much different domains as possible

**Comment by FabianoLothor** [comment]
So, I was getting the same issue here and I fixed changing the expected output type.

I was expecting an integer, after parse the integer to a plain-string, the error was gone.
