### ISSUE TITLE
Question about Transfer Learning part

### ISSUE THREAD

**Issue by ElecRex** [OlafenwaMoses/ImageAI#407]
Can you explain to me the specific implementation process and principles of tranfer learning from pre-trained model in your framework?
Thx！

**Comment by AbimbolaOO** [comment]
ImageAI makes use of the full layers of already trained SOTA models on imageNet. It only modified the classification layer or the final layer so it can work with any number of classes you want to train it on. All the SOTA architecture it uses is listed in ImageAI docs.
