### ISSUE TITLE
GPU training utilization is too high

### ISSUE THREAD

**Issue by DeveloperRachit** [OlafenwaMoses/ImageAI#408]
when i am going to train my model as a custom it's utilization is too high and taking 2 and 3 days to train a single categories why is it happening?

**Comment by OlafenwaMoses** [comment]
What is the size of your training dataset?

**Comment by DeveloperRachit** [comment]
size of your training dataset 71 GB

**Comment by OlafenwaMoses** [comment]
How many images are in the train and test folder?

**Comment by DeveloperRachit** [comment]
5000 inside train and test

**Comment by DeveloperRachit** [comment]
may be less inside test folder

**Comment by OlafenwaMoses** [comment]
Alright. You said it takes 2-3 days to train a single category. Kindly clarify the following.

- how long does each epoch(experiment) takes?
- how many epochs (experiment) did you run?
- Did you run all the epochs in the 2-3 days?

**Comment by DeveloperRachit** [comment]
how long does each epoch(experiment) takes?
i did 5 epoch
how many epochs (experiment) did you run?
all
Did you run all the epochs in the 2-3 days
yes
but its taking too much time 

i started training before yesterday but still 1 epoch is not completed why is it taking too much time even taking 90to 80 % GPU also

**Comment by OlafenwaMoses** [comment]
Considering the number of images you are using for the training, the time it takes to train will depend on your **batch_size** which will also be determined by your **GPU** capacity.

Also, due to the type of model you are training, the processes is built to utilize the GPU as much as it can. 

If you desire faster training time, I will advice you use a more powerful GPU or cloud instances offering multi-GPU instances.

**Comment by DeveloperRachit** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  On   | 00000000:01:00.0 Off |                  N/A |
| 55%   72C    P0    N/A /  75W |   3956MiB /  4040MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      7290      C   python3                                     3945MiB |
+-----------------------------------------------------------------------------+

**Comment by DeveloperRachit** [comment]
this is my GPU configuration is it better or not to do training fastly?

**Comment by OlafenwaMoses** [comment]
I can observe your **GPU** is an **NVIDIA GTX 1050**. This is a considerably low capacity for training object detection models with a few thousands image dataset. 

One of our model training for object detection on **6000** images takes about **4 hours** per epoch on Google Colab, despite the use of Colab's **NVIDIA P100** instance. I will advice you

- use Google Colab
- Mount your drive to the Notebook
- Use your last models for previous training as the pre-trained model to continue in subsequent training.
