### ISSUE TITLE
object detection in satellite imagery

### ISSUE THREAD

**Issue by jaigsingla** [OlafenwaMoses/ImageAI#41]
I tried to ingest 1 m satellite imagery for object identification in model. Model is unable to detect any object in this. I guess improved imageAI may support satellite imagery and video analysis ?

**Comment by OlafenwaMoses** [comment]
The object detection supported in ImageAI requires a ground level point-of-view observation of the objects. We will consider supporting detection of objects in satellite images in future versions of ImageAI.
