### ISSUE TITLE
How to detect on a live video without saving it ??

### ISSUE THREAD

**Issue by shivam9804** [OlafenwaMoses/ImageAI#411]
I don want the video to be saved as I want to detect on a live is it possible ? and as I was trying to do it the video screen wouldnt open I using opencv to camera access.

**Comment by hwillard98** [comment]
I believe this is what you're looking for:
`video = detector.detectCustomObjectsFromVideo(camera_input=camera, save_detected_video=False)`

**Comment by dalisoft** [comment]
@hwillard98 
`save_detected_video=False` option does not work.
I am tried this option
```python
detector.setModelPath(os.path.join(execution_path, "yolo.h5"))
detector.loadModel(detection_speed="flash")
video_data = detector.detectObjectsFromVideo(
    camera_input=camera,
    save_detected_video=False,
    frames_per_second=10,
    log_progress=True,
    minimum_percentage_probability=50,
    # return_detected_frame=False,
)
```

This anyway saves file as `.avi` file into folder.

**Comment by codebugged** [comment]
Hi @shivam9804  
Did it work ? 

I am trying your code snippet but am not able to get live detected feed.
What's number:  +918004006979
