### ISSUE TITLE
No object tracking functionality! 

### ISSUE THREAD

**Issue by ChunfeiMa** [OlafenwaMoses/ImageAI#42]
You said you provide the Video Custom Object Detection (Object Tracking) function, but after checking the code, I could not find any code related to object tracking. Am I wrong?

**Comment by OlafenwaMoses** [comment]
Thank you for the comment. In this context, the custom Object Detection allows you detect only one or selected objects in the video. ImageAI also allows you to retrieve bounding box (box_point)  coordinates of the objects as well. This generated information can be further processes to track objects in the video using other algorithms.

**Comment by OlafenwaMoses** [comment]
We will consider implementing Kalman filter in future versions of ImageAI and provide abstract APIs to access it.

**Comment by ChunfeiMa** [comment]
@OlafenwaMoses  Thanks for your reply. Hope more advanced MOT tracking algorithms can be incorporated in the future.
