### ISSUE TITLE
ImageAI returns weird predictions

### ISSUE THREAD

**Issue by Snickbrack** [OlafenwaMoses/ImageAI#421]
I have done a CustomModelTraining with three categories: "face", "feet" and "hand"

I am using the Car/Tesla-Image from the Prediction-Excample: [Image](https://github.com/OlafenwaMoses/ImageAI/raw/master/data-images/1.jpg)

I am now running a CustomPrediction based on the three categories above and ImageAI returns that this Image is:
88.71890306472778% sure that the image is a feet
10.474355518817902% sure that this image is a face
0.8067470043897629% sure that this image is a hand

But it isn't anything of these three categories. Why doesn't it return lower percentage values for the categories I have provided?

Is ImageAI forced to always return minimum one high percentage value or is it because of low "quality" images for the training and tho ImageAI has not enough or not the right data to do a real prediction?

I am a little bit lost...

**Comment by AbimbolaOO** [comment]
To understand why imageAI as returned a high score for feet despite the image doesn't belong to any of the required classes. You need to understand how classification is done, typically classification is done by computing probability of class scores and these scores need to add up to one. So, in this case, the model thinks the image you testing with has a high probability of being a feet that is why you got a very high score for feet despite the image wasn't that of feet.
