### ISSUE TITLE
Will prediction or detection run on JETSON AGX XAVIER MODULE

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#425]
Hello

Will Image prediction or detection training work on https://www.nvidia.com/en-us/autonomous-machines/jetson-store/ JETSON AGX XAVIER MODULE with tensor cores? is it compatible?

**Comment by AbimbolaOO** [comment]
Hello @Gytis123,

Yes, it will work with JETSON AGX XAVIER MODULE all you need to do is to load the model to the device. Note ImageAI is a power library with was built on TensorFlow and Keras and Nvidea JETSON AGX XAVIER MODULE currently support this frameworks so everything would be fine.
