### ISSUE TITLE
Transfer learning on tiny-yolo version

### ISSUE THREAD

**Issue by Rakeshchandrajoshi** [OlafenwaMoses/ImageAI#428]
Hello Sir
Can we train the custom dataset on tiny-yolo with the help of YOLO? If yes, then how?
or is there any method with the help of that I can convert the YOLO-V3 model into the tiny-yolov3 model?

**Comment by AbimbolaOO** [comment]
No, you can't do that. I think what you might do is transfer learning and for transfer learning, you can only train a new model by using the weight of an already train model (Pre-trained Model).  That is the new model you would be training would be trained on the architecture as the pre-trained model.
