### ISSUE TITLE
CustomPrediction Exception

### ISSUE THREAD

**Issue by Airyzf** [OlafenwaMoses/ImageAI#43]
I run the FirstCustomPrediction.py code , and get the exception . The model file path and json file path is correct

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 385, in loadModel
    model = ResNet50(model_path=self.modelPath, weights="trained", model_input=image_input, num_classes=self.numObjects)
  File "C:\Users\admin\Anaconda3\lib\site-packages\imageai\Prediction\ResNet\resnet50.py", line 111, in ResNet50
    model.load_weights(weights_path)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\topology.py", line 1101, in load_weights
    f = h5py.File(filepath, mode='r')
  File "C:\Users\admin\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\admin\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (Truncated file: eof = 78022201, sblock->base_addr = 0, stored_eof = 94851792)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/tensorflow/pyimages/day2-object-detect/train_test/test.py", line 14, in <module>
    prediction.loadModel(num_objects=10)
  File "C:\Users\admin\Anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 389, in loadModel
    raise ValueError("You have specified an incorrect path to the ResNet model file.")
ValueError: You have specified an incorrect path to the ResNet model file.

**Comment by OlafenwaMoses** [comment]
Please paste the code you are running in the comment below for me to review .

**Comment by Airyzf** [comment]
`from imageai.Prediction.Custom import CustomImagePrediction
import os
execution_path = os.getcwd()


prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath(os.path.join(execution_path, "resnet_model_ex-020_acc-0.651714.h5"))
prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
prediction.loadModel(num_objects=10)

predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "4.jpg"), result_count=5)

for eachPrediction, eachProbability in zip(predictions, probabilities):
    print(eachPrediction + " : " + eachProbability)`

**Comment by OlafenwaMoses** [comment]
The code you are using is not fully compatible with the latest version of ImageAI. The README you read was not properly updated ( will fix that ASAP). 

I will encourage you to follow the newly created Official Documentation of ImageAI , via the link below. 

http://imageai.readthedocs.io/en/latest/custom/index.html

**Comment by OlafenwaMoses** [comment]
Please note that when printing results, use "," instead of "+"

**Comment by OlafenwaMoses** [comment]
You can also find this tutorial helpful 

https://towardsdatascience.com/train-image-recognition-ai-with-5-lines-of-code-8ed0bdd8d9ba

**Comment by Airyzf** [comment]
Thanks for you advice , it works when i use idenprof_061-0.7933.h5 model file.

**Comment by OlafenwaMoses** [comment]
You are welcome.

**Comment by Manny5Parkinson** [comment]
Hello,
I am facing the same problem except I am using my own custom trained model with it's associated json file.

**This is the code,**
from imageai.Prediction.Custom import CustomImagePrediction
import os
execution_path = os.getcwd()


prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath(os.path.join(execution_path, "vigil.h5"))
prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
prediction.loadModel(num_objects=10)


predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "896.png"), result_count=5)


for eachPrediction, eachProbability in zip(predictions, probabilities):
    print(eachPrediction , " : " , eachProbability)

Please suggest a solution

**Comment by Airyzf** [comment]
> Hello,
> I am facing the same problem except I am using my own custom trained model with it's associated json file.
> 
> **This is the code,**
> from imageai.Prediction.Custom import CustomImagePrediction
> import os
> execution_path = os.getcwd()
> 
> prediction = CustomImagePrediction()
> prediction.setModelTypeAsResNet()
> prediction.setModelPath(os.path.join(execution_path, "vigil.h5"))
> prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
> prediction.loadModel(num_objects=10)
> 
> predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "896.png"), result_count=5)
> 
> for eachPrediction, eachProbability in zip(predictions, probabilities):
> print(eachPrediction , " : " , eachProbability)
> 
> Please suggest a solution

try this model "idenprof_061-0.7933.h5"

**Comment by randomarchive101** [comment]
Hello, i randomly started to face the same issue with a program that worked fine ~6 months ago.

```
from imageai.Prediction.Custom import CustomImagePrediction    
execution_path = os.getcwd()
prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath(os.path.join(execution_path, "model_ex-166_acc-0.994712.h5"))
prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
prediction.loadModel(num_objects=10)
```
The model is there, the type is resnet, and the num_objects is correct. i tried to omit the full execution path and just pass the names of the files as is shown in documentation, but result is the same. 
Please help.

**Comment by randomarchive101** [comment]
I also tried the model and code from https://github.com/OlafenwaMoses/ImageAI/blob/e4e8430250b1a236fb0730e5af4f1d1c50bf803d/imageai/Prediction/CUSTOMPREDICTION.md, with same results.

**Comment by randomarchive101** [comment]
created a new virtual env and freshy installed everything, and the problem seems to be resolved. Still would like to know what happened though.

**Comment by randomarchive101** [comment]
okay, there is something really weird going on - i just encountered the same exact issue on a completely different machine that even has a different os. just like previously, it worked fine ~6 months ago. i installed imageai ~8 months ago, and the version on both machines is the newest one. Im really lost

**Comment by Airyzf** [comment]
> I also tried the model and code from https://github.com/OlafenwaMoses/ImageAI/blob/e4e8430250b1a236fb0730e5af4f1d1c50bf803d/imageai/Prediction/CUSTOMPREDICTION.md, with same results.

I install the newest version and run the demo codes without any errors. I did't train the model with my own data.

**Comment by Manny5Parkinson** [comment]
> > Hello,
> > I am facing the same problem except I am using my own custom trained model with it's associated json file.
> > **This is the code,**
> > from imageai.Prediction.Custom import CustomImagePrediction
> > import os
> > execution_path = os.getcwd()
> > prediction = CustomImagePrediction()
> > prediction.setModelTypeAsResNet()
> > prediction.setModelPath(os.path.join(execution_path, "vigil.h5"))
> > prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
> > prediction.loadModel(num_objects=10)
> > predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "896.png"), result_count=5)
> > for eachPrediction, eachProbability in zip(predictions, probabilities):
> > print(eachPrediction , " : " , eachProbability)
> > Please suggest a solution
> 
> try this model "idenprof_061-0.7933.h5"

Hey, it worked for me. Turns out if you rename your model file(h5) it won't work. Thanks a ton!!!!!.
I have another query can we use this resnet model for live video object detection? If let's say I use YOLO for object detection then use the ResNet model for classification. Can this happen?

**Comment by Airyzf** [comment]
> > > Hello,
> > > I am facing the same problem except I am using my own custom trained model with it's associated json file.
> > > **This is the code,**
> > > from imageai.Prediction.Custom import CustomImagePrediction
> > > import os
> > > execution_path = os.getcwd()
> > > prediction = CustomImagePrediction()
> > > prediction.setModelTypeAsResNet()
> > > prediction.setModelPath(os.path.join(execution_path, "vigil.h5"))
> > > prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
> > > prediction.loadModel(num_objects=10)
> > > predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "896.png"), result_count=5)
> > > for eachPrediction, eachProbability in zip(predictions, probabilities):
> > > print(eachPrediction , " : " , eachProbability)
> > > Please suggest a solution
> > 
> > 
> > try this model "idenprof_061-0.7933.h5"
> 
> Hey, it worked for me. Turns out if you rename your model file(h5) it won't work. Thanks a ton!!!!!.
> I have another query can we use this resnet model for live video object detection? If let's say I use YOLO for object detection then use the ResNet model for classification. Can this happen?

Yeah, it can work for live video object detection. But why you use YOLO for object detection and use the ResNet model for classification ? Object detection already recognize the object. In my opinion you just need object detection.

**Comment by Manny5Parkinson** [comment]
> > > > Hello,
> > > > I am facing the same problem except I am using my own custom trained model with it's associated json file.
> > > > **This is the code,**
> > > > from imageai.Prediction.Custom import CustomImagePrediction
> > > > import os
> > > > execution_path = os.getcwd()
> > > > prediction = CustomImagePrediction()
> > > > prediction.setModelTypeAsResNet()
> > > > prediction.setModelPath(os.path.join(execution_path, "vigil.h5"))
> > > > prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
> > > > prediction.loadModel(num_objects=10)
> > > > predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "896.png"), result_count=5)
> > > > for eachPrediction, eachProbability in zip(predictions, probabilities):
> > > > print(eachPrediction , " : " , eachProbability)
> > > > Please suggest a solution
> > > 
> > > 
> > > try this model "idenprof_061-0.7933.h5"
> > 
> > 
> > Hey, it worked for me. Turns out if you rename your model file(h5) it won't work. Thanks a ton!!!!!.
> > I have another query can we use this resnet model for live video object detection? If let's say I use YOLO for object detection then use the ResNet model for classification. Can this happen?
> 
> Yeah, it can work for live video object detection. But why you use YOLO for object detection and use the ResNet model for classification ? Object detection already recognize the object. In my opinion you just need object detection.

Could you provide more details on how I can use the ResNet for Live Video Object Detection? I trained a YOLO model (using darkflow) on custom dataset. While the model can correctly detect objects in images I can find no bounding boxes in the video (I am on Windows 10 btw). The ResNet is another model I trained which has got around 93.5% accuracy. So, I hope to use this ResNet on videos.

My initial thoughts were that, since YOLO is already trained to detect some objects, I wish to use ResNet to classify the detected objects into certain classes.

**Comment by TheNewJavaman** [comment]
@randomarchive101 Did you ever solve your issue? I have a similar problem: ImageAI works fine on Windows but has this error on a Raspberry Pi running Linux.

**Comment by KeyCuevasMelgarejo** [comment]
Hola, estuve con el mismo problema, casi una semana intentando, por fin lo solucioné.
Al parecer existen incompatibilidades con la libreria h5py en versiones recientes.
En mi caso apliqué el siguiente comando de instalacion:

pip install h5py==2.10.0

Espero les sirva.
