### ISSUE TITLE
ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.

### ISSUE THREAD

**Issue by kratika-lahoti** [OlafenwaMoses/ImageAI#432]
I have below packages

Keras                              2.3.1               
tensorboard                        2.0.2               
tensorflow                         2.0.0               
tensorflow-datasets                1.2.0               
tensorflow-estimator               2.0.1               
tensorflow-gpu                     2.0.0               
tensorflow-hub                     0.6.0               
imageai                            2.1.5     

Error
`
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 75, 75, 64)   9472        input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 75, 75, 64)   256         conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 75, 75, 64)   0           batch_normalization[0][0]        
__________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)    (None, 37, 37, 64)   0           activation[0][0]                 
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 37, 37, 64)   4160        max_pooling2d[0][0]              
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 37, 37, 64)   256         conv2d_2[0][0]                   
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 37, 37, 64)   0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 37, 37, 64)   36928       activation_1[0][0]               
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 37, 37, 64)   256         conv2d_3[0][0]                   
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 37, 37, 64)   0           batch_normalization_3[0][0]      
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 37, 37, 256)  16640       activation_2[0][0]               
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 37, 37, 256)  16640       max_pooling2d[0][0]              
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 37, 37, 256)  1024        conv2d_4[0][0]                   
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 37, 37, 256)  1024        conv2d_1[0][0]                   
__________________________________________________________________________________________________
add (Add)                       (None, 37, 37, 256)  0           batch_normalization_4[0][0]      
                                                                 batch_normalization_1[0][0]      
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 37, 37, 256)  0           add[0][0]                        
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 37, 37, 64)   16448       activation_3[0][0]               
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, 37, 37, 64)   256         conv2d_5[0][0]                   
__________________________________________________________________________________________________
activation_4 (Activation)       (None, 37, 37, 64)   0           batch_normalization_5[0][0]      
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 37, 37, 64)   36928       activation_4[0][0]               
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, 37, 37, 64)   256         conv2d_6[0][0]                   
__________________________________________________________________________________________________
activation_5 (Activation)       (None, 37, 37, 64)   0           batch_normalization_6[0][0]      
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 37, 37, 256)  16640       activation_5[0][0]               
__________________________________________________________________________________________________
batch_normalization_7 (BatchNor (None, 37, 37, 256)  1024        conv2d_7[0][0]                   
__________________________________________________________________________________________________
add_1 (Add)                     (None, 37, 37, 256)  0           batch_normalization_7[0][0]      
                                                                 activation_3[0][0]               
__________________________________________________________________________________________________
activation_6 (Activation)       (None, 37, 37, 256)  0           add_1[0][0]                      
__________________________________________________________________________________________________
conv2d_8 (Conv2D)               (None, 37, 37, 64)   16448       activation_6[0][0]               
__________________________________________________________________________________________________
batch_normalization_8 (BatchNor (None, 37, 37, 64)   256         conv2d_8[0][0]                   
__________________________________________________________________________________________________
activation_7 (Activation)       (None, 37, 37, 64)   0           batch_normalization_8[0][0]      
__________________________________________________________________________________________________
conv2d_9 (Conv2D)               (None, 37, 37, 64)   36928       activation_7[0][0]               
__________________________________________________________________________________________________
batch_normalization_9 (BatchNor (None, 37, 37, 64)   256         conv2d_9[0][0]                   
__________________________________________________________________________________________________
activation_8 (Activation)       (None, 37, 37, 64)   0           batch_normalization_9[0][0]      
__________________________________________________________________________________________________
conv2d_10 (Conv2D)              (None, 37, 37, 256)  16640       activation_8[0][0]               
__________________________________________________________________________________________________
batch_normalization_10 (BatchNo (None, 37, 37, 256)  1024        conv2d_10[0][0]                  
__________________________________________________________________________________________________
add_2 (Add)                     (None, 37, 37, 256)  0           batch_normalization_10[0][0]     
                                                                 activation_6[0][0]               
__________________________________________________________________________________________________
activation_9 (Activation)       (None, 37, 37, 256)  0           add_2[0][0]                      
__________________________________________________________________________________________________
conv2d_12 (Conv2D)              (None, 19, 19, 128)  32896       activation_9[0][0]               
__________________________________________________________________________________________________
batch_normalization_12 (BatchNo (None, 19, 19, 128)  512         conv2d_12[0][0]                  
__________________________________________________________________________________________________
activation_10 (Activation)      (None, 19, 19, 128)  0           batch_normalization_12[0][0]     
__________________________________________________________________________________________________
conv2d_13 (Conv2D)              (None, 19, 19, 128)  147584      activation_10[0][0]              
__________________________________________________________________________________________________
batch_normalization_13 (BatchNo (None, 19, 19, 128)  512         conv2d_13[0][0]                  
__________________________________________________________________________________________________
activation_11 (Activation)      (None, 19, 19, 128)  0           batch_normalization_13[0][0]     
__________________________________________________________________________________________________
conv2d_14 (Conv2D)              (None, 19, 19, 512)  66048       activation_11[0][0]              
__________________________________________________________________________________________________
conv2d_11 (Conv2D)              (None, 19, 19, 512)  131584      activation_9[0][0]               
__________________________________________________________________________________________________
batch_normalization_14 (BatchNo (None, 19, 19, 512)  2048        conv2d_14[0][0]                  
__________________________________________________________________________________________________
batch_normalization_11 (BatchNo (None, 19, 19, 512)  2048        conv2d_11[0][0]                  
__________________________________________________________________________________________________
add_3 (Add)                     (None, 19, 19, 512)  0           batch_normalization_14[0][0]     
                                                                 batch_normalization_11[0][0]     
__________________________________________________________________________________________________
activation_12 (Activation)      (None, 19, 19, 512)  0           add_3[0][0]                      
__________________________________________________________________________________________________
conv2d_15 (Conv2D)              (None, 19, 19, 128)  65664       activation_12[0][0]              
__________________________________________________________________________________________________
batch_normalization_15 (BatchNo (None, 19, 19, 128)  512         conv2d_15[0][0]                  
__________________________________________________________________________________________________
activation_13 (Activation)      (None, 19, 19, 128)  0           batch_normalization_15[0][0]     
__________________________________________________________________________________________________
conv2d_16 (Conv2D)              (None, 19, 19, 128)  147584      activation_13[0][0]              
__________________________________________________________________________________________________
batch_normalization_16 (BatchNo (None, 19, 19, 128)  512         conv2d_16[0][0]                  
__________________________________________________________________________________________________
activation_14 (Activation)      (None, 19, 19, 128)  0           batch_normalization_16[0][0]     
__________________________________________________________________________________________________
conv2d_17 (Conv2D)              (None, 19, 19, 512)  66048       activation_14[0][0]              
__________________________________________________________________________________________________
batch_normalization_17 (BatchNo (None, 19, 19, 512)  2048        conv2d_17[0][0]                  
__________________________________________________________________________________________________
add_4 (Add)                     (None, 19, 19, 512)  0           batch_normalization_17[0][0]     
                                                                 activation_12[0][0]              
__________________________________________________________________________________________________
activation_15 (Activation)      (None, 19, 19, 512)  0           add_4[0][0]                      
__________________________________________________________________________________________________
conv2d_18 (Conv2D)              (None, 19, 19, 128)  65664       activation_15[0][0]              
__________________________________________________________________________________________________
batch_normalization_18 (BatchNo (None, 19, 19, 128)  512         conv2d_18[0][0]                  
__________________________________________________________________________________________________
activation_16 (Activation)      (None, 19, 19, 128)  0           batch_normalization_18[0][0]     
__________________________________________________________________________________________________
conv2d_19 (Conv2D)              (None, 19, 19, 128)  147584      activation_16[0][0]              
__________________________________________________________________________________________________
batch_normalization_19 (BatchNo (None, 19, 19, 128)  512         conv2d_19[0][0]                  
__________________________________________________________________________________________________
activation_17 (Activation)      (None, 19, 19, 128)  0           batch_normalization_19[0][0]     
__________________________________________________________________________________________________
conv2d_20 (Conv2D)              (None, 19, 19, 512)  66048       activation_17[0][0]              
__________________________________________________________________________________________________
batch_normalization_20 (BatchNo (None, 19, 19, 512)  2048        conv2d_20[0][0]                  
__________________________________________________________________________________________________
add_5 (Add)                     (None, 19, 19, 512)  0           batch_normalization_20[0][0]     
                                                                 activation_15[0][0]              
__________________________________________________________________________________________________
activation_18 (Activation)      (None, 19, 19, 512)  0           add_5[0][0]                      
__________________________________________________________________________________________________
conv2d_21 (Conv2D)              (None, 19, 19, 128)  65664       activation_18[0][0]              
__________________________________________________________________________________________________
batch_normalization_21 (BatchNo (None, 19, 19, 128)  512         conv2d_21[0][0]                  
__________________________________________________________________________________________________
activation_19 (Activation)      (None, 19, 19, 128)  0           batch_normalization_21[0][0]     
__________________________________________________________________________________________________
conv2d_22 (Conv2D)              (None, 19, 19, 128)  147584      activation_19[0][0]              
__________________________________________________________________________________________________
batch_normalization_22 (BatchNo (None, 19, 19, 128)  512         conv2d_22[0][0]                  
__________________________________________________________________________________________________
activation_20 (Activation)      (None, 19, 19, 128)  0           batch_normalization_22[0][0]     
__________________________________________________________________________________________________
conv2d_23 (Conv2D)              (None, 19, 19, 512)  66048       activation_20[0][0]              
__________________________________________________________________________________________________
batch_normalization_23 (BatchNo (None, 19, 19, 512)  2048        conv2d_23[0][0]                  
__________________________________________________________________________________________________
add_6 (Add)                     (None, 19, 19, 512)  0           batch_normalization_23[0][0]     
                                                                 activation_18[0][0]              
__________________________________________________________________________________________________
activation_21 (Activation)      (None, 19, 19, 512)  0           add_6[0][0]                      
__________________________________________________________________________________________________
conv2d_25 (Conv2D)              (None, 10, 10, 256)  131328      activation_21[0][0]              
__________________________________________________________________________________________________
batch_normalization_25 (BatchNo (None, 10, 10, 256)  1024        conv2d_25[0][0]                  
__________________________________________________________________________________________________
activation_22 (Activation)      (None, 10, 10, 256)  0           batch_normalization_25[0][0]     
__________________________________________________________________________________________________
conv2d_26 (Conv2D)              (None, 10, 10, 256)  590080      activation_22[0][0]              
__________________________________________________________________________________________________
batch_normalization_26 (BatchNo (None, 10, 10, 256)  1024        conv2d_26[0][0]                  
__________________________________________________________________________________________________
activation_23 (Activation)      (None, 10, 10, 256)  0           batch_normalization_26[0][0]     
__________________________________________________________________________________________________
conv2d_27 (Conv2D)              (None, 10, 10, 1024) 263168      activation_23[0][0]              
__________________________________________________________________________________________________
conv2d_24 (Conv2D)              (None, 10, 10, 1024) 525312      activation_21[0][0]              
__________________________________________________________________________________________________
batch_normalization_27 (BatchNo (None, 10, 10, 1024) 4096        conv2d_27[0][0]                  
__________________________________________________________________________________________________
batch_normalization_24 (BatchNo (None, 10, 10, 1024) 4096        conv2d_24[0][0]                  
__________________________________________________________________________________________________
add_7 (Add)                     (None, 10, 10, 1024) 0           batch_normalization_27[0][0]     
                                                                 batch_normalization_24[0][0]     
__________________________________________________________________________________________________
activation_24 (Activation)      (None, 10, 10, 1024) 0           add_7[0][0]                      
__________________________________________________________________________________________________
conv2d_28 (Conv2D)              (None, 10, 10, 256)  262400      activation_24[0][0]              
__________________________________________________________________________________________________
batch_normalization_28 (BatchNo (None, 10, 10, 256)  1024        conv2d_28[0][0]                  
__________________________________________________________________________________________________
activation_25 (Activation)      (None, 10, 10, 256)  0           batch_normalization_28[0][0]     
__________________________________________________________________________________________________
conv2d_29 (Conv2D)              (None, 10, 10, 256)  590080      activation_25[0][0]              
__________________________________________________________________________________________________
batch_normalization_29 (BatchNo (None, 10, 10, 256)  1024        conv2d_29[0][0]                  
__________________________________________________________________________________________________
activation_26 (Activation)      (None, 10, 10, 256)  0           batch_normalization_29[0][0]     
__________________________________________________________________________________________________
conv2d_30 (Conv2D)              (None, 10, 10, 1024) 263168      activation_26[0][0]              
__________________________________________________________________________________________________
batch_normalization_30 (BatchNo (None, 10, 10, 1024) 4096        conv2d_30[0][0]                  
__________________________________________________________________________________________________
add_8 (Add)                     (None, 10, 10, 1024) 0           batch_normalization_30[0][0]     
                                                                 activation_24[0][0]              
__________________________________________________________________________________________________
activation_27 (Activation)      (None, 10, 10, 1024) 0           add_8[0][0]                      
__________________________________________________________________________________________________
conv2d_31 (Conv2D)              (None, 10, 10, 256)  262400      activation_27[0][0]              
__________________________________________________________________________________________________
batch_normalization_31 (BatchNo (None, 10, 10, 256)  1024        conv2d_31[0][0]                  
__________________________________________________________________________________________________
activation_28 (Activation)      (None, 10, 10, 256)  0           batch_normalization_31[0][0]     
__________________________________________________________________________________________________
conv2d_32 (Conv2D)              (None, 10, 10, 256)  590080      activation_28[0][0]              
__________________________________________________________________________________________________
batch_normalization_32 (BatchNo (None, 10, 10, 256)  1024        conv2d_32[0][0]                  
__________________________________________________________________________________________________
activation_29 (Activation)      (None, 10, 10, 256)  0           batch_normalization_32[0][0]     
__________________________________________________________________________________________________
conv2d_33 (Conv2D)              (None, 10, 10, 1024) 263168      activation_29[0][0]              
__________________________________________________________________________________________________
batch_normalization_33 (BatchNo (None, 10, 10, 1024) 4096        conv2d_33[0][0]                  
__________________________________________________________________________________________________
add_9 (Add)                     (None, 10, 10, 1024) 0           batch_normalization_33[0][0]     
                                                                 activation_27[0][0]              
__________________________________________________________________________________________________
activation_30 (Activation)      (None, 10, 10, 1024) 0           add_9[0][0]                      
__________________________________________________________________________________________________
conv2d_34 (Conv2D)              (None, 10, 10, 256)  262400      activation_30[0][0]              
__________________________________________________________________________________________________
batch_normalization_34 (BatchNo (None, 10, 10, 256)  1024        conv2d_34[0][0]                  
__________________________________________________________________________________________________
activation_31 (Activation)      (None, 10, 10, 256)  0           batch_normalization_34[0][0]     
__________________________________________________________________________________________________
conv2d_35 (Conv2D)              (None, 10, 10, 256)  590080      activation_31[0][0]              
__________________________________________________________________________________________________
batch_normalization_35 (BatchNo (None, 10, 10, 256)  1024        conv2d_35[0][0]                  
__________________________________________________________________________________________________
activation_32 (Activation)      (None, 10, 10, 256)  0           batch_normalization_35[0][0]     
__________________________________________________________________________________________________
conv2d_36 (Conv2D)              (None, 10, 10, 1024) 263168      activation_32[0][0]              
__________________________________________________________________________________________________
batch_normalization_36 (BatchNo (None, 10, 10, 1024) 4096        conv2d_36[0][0]                  
__________________________________________________________________________________________________
add_10 (Add)                    (None, 10, 10, 1024) 0           batch_normalization_36[0][0]     
                                                                 activation_30[0][0]              
__________________________________________________________________________________________________
activation_33 (Activation)      (None, 10, 10, 1024) 0           add_10[0][0]                     
__________________________________________________________________________________________________
conv2d_37 (Conv2D)              (None, 10, 10, 256)  262400      activation_33[0][0]              
__________________________________________________________________________________________________
batch_normalization_37 (BatchNo (None, 10, 10, 256)  1024        conv2d_37[0][0]                  
__________________________________________________________________________________________________
activation_34 (Activation)      (None, 10, 10, 256)  0           batch_normalization_37[0][0]     
__________________________________________________________________________________________________
conv2d_38 (Conv2D)              (None, 10, 10, 256)  590080      activation_34[0][0]              
__________________________________________________________________________________________________
batch_normalization_38 (BatchNo (None, 10, 10, 256)  1024        conv2d_38[0][0]                  
__________________________________________________________________________________________________
activation_35 (Activation)      (None, 10, 10, 256)  0           batch_normalization_38[0][0]     
__________________________________________________________________________________________________
conv2d_39 (Conv2D)              (None, 10, 10, 1024) 263168      activation_35[0][0]              
__________________________________________________________________________________________________
batch_normalization_39 (BatchNo (None, 10, 10, 1024) 4096        conv2d_39[0][0]                  
__________________________________________________________________________________________________
add_11 (Add)                    (None, 10, 10, 1024) 0           batch_normalization_39[0][0]     
                                                                 activation_33[0][0]              
__________________________________________________________________________________________________
activation_36 (Activation)      (None, 10, 10, 1024) 0           add_11[0][0]                     
__________________________________________________________________________________________________
conv2d_40 (Conv2D)              (None, 10, 10, 256)  262400      activation_36[0][0]              
__________________________________________________________________________________________________
batch_normalization_40 (BatchNo (None, 10, 10, 256)  1024        conv2d_40[0][0]                  
__________________________________________________________________________________________________
activation_37 (Activation)      (None, 10, 10, 256)  0           batch_normalization_40[0][0]     
__________________________________________________________________________________________________
conv2d_41 (Conv2D)              (None, 10, 10, 256)  590080      activation_37[0][0]              
__________________________________________________________________________________________________
batch_normalization_41 (BatchNo (None, 10, 10, 256)  1024        conv2d_41[0][0]                  
__________________________________________________________________________________________________
activation_38 (Activation)      (None, 10, 10, 256)  0           batch_normalization_41[0][0]     
__________________________________________________________________________________________________
conv2d_42 (Conv2D)              (None, 10, 10, 1024) 263168      activation_38[0][0]              
__________________________________________________________________________________________________
batch_normalization_42 (BatchNo (None, 10, 10, 1024) 4096        conv2d_42[0][0]                  
__________________________________________________________________________________________________
add_12 (Add)                    (None, 10, 10, 1024) 0           batch_normalization_42[0][0]     
                                                                 activation_36[0][0]              
__________________________________________________________________________________________________
activation_39 (Activation)      (None, 10, 10, 1024) 0           add_12[0][0]                     
__________________________________________________________________________________________________
conv2d_44 (Conv2D)              (None, 5, 5, 512)    524800      activation_39[0][0]              
__________________________________________________________________________________________________
batch_normalization_44 (BatchNo (None, 5, 5, 512)    2048        conv2d_44[0][0]                  
__________________________________________________________________________________________________
activation_40 (Activation)      (None, 5, 5, 512)    0           batch_normalization_44[0][0]     
__________________________________________________________________________________________________
conv2d_45 (Conv2D)              (None, 5, 5, 512)    2359808     activation_40[0][0]              
__________________________________________________________________________________________________
batch_normalization_45 (BatchNo (None, 5, 5, 512)    2048        conv2d_45[0][0]                  
__________________________________________________________________________________________________
activation_41 (Activation)      (None, 5, 5, 512)    0           batch_normalization_45[0][0]     
__________________________________________________________________________________________________
conv2d_46 (Conv2D)              (None, 5, 5, 2048)   1050624     activation_41[0][0]              
__________________________________________________________________________________________________
conv2d_43 (Conv2D)              (None, 5, 5, 2048)   2099200     activation_39[0][0]              
__________________________________________________________________________________________________
batch_normalization_46 (BatchNo (None, 5, 5, 2048)   8192        conv2d_46[0][0]                  
__________________________________________________________________________________________________
batch_normalization_43 (BatchNo (None, 5, 5, 2048)   8192        conv2d_43[0][0]                  
__________________________________________________________________________________________________
add_13 (Add)                    (None, 5, 5, 2048)   0           batch_normalization_46[0][0]     
                                                                 batch_normalization_43[0][0]     
__________________________________________________________________________________________________
activation_42 (Activation)      (None, 5, 5, 2048)   0           add_13[0][0]                     
__________________________________________________________________________________________________
conv2d_47 (Conv2D)              (None, 5, 5, 512)    1049088     activation_42[0][0]              
__________________________________________________________________________________________________
batch_normalization_47 (BatchNo (None, 5, 5, 512)    2048        conv2d_47[0][0]                  
__________________________________________________________________________________________________
activation_43 (Activation)      (None, 5, 5, 512)    0           batch_normalization_47[0][0]     
__________________________________________________________________________________________________
conv2d_48 (Conv2D)              (None, 5, 5, 512)    2359808     activation_43[0][0]              
__________________________________________________________________________________________________
batch_normalization_48 (BatchNo (None, 5, 5, 512)    2048        conv2d_48[0][0]                  
__________________________________________________________________________________________________
activation_44 (Activation)      (None, 5, 5, 512)    0           batch_normalization_48[0][0]     
__________________________________________________________________________________________________
conv2d_49 (Conv2D)              (None, 5, 5, 2048)   1050624     activation_44[0][0]              
__________________________________________________________________________________________________
batch_normalization_49 (BatchNo (None, 5, 5, 2048)   8192        conv2d_49[0][0]                  
__________________________________________________________________________________________________
add_14 (Add)                    (None, 5, 5, 2048)   0           batch_normalization_49[0][0]     
                                                                 activation_42[0][0]              
__________________________________________________________________________________________________
activation_45 (Activation)      (None, 5, 5, 2048)   0           add_14[0][0]                     
__________________________________________________________________________________________________
conv2d_50 (Conv2D)              (None, 5, 5, 512)    1049088     activation_45[0][0]              
__________________________________________________________________________________________________
batch_normalization_50 (BatchNo (None, 5, 5, 512)    2048        conv2d_50[0][0]                  
__________________________________________________________________________________________________
activation_46 (Activation)      (None, 5, 5, 512)    0           batch_normalization_50[0][0]     
__________________________________________________________________________________________________
conv2d_51 (Conv2D)              (None, 5, 5, 512)    2359808     activation_46[0][0]              
__________________________________________________________________________________________________
batch_normalization_51 (BatchNo (None, 5, 5, 512)    2048        conv2d_51[0][0]                  
__________________________________________________________________________________________________
activation_47 (Activation)      (None, 5, 5, 512)    0           batch_normalization_51[0][0]     
__________________________________________________________________________________________________
conv2d_52 (Conv2D)              (None, 5, 5, 2048)   1050624     activation_47[0][0]              
__________________________________________________________________________________________________
batch_normalization_52 (BatchNo (None, 5, 5, 2048)   8192        conv2d_52[0][0]                  
__________________________________________________________________________________________________
add_15 (Add)                    (None, 5, 5, 2048)   0           batch_normalization_52[0][0]     
                                                                 activation_45[0][0]              
__________________________________________________________________________________________________
activation_48 (Activation)      (None, 5, 5, 2048)   0           add_15[0][0]                     
__________________________________________________________________________________________________
global_avg_pooling (GlobalAvera (None, 2048)         0           activation_48[0][0]              
__________________________________________________________________________________________________
dense (Dense)                   (None, 8)            16392       global_avg_pooling[0][0]         
__________________________________________________________________________________________________
activation_49 (Activation)      (None, 8)            0           dense[0][0]                      
==================================================================================================
Total params: 23,604,104
Trainable params: 23,550,984
Non-trainable params: 53,120
__________________________________________________________________________________________________
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of samples seen.
Found 8000 images belonging to 8 classes.
Found 273 images belonging to 8 classes.
JSON Mapping for the model classes saved to  D:/ML_input_data/endoscope/kvasir-dataset-v2/./endoscope_images1/json\model_class.json
Number of experiments (Epochs) :  1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    526                 as_ref=input_arg.is_ref,
--> 527                 preferred_dtype=default_dtype)
    528           except TypeError as err:

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_composite_tensors)
   1295     if ret is None:
-> 1296       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1297 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    285   _ = as_ref
--> 286   return constant(v, dtype=dtype, name=name)
    287 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in constant(value, dtype, shape, name)
    226   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 227                         allow_broadcast=True)
    228 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    264           value, dtype=dtype, shape=shape, verify_shape=verify_shape,
--> 265           allow_broadcast=allow_broadcast))
    266   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    436     if values is None:
--> 437       raise ValueError("None values not supported.")
    438     # if dtype is provided, forces numpy array to be the type

ValueError: None values not supported.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    540               observed = ops.internal_convert_to_tensor(
--> 541                   values, as_ref=input_arg.is_ref).dtype.name
    542             except ValueError as err:

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_composite_tensors)
   1295     if ret is None:
-> 1296       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1297 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    285   _ = as_ref
--> 286   return constant(v, dtype=dtype, name=name)
    287 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in constant(value, dtype, shape, name)
    226   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 227                         allow_broadcast=True)
    228 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    264           value, dtype=dtype, shape=shape, verify_shape=verify_shape,
--> 265           allow_broadcast=allow_broadcast))
    266   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    436     if values is None:
--> 437       raise ValueError("None values not supported.")
    438     # if dtype is provided, forces numpy array to be the type

ValueError: None values not supported.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-9baeba6e10fd> in <module>
----> 1 model_trainer.trainModel(num_objects =8, num_experiments = 1, show_network_summary=True, training_image_size=150,save_full_model=True)

~\Anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py in trainModel(self, num_objects, num_experiments, enhance_data, batch_size, initial_learning_rate, show_network_summary, training_image_size, continue_from_model, transfer_from_model, transfer_with_full_training, initial_num_objects, save_full_model)
    340         model.fit_generator(train_generator, steps_per_epoch=int(num_train / batch_size), epochs=self.__num_epochs,
    341                             validation_data=test_generator,
--> 342                             validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler, tensorboard])
    343 
    344 

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1295         shuffle=shuffle,
   1296         initial_epoch=initial_epoch,
-> 1297         steps_name='steps_per_epoch')
   1298 
   1299   def evaluate_generator(self,

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    263 
    264       is_deferred = not model._is_compiled
--> 265       batch_outs = batch_function(*batch_data)
    266       if not isinstance(batch_outs, list):
    267         batch_outs = [batch_outs]

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1015 
   1016       self._update_sample_weight_modes(sample_weights=sample_weights)
-> 1017       self._make_train_function()
   1018       outputs = self.train_function(ins)  # pylint: disable=not-callable
   1019 

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py in _make_train_function(self)
   2114           # Training updates
   2115           updates = self.optimizer.get_updates(
-> 2116               params=self._collected_trainable_weights, loss=self.total_loss)
   2117           # Unconditional updates
   2118           updates += self.get_updates_for(None)

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\optimizers.py in get_updates(self, loss, params)
    474 
    475   def get_updates(self, loss, params):
--> 476     grads = self.get_gradients(loss, params)
    477     self.updates = []
    478 

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\optimizers.py in get_gradients(self, loss, params)
     90     """
     91     grads = K.gradients(loss, params)
---> 92     if None in grads:
     93       raise ValueError('An operation has `None` for gradient. '
     94                        'Please make sure that all of your ops have a '

~\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py in tensor_equals(self, other)
   1334       return gen_math_ops.equal(self, other, incompatible_shape_error=False)
   1335     else:
-> 1336       return gen_math_ops.equal(self, other)
   1337   else:
   1338     # In legacy graph mode, tensor equality is object equality

~\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py in equal(x, y, incompatible_shape_error, name)
   3625   _, _, _op = _op_def_lib._apply_op_helper(
   3626         "Equal", x=x, y=y, incompatible_shape_error=incompatible_shape_error,
-> 3627                  name=name)
   3628   _result = _op.outputs[:]
   3629   _inputs_flat = _op.inputs

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    543               raise ValueError(
    544                   "Tried to convert '%s' to a tensor and failed. Error: %s" %
--> 545                   (input_name, err))
    546             prefix = ("Input '%s' of '%s' Op has type %s that does not match" %
    547                       (input_name, op_type_name, observed))

ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.`

**Comment by AbimbolaOO** [comment]
Hello @kratika-lahoti,

To resolve the issue you are currently having you need to make sure your python version is not greater than python3.6. To see your python version type python3 --version to your command line.
Having done that make sure you install the exact versions of the packages listed below in the given order.
pip install tensorflow==1.13.1 or pip3 install tensorflow-gpu==1.13.1 if you are using a GPU
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade
