### ISSUE TITLE
Training configurations 

### ISSUE THREAD

**Issue by kghalieh** [OlafenwaMoses/ImageAI#441]
Does the training api perform image augmentation by default?
I have four classes of objects (arrows:up, down, left and right) the model perform great for up and down but not for left and right however I increase the samples. 
So I just want to make sure if the API is not trying to increase the samples by default since it will produce wrong lables.

**Comment by rola93** [comment]
Yes it does. It is not very well documented, but you can read its source code, is not that hard.

**Comment by kghalieh** [comment]
Yea, I disabled it from the source code. Apologise for the late comment
