### ISSUE TITLE
setTrainConfig endless working for custom dataset

### ISSUE THREAD

**Issue by Anastasiyabordak** [OlafenwaMoses/ImageAI#445]
I use such code:
`trainer = DetectionModelTrainer())`
`trainer.setModelTypeAsYOLOv3()`
`trainer.setDataDirectory(data_directory=MY_DATA_DIR)`
`list_of_objects = ['my_custom_object_1', 'my_custom_object_2' ,...])`
And block:
`trainer.setTrainConfig(object_names_array=list_of_objects , batch_size=16, num_experiments=200, train_from_pretrained_model="pretrained-yolov3.h5")`
Has warnings:
`/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/gen_anchors.py:21: RuntimeWarning: divide by zero encountered in double_scalars
  similarity = (c_w*c_h)/(w*h)
/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/gen_anchors.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  similarity = w*h/(c_w*c_h)
/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/gen_anchors.py:15: RuntimeWarning: invalid value encountered in double_scalars
  similarity = w*h/(c_w*c_h))`

trainer.setTrainConfig was running with ~98% CPU without any results for about 30 hours. How to fix it?

Is it a problem with my Pascal VOC format?

**Comment by nddthecollector** [comment]
Hi,
I am facing the same problem. Have you found a solution yet?

**Comment by Anastasiyabordak** [comment]
> 
> 
> Hi,
> I am facing the same problem. Have you found a solution yet?

Nope. It is because of [this line](https://github.com/OlafenwaMoses/ImageAI/blob/a62d1d9003c6a8678e75cde598f27c413d927db2/imageai/Detection/Custom/gen_anchors.py#L95)
For large custom dataset it doesn't work

**Comment by nddthecollector** [comment]
That's really sad. Thank you for your information.

**Comment by vykintazo** [comment]
Hey everyone,
how large are your large datasets? I have dataset of about 1500 images and wondering whether I should wait for it to generate anchors or not.
Also, would it be possible to provide your own anchors?

**Comment by Anastasiyabordak** [comment]
I had about 90k, 1000+ photo Bbox, good hardware. It was like endless

> 
> 
> Hey everyone,
> how large are your large datasets? I have dataset of about 1500 images and wondering whether I should wait for it to generate anchors or not.
> Also, would it be possible to provide your own anchors?

**Comment by osiastossou** [comment]
@Anastasiyabordak 
Please do you get an solution ?
I have the same problem
