### ISSUE TITLE
TypeError: must be str, not numpy.float64

### ISSUE THREAD

**Issue by koala-lava** [OlafenwaMoses/ImageAI#45]
[Your example tutorial](https://towardsdatascience.com/object-detection-with-10-lines-of-code-d6cb4d86f606) has this line:
`print(eachObject["name"] + " : " + eachObject["percentage_probability"] )`

But for me it throws TypeError exception, how do you make it to work? :)  Maybe I forgot something I'm not sure. I use python 3.6.6

I have to use str() function:
`print(eachObject["name"] + " : " + str(eachObject["percentage_probability"]) )`

**Comment by OlafenwaMoses** [comment]
All you need to do is to change the "+" icon to "," . This was changed in the latest version. I will update the tutorial also.
