### ISSUE TITLE
Version conflicts with dependencies using the recommended tenserflow version

### ISSUE THREAD

**Issue by derekpitts** [OlafenwaMoses/ImageAI#461]
I am trying to create a custom detection model following the instructions here:
https://imageai.readthedocs.io/en/latest/customdetection/
or
https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff

However I am running into version conflicts when using the recommended tensorflow-gpu == 1.13.1. It looks like the newest version of keras is not compatible with that version anymore. Can you specify the keras version that is used along side of this because otherwise the instructions in your examples do not work or at least specify your last known versions of dependencies because those given on your GitHub page no longer apply.

Keras version = ??
Tenserflow version = 1.13.1
ImageAi version = ??

Thanks!

**Comment by AbimbolaOO** [comment]
Hello @derekpitts,

A good way to resolve this is to wipe (uninstall) your computer clean of any version of TensorFlow you have then reinstall the required version to run imageAI or you can also install the required TensorFlow version in a virtual environment. To create a new virtual environment type **python3 -m venv venv** Please make sure your version of python is not greater than python3.6 before you start. Having done any of that you can go ahead and install all the following packages. 

pip install tensorflow==1.13.1 or pip3 install tensorflow-gpu==1.13.1 if you are using a GPU
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade
