### ISSUE TITLE
Labels for training set.

### ISSUE THREAD

**Issue by sanathbharadwaj** [OlafenwaMoses/ImageAI#47]
Hello,
This library is gonna save my life. Just a clarification. While training for the custom dataset, is labeling the images with the bounding boxes in the training set needed? I don't know much about RetinaNet. Hence, just wanted to confirm. I did see in many other methods, bounding boxes and other kinds of segmentations were done on the image set.

Thanks in Advance

With Regards
Sanath Bharadwaj

**Comment by OlafenwaMoses** [comment]
Hello, 
ImageAI supports training custom models for Image recognition only. This requires only labels, which will be automatically handled by ImageAI as far as your dataset is organized as described in ImageAI's documentation. Find the tutorial and documentation for custom training of image recognition models below. 

https://towardsdatascience.com/train-image-recognition-ai-with-5-lines-of-code-8ed0bdd8d9ba

http://imageai.readthedocs.io/en/latest/custom/index.html

**Comment by OlafenwaMoses** [comment]
Support for training custom object detection models will be provided in future versions of ImageAI.
