### ISSUE TITLE
how i can specify GPU number ?

### ISSUE THREAD

**Issue by 1f9763** [OlafenwaMoses/ImageAI#48]
when i use 

```
detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath(execution_path + 'resnet50_coco_best_v2.0.1.h5')
detector.loadModel()

detections = detector.detectObjectsFromImage(input_image=input_img, minimum_percentage_probability=70)
```

**Comment by OlafenwaMoses** [comment]
Hello there, because ImageAI depends on Keras, Keras automatically uses and manages GPU if available. You can learn more about this via the link below. 
https://keras.io/getting-started/faq/#how-can-i-run-keras-on-gpu

**Comment by cagnulein** [comment]
@1f9763 Which GPU card did you use? I would like to do the same for an alarm system, and i would like help my CPU (i7 7th generation 8 core) with a GPU.
