### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by chang4869** [OlafenwaMoses/ImageAI#480]
I am confused, as long as I use the model I trained, the following problems will occur   815                 if extract_detected_objects:

~/anaconda3/lib/python3.6/site-packages/imageai/Detection/Custom/__init__.py in draw_boxes_and_caption(self, image_frame, v_boxes, v_labels, v_scores, show_names, show_percentage)
   1364             class_color = self.label_color(self.__labels.index(v_labels[i]))
   1365 
-> 1366             image_frame = cv2.rectangle(image_frame, (x1, y1), (x2, y2), class_color, 2)
   1367 
   1368             label = ""

OverflowError: Python int too large to convert to C long

**Comment by AbimbolaOO** [comment]
The cause of this can be found here [https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma](click)

**Comment by AbimbolaOO** [comment]
The solution to this can be found here [https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma](URL)
