### ISSUE TITLE
Does it support Realtime object detection?

### ISSUE THREAD

**Issue by AhSem** [OlafenwaMoses/ImageAI#5]
Hi, I am wondering if ImageAI currently supports realtime object detection with a live rtsp stream?

The current sample source codes show that it takes in a sample mp4 video file and later output another video file with objects detected. 

I am using Kivy Video widget to display an RTSP live stream, and am wondering if could implement ImageAI so that we can see the objects being detected and tracked in real time.

Please advice.

**Comment by OlafenwaMoses** [comment]
ImageAI supports Numpy array and Filestream inputs and Numpy array outputs. You can obtain the each frame returned from live stream and parse it into the **detectObjectsFromImage()**  function, as instructed in the details and documentation in the link below. 

https://github.com/OlafenwaMoses/ImageAI/tree/master/imageai/Detection

Please note that the object detection method currently supported in ImageAI is RetinaNet,  a high performance algorithm that requires a NVIDIA GPU powered system for real-time object detection tasks. 

In the next version of ImageAI,  we will provide implementations of camera and live stream inputs for object detection.
