### ISSUE TITLE
How to perform custom object detection using custom dataset?

### ISSUE THREAD

**Issue by futtBucker** [OlafenwaMoses/ImageAI#50]
Hi, thanks for developing such amazing library for object recognition. I'm new to this field but I learn something new everyday. 
I've been doing some image prediction using custom model (such in https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/CUSTOMTRAINING.md), which is working properly. Now I'm trying to use the same model for object detection. 
This is my code : 
```python
from imageai.Detection import ObjectDetection
import os
execution_path = os.getcwd()
detection = ObjectDetection()
detection.setModelTypeAsRetinaNet()
detection.setModelPath(os.path.join(execution_path, "model_ex-063_acc-0.733333.h5"))
detection.loadModel()
# blablabla
```

However I stumbled upon an error : 

```python
ValueError                                Traceback (most recent call last)
<ipython-input-7-5e894296657a> in <module>()
      1 detection.setModelPath(os.path.join(execution_path, "model_ex-063_acc-0.733333.h5"))
----> 2 detection.loadModel()

~\Anaconda3\lib\site-packages\imageai\Detection\__init__.py in loadModel(self, detection_speed)
    120             elif(self.__modelType == "retinanet"):
    121                 model = resnet50_retinanet(num_classes=80)
--> 122                 model.load_weights(self.modelPath)
    123                 self.__model_collection.append(model)
    124                 self.__modelLoaded = True

~\Anaconda3\lib\site-packages\keras\engine\network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
   1178             else:
   1179                 saving.load_weights_from_hdf5_group(
-> 1180                     f, self.layers, reshape=reshape)
   1181 
   1182     def _updated_config(self):

~\Anaconda3\lib\site-packages\keras\engine\saving.py in load_weights_from_hdf5_group(f, layers, reshape)
    899                          'containing ' + str(len(layer_names)) +
    900                          ' layers into a model with ' +
--> 901                          str(len(filtered_layers)) + ' layers.')
    902 
    903     # We batch weight value assignments in a single backend call

ValueError: You are trying to load a weight file containing 107 layers into a model with 116 layers.
```

Not sure if we have this feature, I just trying my luck. Let me know if it hasn't yet implemented, it's a bug, or is it error from my side?

T.Hanks

**Comment by OlafenwaMoses** [comment]
Hello, the ModelTraining class provided only supports training custom models for image prediction ( not object detection).  We will add support for training object detection models in future versions. Please note that you can not use an image prediction model for object detection.

**Comment by patrickduhaime** [comment]
Hello, Thanx for alle the great work !!!

Any update on this ? 

I like ImageAI very much but I  need to make my own dataset to detect some Kalmia plants to irradicate in wild blueberry fields, the images are taken with an NDVI lens on the camera so, I cannot use the already made datasets for this.

**Comment by OlafenwaMoses** [comment]
Kindly follow up with #8
