### ISSUE TITLE
How do i exit a real time camera video input ? 

### ISSUE THREAD

**Issue by SamsLogic** [OlafenwaMoses/ImageAI#510]
Please add a safe kill switch for video input using camera. I have to kill the whole program to kill the video detection.

PS: Thank you for this library. It is getting very handy for my project. Great work.

**Comment by AbimbolaOO** [comment]
I think there are no-kill switch builtin. All you need to do is press Cntrl+C or Cntrl+X on your keyboard.  At times you would be required to press any of those keys twice.
