### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by nofacemane** [OlafenwaMoses/ImageAI#511]
Hi Ola,

 the following command;
 `pip install imageai --upgrade ` 
successfully addressed the error: ModuleNotFoundError: No module named 'imageai'

However, I am now faced with the following error;
ModuleNotFoundError: No module named 'imageai' 

perhaps seen this before? any advice?

**Comment by vinaykumarprabhu** [comment]
@nofacemane 
Try installing !pip install opencv-python.

**Comment by AbimbolaOO** [comment]
Hello @nofacemane,

To resolve the issue you are currently having you need to make sure your python version is not greater than python3.6. To see your python version type python3 --version to your command line.

Having done that make sure you install the exact versions of the packages listed below in the given order.
pip install tensorflow==1.13.1 or pip3 install tensorflow-gpu==1.13.1 if you are using a GPU
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade
