### ISSUE TITLE
How can I  get a real-time window when I run examples/camera_feed_detection.py

### ISSUE THREAD

**Issue by chaotianjiao** [OlafenwaMoses/ImageAI#512]
when I run [camera_feed_detection.py](https://github.com/OlafenwaMoses/ImageAI/blob/master/examples/camera_feed_detection.py)
it show my mac camera is working,but I can't get a window to see the result.
what should I add into the code to open a window and get the real-time detection result?
Thanks!

**Comment by nickums** [comment]
the documentation describes the  per_frame_function=forFrame procedure in which the frame is displayed by plt
