### ISSUE TITLE
how to load two prediction model at the same time?

### ISSUE THREAD

**Issue by LCorleone** [OlafenwaMoses/ImageAI#52]
hi, first excellent job you did.
I trained two different prediction model, and i want to load them at the same time.
```
# hat classifier
hat_prediction = CustomImagePrediction()
hat_prediction.setModelTypeAsResNet()
# prediction.setModelTypeAsInceptionV3()
hat_prediction.setModelPath(os.path.join(execution_path, 'classifier', 'models', "20180724VIDEO_ex-036_acc-0.988451.h5"))
hat_prediction.setJsonPath(os.path.join(execution_path, 'classifier', 'json', "model_class.json"))
hat_prediction.loadModel(num_objects=2)

# cloth classifier
cloth_prediction = CustomImagePrediction()
cloth_prediction.setModelTypeAsResNet()
cloth_prediction.setModelPath(os.path.join(execution_path, 'cloth_classifier', 'models', "20180724VIDEO_ex-040_acc-0.994318.h5"))
cloth_prediction.setJsonPath(os.path.join(execution_path, 'cloth_classifier', 'json', "model_class.json"))
cloth_prediction.loadModel(num_objects=2)
```
But i found that it seems to fail as it can only load one?

**Comment by LCorleone** [comment]
I solved it. 
It can load two models at the same time.
However, here the global CLASS_INDEX will overwrite two different class names and should be modified.
```
def decode_predictions(preds, top=5, model_json=""):
    global CLASS_INDEX

    if CLASS_INDEX is None:
        CLASS_INDEX = json.load(open(model_json))
    results = []
    for pred in preds:
        top_indices = pred.argsort()[-top:][::-1]
        for i in top_indices:
            each_result = []
            each_result.append(CLASS_INDEX[str(i)])
            each_result.append(pred[i])
            results.append(each_result)
    return results
```

**Comment by OlafenwaMoses** [comment]
@LCorleone Thank you for working on this. It is very useful to have 2 or more custom models active. I will adopt your modifications in the next version of ImageAI.

**Comment by jgros** [comment]
@LCorleone Can you share what you did to make it work as a workaround?

**Comment by maxlamenace417** [comment]
Hello, has it been changed in the code yet?

I think a quick workaround would be:     (however the model would be loaded each time)
`def decode_predictions(preds, top=5, model_json=""):
    shittyVariable = json.load(open(model_json))
    results = []
    for pred in preds:
        top_indices = pred.argsort()[-top:][::-1]
        for i in top_indices:
            each_result = []
            each_result.append(shittyVariable [str(i)])
            each_result.append(pred[i])
            results.append(each_result)
    return results`

But the main question is why is this method not directly in the CustomImagePrediction class???
