### ISSUE TITLE
detectCustomObjectsFromVideo() got multiple values for argument 'custom_objects'

### ISSUE THREAD

**Issue by Sanket307** [OlafenwaMoses/ImageAI#527]
Hello,

when i try to run customobjectdetection on google colaboratory with gpu getting  below error.

![Screenshot from 2020-05-01 16-53-57](https://user-images.githubusercontent.com/40209821/80802503-209df200-8bcd-11ea-823f-1f70897b03cb.png)

Please help me to figure it out.

**Comment by Terizian** [comment]
I think custom_objects takes a CustomObjects object, not a dictionary as you have there.

I would suggest commenting the two lines and writing this: `custom_objects = detector.CustomObjects(truck=True)`

**Comment by vinaykumarprabhu** [comment]
> Hello,
> 
> when i try to run customobjectdetection on google colaboratory with gpu getting below error.
> 
> ![Screenshot from 2020-05-01 16-53-57](https://user-images.githubusercontent.com/40209821/80802503-209df200-8bcd-11ea-823f-1f70897b03cb.png)
> 
> Please help me to figure it out.

@Terizian 

> Hello,
> 
> when i try to run customobjectdetection on google colaboratory with gpu getting below error.
> 
> ![Screenshot from 2020-05-01 16-53-57](https://user-images.githubusercontent.com/40209821/80802503-209df200-8bcd-11ea-823f-1f70897b03cb.png)
> 
> Please help me to figure it out.

@Sanket307 ,

the parameter that needs to be passed should to custom object should have the values mentioned for all the output categories supported by imageai, which in ur case is not i.e. u have specified only {'person':'valid'}
Instead u should have done {'person': 'valid', 'bicycle': 'invalid', 'car': 'invalid', 'motorcycle': 'invalid', 'airplane': 'invalid', 'bus': 'invalid', 'train': 'invalid', 'truck': 'invalid', 'boat': 'invalid', 'traffic light': 'invalid', 'fire hydrant': 'invalid', 'stop sign': 'invalid', 'parking meter': 'invalid', 'bench': 'invalid', 'bird': 'invalid', 'cat': 'invalid', 'dog': 'invalid', 'horse': 'invalid', 'sheep': 'invalid', 'cow': 'invalid', 'elephant': 'invalid', 'bear': 'invalid', 'zebra': 'invalid', 'giraffe': 'invalid', 'backpack': 'invalid', 'umbrella': 'invalid', 'handbag': 'invalid', 'tie': 'invalid', 'suitcase': 'invalid', 'frisbee': 'invalid', 'skis': 'invalid', 'snowboard': 'invalid', 'sports ball': 'invalid', 'kite': 'invalid', 'baseball bat': 'invalid', 'baseball glove': 'invalid', 'skateboard': 'invalid', 'surfboard': 'invalid', 'tennis racket': 'invalid', 'bottle': 'invalid', 'wine glass': 'invalid', 'cup': 'invalid', 'fork': 'invalid', 'knife': 'invalid', 'spoon': 'invalid', 'bowl': 'invalid', 'banana': 'invalid', 'apple': 'invalid', 'sandwich': 'invalid', 'orange': 'invalid', 'broccoli': 'invalid', 'carrot': 'invalid', 'hot dog': 'invalid', 'pizza': 'invalid', 'donut': 'invalid', 'cake': 'invalid', 'chair': 'invalid', 'couch': 'invalid', 'potted plant': 'invalid', 'bed': 'invalid', 'dining table': 'invalid', 'toilet': 'invalid', 'tv': 'invalid', 'laptop': 'invalid', 'mouse': 'invalid', 'remote': 'invalid', 'keyboard': 'invalid', 'cell phone': 'invalid', 'microwave': 'invalid', 'oven': 'invalid', 'toaster': 'invalid', 'sink': 'invalid', 'refrigerator': 'invalid', 'book': 'invalid', 'clock': 'invalid', 'vase': 'invalid', 'scissors': 'invalid', 'teddy bear': 'invalid', 'hair dryer': 'invalid', 'toothbrush': 'invalid'}
and this would have worked.

And also as mentioned @Terizian if u specify `detector.CustomObjects(truck=True)` this method actually return a dictionary as mentioed above.

Hope this helps.

**Comment by vinaykumarprabhu** [comment]
@Sanket307 ,

the parameter that needs to be passed should to custom object should have the values mentioned for all the output categories supported by imageai, which in ur case is not i.e. u have specified only {'person':'valid'}
Instead u should have done {'person': 'valid', 'bicycle': 'invalid', 'car': 'invalid', 'motorcycle': 'invalid', 'airplane': 'invalid', 'bus': 'invalid', 'train': 'invalid', 'truck': 'invalid', 'boat': 'invalid', 'traffic light': 'invalid', 'fire hydrant': 'invalid', 'stop sign': 'invalid', 'parking meter': 'invalid', 'bench': 'invalid', 'bird': 'invalid', 'cat': 'invalid', 'dog': 'invalid', 'horse': 'invalid', 'sheep': 'invalid', 'cow': 'invalid', 'elephant': 'invalid', 'bear': 'invalid', 'zebra': 'invalid', 'giraffe': 'invalid', 'backpack': 'invalid', 'umbrella': 'invalid', 'handbag': 'invalid', 'tie': 'invalid', 'suitcase': 'invalid', 'frisbee': 'invalid', 'skis': 'invalid', 'snowboard': 'invalid', 'sports ball': 'invalid', 'kite': 'invalid', 'baseball bat': 'invalid', 'baseball glove': 'invalid', 'skateboard': 'invalid', 'surfboard': 'invalid', 'tennis racket': 'invalid', 'bottle': 'invalid', 'wine glass': 'invalid', 'cup': 'invalid', 'fork': 'invalid', 'knife': 'invalid', 'spoon': 'invalid', 'bowl': 'invalid', 'banana': 'invalid', 'apple': 'invalid', 'sandwich': 'invalid', 'orange': 'invalid', 'broccoli': 'invalid', 'carrot': 'invalid', 'hot dog': 'invalid', 'pizza': 'invalid', 'donut': 'invalid', 'cake': 'invalid', 'chair': 'invalid', 'couch': 'invalid', 'potted plant': 'invalid', 'bed': 'invalid', 'dining table': 'invalid', 'toilet': 'invalid', 'tv': 'invalid', 'laptop': 'invalid', 'mouse': 'invalid', 'remote': 'invalid', 'keyboard': 'invalid', 'cell phone': 'invalid', 'microwave': 'invalid', 'oven': 'invalid', 'toaster': 'invalid', 'sink': 'invalid', 'refrigerator': 'invalid', 'book': 'invalid', 'clock': 'invalid', 'vase': 'invalid', 'scissors': 'invalid', 'teddy bear': 'invalid', 'hair dryer': 'invalid', 'toothbrush': 'invalid'}
and this would have worked.

And also as mentioned @Terizian if u specify detector.CustomObjects(truck=True) this method actually return a dictionary as mention
<img width="1550" alt="Screenshot 2020-05-30 at 3 43 44 PM" src="https://user-images.githubusercontent.com/15928383/83325834-053a0b80-a28d-11ea-97e4-808e5a5a76d7.png">
ed above.

Hope this _helps.*
![image](https://user-images.githubusercontent.com/15928383/83325813-e9cf0080-a28c-11ea-9e97-9a47e8715d19.png)

**Comment by Sanket307** [comment]
Thanks for your comments.

Issue solved, As i am replacing original script but it is not replaced in colab so it generate error.
