### ISSUE TITLE
Will ImageAI support Yolo traning ?

### ISSUE THREAD

**Issue by chunyisong** [OlafenwaMoses/ImageAI#53]
Now ImageAI can train models using SqueezeNet, ResNet50, InceptionV3 and DenseNet,it is a nice work. Do you have plane to support Yolo V3 training？Thanks

**Comment by OlafenwaMoses** [comment]
We have plans to support training custom models for object detection using YOLO, TinyYOLO and RetinaNet. Once these features are ready, we will release it.

**Comment by chunyisong** [comment]
Nice！Thank you
