### ISSUE TITLE
What's the ETA of Tensorflow 2.2.0 support?

### ISSUE THREAD

**Issue by ivanfarkas2** [OlafenwaMoses/ImageAI#538]
# What's the ETA of Tensorflow 2.2.0 support?

**Comment by AbimbolaOO** [comment]
ImageAI creator and contributors are currently working on the next version of ImageAI and there is a very high chance it supports current and future releases of Tensorflow. So about the ETA, I would safely guess before the end this year.

**Comment by OlafenwaMoses** [comment]
ImaageAI now supports TF 2.4.0 . Visit the link below for more.

https://imageai.readthedocs.io/en/latest/index.html#installing-imageai
