### ISSUE TITLE
ImageAI with HoloLens?

### ISSUE THREAD

**Issue by jtrinidad6** [OlafenwaMoses/ImageAI#539]
Hello,

I was able to use your code to detect objects in videos and webcam using your tutorials, however, is it possible to use this with the live video feed in HoloLens? detect objects real-time in HoloLens?

**Comment by AbimbolaOO** [comment]
Hello @jtrinidad6,
As of now, ImageAI cannot be integrated with HoloLens. But one cool trick could be to get video recording from a hologram and give it to imageAI to work with.
