### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by aliguldummar** [OlafenwaMoses/ImageAI#54]
I have installed all libraries of Image AI but I am facing errors when I run any code example of image AI in spider ide. This error shows
File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found

anyone helps me  in this regard

**Comment by aliguldummar** [comment]
OlafenwaMoses thank you for your prompt response. From where I can download the model file . I could find the model file in imageAi files on GitHub. Kindly guide me

**Comment by aliguldummar** [comment]
I have downloaded all models but now I am facing this error:
raise ValueError("Ensure you specified correct input image, input type, output type and/or output image path ")  ValueError: Ensure you specified correct input image, input type, output type and/or output image path

**Comment by OlafenwaMoses** [comment]
This must have happened because you parsed the wrong image path into the detection function. Ensure the image you are trying to detect is in the path you specified in the detection function. 

You might paste the code you wrote here in case the error persists so that I can review it.

**Comment by aliguldummar** [comment]
rom imageai.Detection import ObjectDetection
import os
from time import time

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel(detection_speed="flash")

our_time = time()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "1.jpg"), output_image_path=os.path.join(execution_path , "1flash.jpg"), minimum_percentage_probability=30)
print("IT TOOK : ", time() - our_time)
for eachObject in detections:
    print(eachObject["name"] + " : " + eachObject["percentage_probability"] )
    print("--------------------------------")

**Comment by aliguldummar** [comment]
this code and simply run it . but it shows the error . how can add path

**Comment by aliguldummar** [comment]
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 35-36: malformed \N character escape 
above error  when i put image path 
detector = ObjectDetection("E:\MS CS\Computer Vision\project cv\New folder\ImageAI-2.0.2\images")
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel(detection_speed="flash")

**Comment by aliguldummar** [comment]
Now i have face this error when i copy code from examples to images folder


  File "E:/MS CS/Computer Vision/project cv/New folder/ImageAI-2.0.2/images/object_detection.py", line 16, in <module>
    print(eachObject["name"] + " : " + eachObject["percentage_probability"], " : ", eachObject["box_points"] )

TypeError: must be str, not numpy.float64

**Comment by OlafenwaMoses** [comment]
This error happened due to a recent change in the latest version of ImageAI. Replace the comma "+" with "," where you print the result.

**Comment by aliguldummar** [comment]
Thank you it is now working. I appreciate your favorable response and
guidance.

**Comment by OlafenwaMoses** [comment]
You are welcome.
