### ISSUE TITLE
RGB vs BGR images in detector

### ISSUE THREAD

**Issue by harshithere** [OlafenwaMoses/ImageAI#540]
Hey,
I recently faced a new issue when I was using OpenCV to load frames from a video and apply a custom object detector on those frames. I wish to identify vehicles in a video captured from a car driving on a highway. The code would roughly translate as -

```detector = ObjectDetection() 
detector.setModelTypeAsRetinaNet()
detector.setModelPath("models/resnet50_coco_best_v2.0.1.h5")
detector.loadModel()
custom = detector.CustomObjects(person=True, bicycle=True, car=True, motorcycle=True)    
input_image = cv2.imread('some_image.jpg')

detections = detector.detectCustomObjectsFromImage(input_image = input_image, 
input_type ='array', minimum_percentage_probability=30, custom_objects=custom)`
```

The model was performing quite poorly and after some debugging I realized that the performance improves if I convert the image to RGB format. 

``` input_image = cv2.imread('some_image.jpg')
input_image_conv = cv2.cvtColor(input_image, cv2.COLOR_BGR2RGB)
detections = detector.detectCustomObjectsFromImage(input_image = input_image_conv, 
input_type ='array',  minimum_percentage_probability=30, custom_objects=custom)`
```

I guess its because imageAI expects an image in RGB format whereas the default image type in openCV is BGR. Is this really the problem or am I missing something else? If yes, I believe this should be documented somewhere. Please provide your views

**Comment by rola93** [comment]
Yes, ImageAI expects RGB images and it's not well documented.

**Comment by harshithere** [comment]
Thanks @rola93 for confirming
Should I add that to the documentation and raise a pull request? Its a small detail but would have really saved me (and probably someone else) some time if I knew it before-hand
