### ISSUE TITLE
Save detected objects separately

### ISSUE THREAD

**Issue by mibalas** [OlafenwaMoses/ImageAI#542]
Hi, I'm using ImageAI to detect houses in georeferenced drone images.
I would like to know if is any way to save the detected objects in a separate file in vector format, like a geojson, dwg or kml file, for example? cause a need to show the objects in a map.

thank you

**Comment by Combinacijus** [comment]
Refering to [documentation](https://imageai.readthedocs.io/en/latest/detection/):

> “”“
> If extract_detected_objects = True and output_type = ‘array’, the the function will return:
> a **numpy array of the detected image**
> an array of dictionaries, with each dictionary corresponding to the objects
> detected in the image. Each dictionary contains the following property: * name (string) * percentage_probability (float) * **box_points (list of x1,y1,x2 and y2 coordinates)**
> an array of numpy arrays of each object detected in the image
> “””
>  `returned_image, detections, extracted_objects = detector.detectObjectsFromImage(input_image=”image.jpg”, output_type=”array”, extract_detected_objects=True, minimum_percentage_probability=30)`

ImageAI can return detections in numpy array (image) format it also returns box point in screen space etc. (refer documentation).

Now the question is can you transform this data to the format you want. And this is not the scope of ImageAI though.
