### ISSUE TITLE
problem in creating h5 file

### ISSUE THREAD

**Issue by Jitendra-Nathawat** [OlafenwaMoses/ImageAI#549]
i want to create a h5 file for my retinanet model or function and i have an xml , json , csv file of my dataset but still i am confusing , how can we create h5 file for our custom object detection ?

**Comment by Jitendra-Nathawat** [comment]
sir i am still waiting for your response

**Comment by AbimbolaOO** [comment]
Hello @Jitendra-Nathawat,

To create custom object detection you need to train the model with YOLOv3. This is what is available. Follow the code below and you would get an h5 file for your object detection. 

imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="hololens")
trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5")
trainer.trainModel()
