### ISSUE TITLE
ModuleNotFoundError: No module named 'imageai'

### ISSUE THREAD

**Issue by sherinaly** [OlafenwaMoses/ImageAI#55]
I followed the installation instructions and this error showed
ModuleNotFoundError: No module named 'imageai'
I updated the conda and spyder to let them see the module but still having the error.
Any suggestion how to solve it?

**Comment by OlafenwaMoses** [comment]
Have you tried installing it using pip

**Comment by novicecivon** [comment]
i also followed the instructions and used the pip installation, but the error still occurred

**Comment by monique94** [comment]
I have tried installing it using pip but encountered the same problem. Please how can we fix this

**Comment by aricus** [comment]
The same thing happened to me as well. I have installed and doublechecked the installs of all the modules:

pip install imageai
Requirement already satisfied: imageai in c:\users\robam\appdata\local\programs\python\python36-32\lib\site-packages (2.0.2)

and when I run it:
py imageDetect.py
Traceback (most recent call last):
  File "imageDetect.py", line 1, in <module>
    from imageai.Prediction import ImagePrediction
ModuleNotFoundError: No module named 'imageai'

**Comment by novicecivon** [comment]
i found out that i have 2 versions of anaconda installed in my device so i uninstalled the two and installed imageai again problem solved.

**Comment by HarishAgarwal88** [comment]
I faced the same issue, installed imageAI with pip instead of pip3, this solved problem for me.

**Comment by rohitgupta** [comment]
Harshit can you provide more details and step.

**Comment by OlafenwaMoses** [comment]
@rohitgupta run any of the commands below to install imageai

`pip3 install imageai --upgrade`
or 
`pip install imageai --upgrade` if the previous doesn't solve the problem.

**Comment by nofacemane** [comment]
Hi Ola, 

pip install imageai --upgrade -- addressed the error "ModuleNotFoundError: No module named 'imageai'"

but now im faced with the following error: ModuleNotFoundError: No module named 'cv2'

Any advice?

**Comment by HameedFawwaz** [comment]
> Hi Ola,
> 
> pip install imageai --upgrade -- addressed the error "ModuleNotFoundError: No module named 'imageai'"
> 
> but now im faced with the following error: ModuleNotFoundError: No module named 'cv2'
> 
> Any advice?

To fix the error of not having cv2, try using `pip install opencv-python` or `pip3 install opencv-python`. This should fix your error.

**Comment by ShreyaJamsandekar** [comment]
> @rohitgupta run any of the commands below to install imageai
> 
> `pip3 install imageai --upgrade`
> or
> `pip install imageai --upgrade` if the previous doesn't solve the problem.

I'm absolutely new to all of this , could someone tell me where these commands have to be written in the Spyder app , so i can install imageai?

**Comment by emcquaid** [comment]
> I'm absolutely new to all of this , could someone tell me where these commands have to be written in the Spyder app , so i can install imageai?

https://pip.pypa.io/en/stable/user_guide/

pip is a command line program. When you install pip, a pip command is added to your system, which can be run from the command prompt as follows:

`$ pip <pip arguments>`

If you cannot run the pip command directly (possibly because the location where it was installed isn’t on your operating system’s PATH) then you can run pip via the Python interpreter:

`$ python -m pip <pip arguments>`

On Windows, the py launcher can be used:

`$ py -m pip <pip arguments>`

Even though pip is available from your Python installation as an importable module, via import pip, it is not supported to use pip in this way.

**Comment by emcquaid** [comment]
> > I'm absolutely new to all of this , could someone tell me where these commands have to be written in the Spyder app , so i can install imageai?
> 
> https://pip.pypa.io/en/stable/user_guide/
> 
> pip is a command line program. When you install pip, a pip command is added to your system, which can be run from the command prompt as follows

if you have questions about what is the command prompt, aka the command line or terminal, try google to learn more about those terms.

Or check out this great free resource on Udemy: https://www.udemy.com/course/powertocode-awesome-command-line/

**Comment by ShreyaJamsandekar** [comment]
> > > I'm absolutely new to all of this , could someone tell me where these commands have to be written in the Spyder app , so i can install imageai?
> > 
> > 
> > https://pip.pypa.io/en/stable/user_guide/
> > pip is a command line program. When you install pip, a pip command is added to your system, which can be run from the command prompt as follows
> 
> @ShreyaJamsandekar
> if you have questions about what is the command prompt, aka the command line or terminal, try google to learn more about those terms.
> 
> Or check out this great free resource on Udemy: https://www.udemy.com/course/powertocode-awesome-command-line/

thank you so much!

**Comment by maciekbaglaj** [comment]
Hey there, 
I'm stuck on running the detector = VideoObjectDetection() function and I am getting this error:

AttributeError: module 'keras.backend' has no attribute 'get_session'

I've installed and uninstalled both versions of pip and pip3 for all packages, but none of them helps.
Would you have any advice on solving this issue?
Cheers!
