### ISSUE TITLE
i am having this error when i am training my custom model.

### ISSUE THREAD

**Issue by Jitendra-Nathawat** [OlafenwaMoses/ImageAI#552]
Failed to create a directory: C:/Users/lenovo/Desktop/ML Project//Jitendra/Project1/ImageAI/emblum\logs\resnet_lr-0.001_2020-06-28-11-53-00\train; No such file or directory [Op:CreateSummaryFileWriter]

here is my code - 

from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("C:/Users/lenovo/Desktop/ML Project//Jitendra/Project1/ImageAI/emblum")
model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True)

i am creating a virtual environment and now process this so i get this error...

**Comment by ehiaig** [comment]
Ensure that this directory is correct 'C:/Users/lenovo/Desktop/ML Project//Jitendra/Project1/ImageAI/emblum'

**Comment by Jitendra-Nathawat** [comment]
my directory is correct but when i am going train my model ill receive an this error ...........

Failed to create a directory: C:/Users/lenovo/Desktop/Ml original/ImageAI/emblum\logs\resnet_lr-0.001_2020-06-29-11-37-08\train; No such file or directory [Op:CreateSummaryFileWriter]

why this error is coming ?

**Comment by luisvivasg** [comment]
> my directory is correct but when i am going train my model ill receive an this error ...........
> 
> Failed to create a directory: C:/Users/lenovo/Desktop/Ml original/ImageAI/emblum\logs\resnet_lr-0.001_2020-06-29-11-37-08\train; No such file or directory [Op:CreateSummaryFileWriter]
> 
> why this error is coming ?

Are you sure about the path? ageAI/emblum\logs\resnet_lr-0.001_2020-06-29-11-37

I see you have / and \ at the same time.

**Comment by Jitendra-Nathawat** [comment]
ok thanks sir , i got it.
