### ISSUE TITLE
Custom object detection training

### ISSUE THREAD

**Issue by VincentDuf** [OlafenwaMoses/ImageAI#556]
Hi,
I want to use your project to train an aphid detection model. It's not very clear if I can train my custom model using Retinanet or if this network is only usable to make class prediction ?
I can't see the difference between Custom Detection Model Training and Custom Object Detection ? In both case you only speak about YoloV3 though in the introduction you speak about Retinanet for Object Detection...

Can you just confirm or not if I can train an object detection model based on retinanet ? 

Thank you and congrats for the project, it looks incredibly efficient to use.

**Comment by AbimbolaOO** [comment]
Yes, you can perform object detection with Retinanet but for custom Object detection i.e object detection model trained with your own custom data that can only be done YOLO.

The difference between **Custom Detection Model Training** and **Custom Object Detection** is that **Custom Detection Model Training** is used to train the object detection model with your own data while **Custom Object Detection** is used to perform the task of detecting object using the trained model. I like to think of  **Custom Object Detection** as been used for inference. while  **Custom Detection Model Training** is used for training.
