### ISSUE TITLE
The Session graph is empty.  Add operations to the graph before calling run().

### ISSUE THREAD

**Issue by J0ke1fdr** [OlafenwaMoses/ImageAI#56]
it is OK with Version 2.0.1, but in 2.0.2, the error said 

> RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

**Comment by OlafenwaMoses** [comment]
Update the Keras you have installed. Let me know if this resolves the issue.

**Comment by OlafenwaMoses** [comment]
You are welcome.

**Comment by Krishnarohith10** [comment]
Sorry to say but i got same problem, keras==2.3.1 and tensorflow==2.0.0
How do i solve this problem ?

**Comment by babaralishah** [comment]
i have uninstalled the keras but still the same error

**Comment by feliciandayani** [comment]
> Sorry to say but i got same problem, keras==2.3.1 and tensorflow==2.0.0
> How do i solve this problem ?

Hi, I have the same problem here. Do you manage to fix it?
