### ISSUE TITLE
TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32

### ISSUE THREAD

**Issue by nachiketmore99** [OlafenwaMoses/ImageAI#565]
I am getting this error when I try to train a model or load a previously trained model.
I am using these libraries with version,

**Keras==2.3.1
opencv-python==4.1.0.25
tensorflow==1.15.2**

TypeError                                 Traceback (most recent call last)
<ipython-input-4-ad5b5c47d07e> in <module>
     33 detector.setModelPath(str(dir)+"flask/model.h5")
     34 detector.setJsonPath(str(dir)+"flask/detection_config.json")
---> 35 detector.loadModel()
     36 print('Model Loaded')
     37 

~\Anaconda3\envs\image_class\lib\site-packages\imageai\Detection\Custom\__init__.py in loadModel(self)
    647             self.__detection_utils = CustomDetectionUtils(labels=self.__model_labels)
    648 
--> 649             self.__model = yolo_main(Input(shape=(None, None, 3)), 3, len(self.__model_labels))
    650 
    651             self.__model.load_weights(self.__model_path)

~\Anaconda3\envs\image_class\lib\site-packages\imageai\Detection\YOLOv3\models.py in yolo_main(input, num_anchors, num_classes)
     58 def yolo_main(input, num_anchors, num_classes):
     59 
---> 60     darknet_network = Model(input, darknet(input))
     61 
     62     network, network_1 = last_layers(darknet_network.output, 512, num_anchors * (num_classes + 5), layer_name="last1")

~\Anaconda3\envs\image_class\lib\site-packages\imageai\Detection\YOLOv3\models.py in darknet(input)
     31 
     32 def darknet(input):
---> 33     network = NetworkConv2D_BN_Leaky(input=input, channels=32, kernel_size=(3,3))
     34     network = residual_block(input=network, channels=64, num_blocks=1)
     35     network = residual_block(input=network, channels=128, num_blocks=2)

~\Anaconda3\envs\image_class\lib\site-packages\imageai\Detection\YOLOv3\models.py in NetworkConv2D_BN_Leaky(input, channels, kernel_size, kernel_regularizer, strides, padding, use_bias)
     15 
     16     network = Conv2D( filters=channels, kernel_size=kernel_size, strides=strides, padding=padding, kernel_regularizer=kernel_regularizer, use_bias=use_bias)(input)
---> 17     network = BatchNormalization()(network)
     18     network = LeakyReLU(alpha=0.1)(network)
     19     return network

~\Anaconda3\envs\image_class\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    487             # Actually call the layer,
    488             # collecting output(s), mask(s), and shape(s).
--> 489             output = self.call(inputs, **kwargs)
    490             output_mask = self.compute_mask(inputs, previous_mask)
    491 

~\Anaconda3\envs\image_class\lib\site-packages\keras\layers\normalization.py in call(self, inputs, training)
    183         normed_training, mean, variance = K.normalize_batch_in_training(
    184             inputs, self.gamma, self.beta, reduction_axes,
--> 185             epsilon=self.epsilon)
    186 
    187         if K.backend() != 'cntk':

~\Anaconda3\envs\image_class\lib\site-packages\keras\backend\tensorflow_backend.py in normalize_batch_in_training(x, gamma, beta, reduction_axes, epsilon)
   2313         return _fused_normalize_batch_in_training(
   2314             x, gamma, beta, reduction_axes,
-> 2315             epsilon=epsilon)
   2316     else:
   2317         if sorted(reduction_axes) == list(range(ndim(x)))[:-1]:

~\Anaconda3\envs\image_class\lib\site-packages\keras\backend\tensorflow_backend.py in _fused_normalize_batch_in_training(x, gamma, beta, reduction_axes, epsilon)
   2286         beta,
   2287         epsilon=epsilon,
-> 2288         data_format=tf_data_format)
   2289 
   2290 

~\Anaconda3\envs\image_class\lib\site-packages\tensorflow_core\python\ops\nn_impl.py in fused_batch_norm(x, scale, offset, mean, variance, epsilon, data_format, is_training, name)
   1499         data_format=data_format,
   1500         is_training=is_training,
-> 1501         name=name)
   1502     return y, batch_mean, batch_var
   1503 

~\Anaconda3\envs\image_class\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py in fused_batch_norm_v3(x, scale, offset, mean, variance, epsilon, data_format, is_training, name)
   4617                             variance=variance, epsilon=epsilon,
   4618                             data_format=data_format, is_training=is_training,
-> 4619                             name=name)
   4620   _result = _op.outputs[:]
   4621   _inputs_flat = _op.inputs

~\Anaconda3\envs\image_class\lib\site-packages\tensorflow_core\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    630               _SatisfiesTypeConstraint(base_type,
    631                                        _Attr(op_def, input_arg.type_attr),
--> 632                                        param_name=input_name)
    633             attrs[input_arg.type_attr] = attr_value
    634             inferred_from[input_arg.type_attr] = input_name

~\Anaconda3\envs\image_class\lib\site-packages\tensorflow_core\python\framework\op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     59           "allowed values: %s" %
     60           (param_name, dtypes.as_dtype(dtype).name,
---> 61            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     62 
     63 

_TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32_

**Comment by Combinacijus** [comment]
Would be nice to see full code.
Take a look at this [tutorial](https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff)

In tutorial it's recommended to use tensorflow version **1.13.1** `pip3 install tensorflow-gpu==1.13.1` I suspect that different versions could cause problems as it seems it's very picky for dependencies. I have commented already on versions that [worked for me on my machine](https://github.com/OlafenwaMoses/ImageAI/issues/548#issuecomment-659459131). Hope it will be helpful

**Comment by nachiketmore99** [comment]
Thank You for the reply I will check with the versions you mentioned

**Comment by AbimbolaOO** [comment]
Hello @nachiketmore99,
To resolve the issue you are currently having you need to make sure your python version is not greater than python3.6. To see your python version type **python3 --version** to your command line. 

Having done that make sure you install the exact versions of the packages listed below in the given order.
**pip install tensorflow==1.13.1
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade**
