### ISSUE TITLE
Tensorflow error "ValueError: None values not supported."

### ISSUE THREAD

**Issue by osseney** [OlafenwaMoses/ImageAI#566]
W0726 07:07:10.433214 139676463068992 module_wrapper.py:139] From guess.py:158: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

/home/autumn/tensor/AgeGenderDeepLearning-master/Folds/tf/age_fold_test_is_3_RFSACL//run-433692/checkpoint-0
WARNING:tensorflow:From guess.py:166: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
W0726 07:07:10.434898 139676463068992 deprecation.py:323] From guess.py:166: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
INFO:tensorflow:Restoring parameters from /home/autumn/tensor/AgeGenderDeepLearning-master/Folds/tf/age_fold_test_is_3_RFSACL//run-433692/checkpoint-0
I0726 07:07:10.474560 139676463068992 saver.py:1284] Restoring parameters from /home/autumn/tensor/AgeGenderDeepLearning-master/Folds/tf/age_fold_test_is_3_RFSACL//run-433692/checkpoint-0
Traceback (most recent call last):
  File "guess.py", line 208, in <module>
    tf.app.run()
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "guess.py", line 169, in main
    softmax_output = tf.nn.softmax(logits)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2958, in softmax
    return _softmax(logits, gen_nn_ops.softmax, axis, name)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2884, in _softmax
    logits = ops.convert_to_tensor(logits)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/autumn/anaconda3/envs/myenv/lib/python3.5/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

`batch_norm_params = {
        "is_training": is_training,
        "trainable": True,
        # Decay for the moving averages.
        "decay": 0.9997,
        # Epsilon to prevent 0s in variance.
        "epsilon": 0.001,
        # Collection containing the moving mean and moving variance.
        "variables_collections": {
            "beta": None,
            "gamma": None,
            "moving_mean": ["moving_vars"],
            "moving_variance": ["moving_vars"],
        }
    }

    epochs = 250
    batch_size = 55000 # Entire training set
    weight_decay = 0.0005
    weights_regularizer = tf.contrib.layers.l2_regularizer(weight_decay)
    image_set = input_data.read_data_sets('~/tensor/AgeGenderDeepLearning-master/Folds/tf/age_fold_test_is_3_RFSACL', one_hot=True)
    model_path_pruned = "~/tensor/AgeGenderDeepLearning-master/Folds/tf/Pruned.ckpt"

    images = tf.placeholder(tf.float32, [None, 784])
    nlabels = tf.placeholder(tf.float32, [None, 10])

    layer1 = layers.masked_fully_connected(images, 300)
    layer2 = layers.masked_fully_connected(layer1, 300)
    logits = layers.masked_fully_connected(layer2, 10)

    batches = int(len(image_set.train.images) / batch_size)
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=nlabels, logits=logits))

    with tf.variable_scope("LeviHassnerBN", "LeviHassnerBN", [images]) as scope:

        pruning_hparams = pruning.get_pruning_hparams()
        print("Pruning Hyperparameters:", pruning_hparams)

        # Change hyperparameters to meet our needs
        pruning_hparams.begin_pruning_step = 0
        pruning_hparams.end_pruning_step = 250
        pruning_hparams.pruning_frequency = 1
        pruning_hparams.sparsity_function_end_step = 250
        pruning_hparams.target_sparsity = .9
        global_step = tf.train.get_or_create_global_step()

        saver = tf.train.Saver()

        train_op = tf.train.AdamOptimizer(learning_rate=1e-4).minimize(loss, global_step=global_step)
        reset_global_step_op = tf.assign(global_step, 0)
        # Create a pruning object using the pruning specification, sparsity seems to have priority over the hparam
        p = pruning.Pruning(pruning_hparams, global_step=global_step, sparsity=.9)
        prune_op = p.conditional_mask_update_op()
        correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(nlabels, 1))
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
        with tf.Session() as sess:
            sess.run(tf.initialize_all_variables())

            # Reset the global step counter and begin pruning
            sess.run(reset_global_step_op)
            for epoch in range(epochs):
                for batch in range(batches):
                    batch_xs, batch_ys = image_set.train.next_batch(batch_size)
                    # Prune and retrain
                    sess.run(prune_op)
                    sess.run(train_op, feed_dict={images: batch_xs, nlabels: batch_ys})

                # Calculate Test Accuracy every 10 epochs
                if epoch % 10 == 0:
                    acc_print = sess.run(accuracy, feed_dict={images: image_set.test.images, nlabels: image_set.test.labels})
                    print("Pruned model step %d test accuracy %g" % (epoch, acc_print))
                    print("Weight sparsities:", sess.run(tf.contrib.model_pruning.get_weight_sparsity()))

                    saver.save(sess, model_path_pruned)

            # Print final accuracy
            acc_print = sess.run(accuracy, feed_dict={images: image_set.test.images, nlabels: image_set.test.labels})
            print("Final accuracy:", acc_print)
            print("Final sparsity by layer (should be 0)", sess.run(tf.contrib.model_pruning.get_weight_sparsity()))`

**Comment by Combinacijus** [comment]
Shouldn't this issue belong to Tensorflow repository instead of ImageAI?

**Comment by AbimbolaOO** [comment]
Hello @osseney,

To resolve the issue you are currently having you need to make sure your python version is not greater than python3.6. To see your python version type python3 --version to your command line.

Having done that make sure you install the exact versions of the packages listed below in the given order.
pip3 install tensorflow-gpu==1.13.1
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade

Do this and you will be fine
