### ISSUE TITLE
Detect humans and Hololens simultaneously

### ISSUE THREAD

**Issue by beginner1393** [OlafenwaMoses/ImageAI#567]
Hello to all.
I read the following example in its entirety and wrote a similar program:

[](https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTION.md
[]()https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTIONTRAINING.md
)
Now, I want to be able to recognize the human position in addition to the Hololens , what should I do?
In the example above, only the Hololens can be detected in the image, how can other objects be detected in the image?

Thanks

**Comment by Combinacijus** [comment]
Checkout this tutorial [https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff](https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff)

In short:

1. Make a dataset for humans.
2. Combine hololens and humans datasets into one.
3. Everything else is almost the same as in the tutorial I linked but change the line _object_names_array = ["hololens"]_ to _object_names_array = ["hololens", "human"]_. (note that "human" should be same label as in your dataset).

If it solved your issue you should close it.

**Comment by beginner1393** [comment]
Thanks.
Do I have to retrain humans to the YOLO ?!!

**Comment by Combinacijus** [comment]
@beginner1393 If you refer to a 'person' class which is 1 of 50 (or so) classes that are already trained in a given pretrained model then the answer is probably **yes** .
As I understand when using transfer learning you need to train/retrain all classes you want to classify.

I could be wrong so if anyone else knows better or it becomes a feature please correct me
