### ISSUE TITLE
Error closing: 'Image' object has no attribute 'fp'

### ISSUE THREAD

**Issue by addriumruss** [OlafenwaMoses/ImageAI#569]
first time use imageai, images are collected as guided, but many same error appear:
Error closing: 'Image' object has no attribute 'fp'

it this error says the image is now right?

**Comment by AbimbolaOO** [comment]
Hello @addriumruss,

To resolve the issue you are currently having you need to make sure your python version is not greater than python3.6. To see your python version type python3 --version to your command line.
Having done that make sure you install the exact versions of the packages listed below in the given order.
pip install tensorflow==1.13.1 or pip3 install tensorflow-gpu==1.13.1 if you are using a GPU
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade
 
Having done all this you can re-run your code an things should work better now.
