### ISSUE TITLE
No objects detected (returning empty list), despite ImageAI calculation of a 0.9972 mAP

### ISSUE THREAD

**Issue by zacknawrocki** [OlafenwaMoses/ImageAI#578]
I set up everything, based on these three Medium articles created by ImageAI
Link 1: https://towardsdatascience.com/object-detection-with-10-lines-of-code-d6cb4d86f606
Link 2: https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff
Link 3: https://medium.com/deepquestai/object-detection-training-preparing-your-custom-dataset-6248679f0d1d

To repeat, I have attached code, which includes example scripts identical to the ImageAI documentation https://drive.google.com/drive/folders/1SidAsXZ4FpWOq7v00v6TT0Uplj24jGdW?usp=sharing

I have also attached the [results](https://github.com/OlafenwaMoses/ImageAI/files/5197789/mAP_results.txt) that show the calculated 0.9972 mAP within a text file. Even when testing the recognition on the images I used to train the detection, I still receive no results. Considering I've been able to get the same results (or lack of) with the example scripts used in the the documentation, as well as within the written articles, I am unsure why this would be occurring.

**Comment by OlafenwaMoses** [comment]
How many images did you provide for train and validation?

**Comment by zacknawrocki** [comment]
I used 252 images for training and 62 images for validation.

**Comment by OlafenwaMoses** [comment]
Interesting. I will advice you lower the `minimum_percentage_probability` ( 50 by default ) and try again.

Also, How many objects are involved? I will advice you add more training images to improve the accuracy.

**Comment by zacknawrocki** [comment]
I am using one class of objects and tried a 30 threshold.

Interestingly I was able to get detection working using the darknet repository, with a provided notebook. While that solves the problem I was having, I it doesn't quite solve the problem with imageAI.

**Comment by zacknawrocki** [comment]
Switching to .jpeg instead of .png worked

**Comment by SB2020-eye** [comment]
I'm also new at this and having difficultes. So, does .png work with imageai? What about .tiff?

I thought they did. But I'm trying to figure out what's going wrong, came across this, and now am concerned to narrow down possible reasons things aren't working.
