### ISSUE TITLE
how can i change the size of the font which printed on the output photos

### ISSUE THREAD

**Issue by refaeldimri** [OlafenwaMoses/ImageAI#579]
hello.
i got detect photos with very small font (square, name, confidence), i cant see it.
how can i fix this problem?

**Comment by bobwassell** [comment]
This is on line 45 of Detection\keras_retinanet\utils\visualization.py    
HTH

cv2.putText(image, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 3)
