### ISSUE TITLE
 trainer.setModelTypeAsYOLOv3() TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by egejac** [OlafenwaMoses/ImageAI#585]
Hello
I got an issue while trying to learn to train the model
Could you please take time to tell me what could have been wrong

from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="hololens")

trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, num_experiments=200, train_from_pretrained_model="./models/yolo-tiny.h5")
trainer.trainModel()

Ouptut

trainer.setModelTypeAsYOLOv3()
TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'

**Comment by refaeldimri** [comment]
what is the name of your model? ("./models/yolo-tiny.h5"). are u sure? where do u store it?

**Comment by ejgeo** [comment]
I used the available yolo-tiny.h5 to train, which is stored in the folder models

**Comment by refaeldimri** [comment]
Do u use google colab?
Where do u store the files? On your computer? On your drive? On google colab?

**Comment by egejac** [comment]
I use my Computer. The files are stored in my C drive
Geo Jacob
<https://de.linkedin.com/in/geo-jacob/de>[image: T:]  +49 (0) 17636610077
<+49%20(0)%2017636610077>
[image: E:]  ejgeo305@gmail.com
Johannes Kärner Str. 5, 04328, Leipzig,
<https://de.linkedin.com/in/geo-jacob/de>
[image: Your Company]

**Comment by refaeldimri** [comment]
U cant run it by your computer i you do not have GPU/Graphic card.

**Comment by egejac** [comment]
But, can that lead to error?

**Comment by refaeldimri** [comment]
I think so, try to put the model in same folder with the code file and change this line:
train_from_pretrained_model="yolo-tiny.h5")

Google colab serve you to run this code without GPU

**Comment by egejac** [comment]
I could solve it. The problem was that I used "yolo-tiny.h5". I changed as per the documentation to  "pretrained-yolov3.h5". This resulted in the training of the model
