### ISSUE TITLE
Model file weight problem

### ISSUE THREAD

**Issue by MainIII** [OlafenwaMoses/ImageAI#59]
Hello, I used the ResNet model file that Custome trained to load into the project, which is wrong: ValueError: ValueError: You are trying to load a weight file containing 107 layers into a model with 116 layers.

Do you have any solutions?

**Comment by OlafenwaMoses** [comment]
1. What is model type you set before you load the model? 
2. How many object classes are in the custom model? 

Also, you may post your full code here so that I can review it.

**Comment by MainIII** [comment]
Thank you very much for answering my question
The type of the model is set by the RetinaNet type.

This is my source file
from imageai.Detection import ObjectDetection
import os

execution_path_Mode = os.getcwd()+"\\mode"    #Model file storage path
execution_path_In = os.getcwd()+"\\image"    #Image storage path to be detected
execution_path_Out = os.getcwd()+"\\image_new"    #Output image storage path

detector = ObjectDetection()     #Create an object detection object
detector.setModelTypeAsRetinaNet()    #Set the model type to RetinaNet
detector.setModelPath( os.path.join(execution_path_Mode, "model_ex-100_acc-0.613487.h"))    #Set model file address
mode = detector.loadModel()


for root,dirs,files in os.walk(execution_path_In):
    for f in files:
        i = 0
        detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path_In, f), output_image_path=os.path.join(execution_path_Out, f[:-4]+'_new.jpg'))
        for eachObject in detections:
            i += 1
            print(eachObject["name"] + " : " + eachObject["percentage_probability"] )
            print("--------------------------------")

**Comment by MainIII** [comment]
model_ex-100_acc-0.613487.h
This is my custom model file, which contains four object classes.
They are cats, dogs, rabbits, tigers.

**Comment by MainIII** [comment]
I think I've found the problem.
I didn't use the CustomImagePrediction class to load the model, and I didn't specify the number of objects and the JSON file
Thank you and your team for developing such a beautiful library

**Comment by OlafenwaMoses** [comment]
I am glad you figured it out. You are most welcome.
