### ISSUE TITLE
Box_points

### ISSUE THREAD

**Issue by egejac** [OlafenwaMoses/ImageAI#591]
I was trying to use boxpoints to calculate the distance of the object from the image. Where could we find the documentation for coordinates for box_points for object distance calculation

**Comment by Helaly96** [comment]
Can you clarify your issue abit more?

**Comment by egejac** [comment]
The code: detections = detector.detectObjectsFromImage(input_image="image.jpg", output_image_path="imagenew.jpg", minimum_percentage_probability=30)

one parameter, 
returns : The returned values will depend on the parameters parsed into the detectObjectsFromImage() function. See the comments and code below

“”“
If all required parameters are set and ‘output_image_path’ is set to a file path you want the detected image to be saved, the function will return:

an array of dictionaries, with each dictionary corresponding to the objects
detected in the image. Each dictionary contains the following property:

- name (string)
- percentage_probability (float)
- box_points (tuple of x1,y1,x2 and y2 coordinates)

So what doese x1,y1,x2 and y2 coordinates mean? Does x1 means distance from left end of the image, y1 from base of the image etc?

**Comment by Helaly96** [comment]
![image](https://user-images.githubusercontent.com/30905312/96568927-cc94e000-12c8-11eb-8861-ee8be83574f8.png)

**Comment by egejac** [comment]
Thank you
