### ISSUE TITLE
Error while using ImageAI with Flask if not Loading the model in the same method

### ISSUE THREAD

**Issue by Helaly96** [OlafenwaMoses/ImageAI#593]
Hello,
i am trying to make a simple API to detect images using ImageAI, and I ran into a very weird problem that I cannot explain.

when I init the Model globally and try to just run the object detection function from inside the method, it gives me a lot of errors mostly

```
"Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path 
```

```
'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("keras_learning_phase:0", shape=(), dtype=bool) is not an element of this graph.
```

and thinks like that all , but when I do the same code, but just put those 
```
yolo = Detection.ObjectDetection()
yolo.setModelTypeAsYOLOv3()
yolo.setModelPath(modelpath)
yolo.loadModel()

```
inside the method , the code works just fine.

i tried disabling the Threads in flask, but no hope.

**Comment by AlucardNosferatu** [comment]
same question, I guess it's because they are in different threads?
