### ISSUE TITLE
Importing imageai.Detection Give "Illegal Instruction"

### ISSUE THREAD

**Issue by GetRektBoy724** [OlafenwaMoses/ImageAI#595]
i have imageai install in my linux
i have intel 7th gen celeron cpu and intel hd graphics card (it was crappy? ummm yes)
if i run 
`
python3 -c "import imageai.Detection"
`
i get 
`
Illegal Instruction
`
i already install ALL of the requirements and i install imageai using pip
i use python3.8 if you ask
if i look on dmesg...this thing showed up : 
`
traps: camera_feed_det[15800] trap invalid opcode ip:7fe4a22f0f10 sp:7ffd72ccfa68 error:0 in _pywrap_tensorflow_internal.so[7fe494772000+1d6ed000]
`
pls help
this is the code im trying to run
`
#!/usr/bin/python3
from imageai.Detection import VideoObjectDetection
import os
import cv2

execution_path = os.getcwd()

camera = cv2.VideoCapture(0)

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath(os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5")) # Download the model via this link https://github.com/OlafenwaMoses/ImageAI/releases/tag/1.0
detector.loadModel()

video_path = detector.detectObjectsFromVideo(camera_input=camera,
                                output_file_path=os.path.join(execution_path, "camera_detected_video")
                                , frames_per_second=20, log_progress=True, minimum_percentage_probability=30)
print(video_path)

`
any answer is appreciated :D

**Comment by GetRektBoy724** [comment]
im really a beginner in the world of object detection and image recognition

**Comment by GetRektBoy724** [comment]
yayy got it fixed but i have a new problem tho
i use this pre-build wheel : https://github.com/agkphysics/tensorflow-wheels/releases/download/tf_2.4.0_nogpu_noavx_nomkl/tensorflow_cpu-2.4.0-cp38-cp38-linux_x86_64.whl
from this : https://github.com/yaroslavvb/tensorflow-community-wheels/issues/158

**Comment by elbriga** [comment]
how do u fixed it?
