### ISSUE TITLE
TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by GetRektBoy724** [OlafenwaMoses/ImageAI#597]
The code that gives error : 
[---------------]
#!/usr/bin/python3
from imageai.Detection import ObjectDetection as detector

model_path = "./models/yolo.h5"
input_path = "./input/image.jpg"
output_path = "./output/newimage.jpg"

detector.setModelTypeAsYOLOv3()
detector.setModelPath(model_path)
detector.loadModel()
detection = detector.detectObjectsFromImage(input_image=input_path, output_image_path=output_path)

for eachItem in detection:
    print(eachItem["name"] , " : ", eachItem["percentage_probability"])
[---------------]
and the stderr was : 
`
Traceback (most recent call last):
  File "./objectdetectionfromimage2.py", line 8, in <module>
    detector.setModelTypeAsYOLOv3()
TypeError: setModelTypeAsYOLOv3() missing 1 required positional argument: 'self'
`
i run the code with python3.8
i already install all ImageAI Requirements
pls help...any answer is appreciated

**Comment by OlafenwaMoses** [comment]
You forgot to create the detector class. See the correct code below.

```
from imageai.Detection import ObjectDetection

model_path = "./models/yolo.h5"
input_path = "./input/image.jpg"
output_path = "./output/newimage.jpg"


detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath(model_path)
detector.loadModel()
detection = detector.detectObjectsFromImage(input_image=input_path, output_image_path=output_path)

for eachItem in detection:
    print(eachItem["name"] , " : ", eachItem["percentage_probability"])
```

**Comment by OlafenwaMoses** [comment]
Also, install the latest version of ImageAI in the documentation linked below.

https://imageai.readthedocs.io/en/latest/index.html#installing-imageai

**Comment by exeptionerror** [comment]
All Possible working solution added [[Solved] TypeError: Missing 1 required positional argument: ‘self’](https://flutterq.com/typeerror-missing-1-required-positional-argument-self/)
