### ISSUE TITLE
output bounding boxes

### ISSUE THREAD

**Issue by dami23** [OlafenwaMoses/ImageAI#6]
thank you for your work and share, would it be possible to output the bounding box values of an arbitrary image? Sincerely thank you for your help!!

**Comment by OlafenwaMoses** [comment]
You can run object detection on any image parsed into the **detectObjectsFromImage()**  function. Are you asking to obtain the x, y,  width and height values for the bounding box of each object detected?

**Comment by dami23** [comment]
@OlafenwaMoses thank you for your reply. Yes,  I just want to get the objects bounding boxes values (x, y, width, height) from images (not from the coco dataset). I have tired to use detections[0, :, :4] in the function detectObjectsFromImage() to output bboxes, the output bboxes with shape (160965,4). It is difficult to acquire the expected values from the output bboxes without filtering through the preset minimum_percentage_probability and the calculated (label, score) by the model. Could you give me a cue to resolve this problem? Thank you again!!

**Comment by OlafenwaMoses** [comment]
Thank you for bringing this up. We will provide options to obtain the bounding box details of each object detected in the next version of ImageAI. It will be announced soon. Keep in touch.

**Comment by OlafenwaMoses** [comment]
The latest version of ImageAI (v2.0.2) is now available and supports retrieving x1,y1,x2 and y2 coordinates of each detected object. Find links to documentation below. 

http://imageai.readthedocs.io/en/latest/detection/index.html

http://imageai.readthedocs.io/en/latest/video/index.html
