### ISSUE TITLE
Train model for custom object detection in video.

### ISSUE THREAD

**Issue by ankitaggarwal-trantor** [OlafenwaMoses/ImageAI#60]
Hi Moses,

I want to train resnet model with custom objects (traffic lights, road signs etc). Then want to use that model for object detection in video. It seems like you have given custom model train for image prediction only not for object detection in videos. Any luck to get help on it.

Regards,
Ankit Aggarwal

**Comment by OlafenwaMoses** [comment]
Please see the discussion here #8 .
