### ISSUE TITLE
How to save only person detected video

### ISSUE THREAD

**Issue by Malithi-gif** [OlafenwaMoses/ImageAI#604]
I need to save only person detected from full video. My video firstly person display and secondly display the car. I need to save only  person detected video from that.

**Comment by OlafenwaMoses** [comment]
You can do this by adding custom objects to your `detectObjectsFromVideo()` function. See sample below:

```
custom = detector.CustomObjects(person=True)
detector.detectObjectsFromVideo(custom_objects=custom, ...............)
```
