### ISSUE TITLE
should pycocotools be listed in requirements.txt?

### ISSUE THREAD

**Issue by suliuzh** [OlafenwaMoses/ImageAI#605]
Hi
I am wondering if pycocotools should be listed in requirements,txt?
As we can see, pycocotools is used in source codes in the following screenshot as a must. But when I use "pip install ImageAI", it seems that pycocotools will not be installed automatically. So should pycocotools be listed as dependency? If not, why?
![image](https://user-images.githubusercontent.com/27858725/99872880-827f8100-2c1d-11eb-9bb9-432bdc6851bb.png)

**Comment by OlafenwaMoses** [comment]
`pycocotools` isn't needed for ImageAI since it doesn't support custom model training for RetinaNet yet.
