### ISSUE TITLE
AttributeError : 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jozdavab** [OlafenwaMoses/ImageAI#606]
Hi!

I am trying to run the example python code for objection detection, called "FirstObjectDetection.py".
https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/README.md#firstobjectdetectionpy

However in line9, after calling detector.loadModel()" I get an exception:

"
Exception has occurred: AttributeError
'str' object has no attribute 'decode'
"

What can cause an issue like this?

-----
The imageAI project installation is fine I think, because I can run the example python code for imageprediction without any issue:
https://github.com/OlafenwaMoses/ImageAI/tree/master/imageai/Prediction#firstprediction

I set up the project with python 3.8.6 with dependencies:

pip3 install tensorflow==1.13.1
pip3 install numpy==1.16.1
pip3 install scipy
pip3 install opencv-python
pip3 install pillow
pip3 install matplotlib
pip3 install h5py
pip3 install keras==2.2.4
pip3 install imageai --upgrade

Thanks for your reply
David

**Comment by naimulhq** [comment]
I had the same issue too. I was able to fix it by running 
`pip3 install 'h5py<3.0.0'`

**Comment by jozdavab** [comment]
Hi!

Seems like downgrading h5py solved the issue.
Thank you for your reply.

**Comment by AlucardNosferatu** [comment]
pip install h5py==2.10
