### ISSUE TITLE
InternalError: Failed to create session. ERROR

### ISSUE THREAD

**Issue by angelo337** [OlafenwaMoses/ImageAI#61]
hi there
I was Running you example on object training, (ImageAI : Custom Prediction Model Training )
however when i TRy to run the example code provided in there, I am getting this error:

InternalError: Failed to create session.

could you please point me out why is that and where could I find information in order to solve this issue?
thanks
angelo

**Comment by OlafenwaMoses** [comment]
Please see answers provided in the webpage linked below. 

https://github.com/tensorflow/tensorflow/issues/9549

**Comment by angelo337** [comment]
thanks, in case anyone have the same issue I solved with the installation of all Nvidia components with version 9.X, including cudnn.
regards
Angelo

**Comment by OlafenwaMoses** [comment]
@angelo337 Thanks for sharing this.
