### ISSUE TITLE
“SystemError: tile cannot extend outside image” in PIL during save image

### ISSUE THREAD

**Issue by hrvojej** [OlafenwaMoses/ImageAI#617]
I'm posting here solution for error in title. In case someone has similar problems. Same solution is posted on StackOverflow [here](https://stackoverflow.com/a/65473264/2119941). 

### If you are using DeepLearning software to detect objects in image and you are trying to cut detections out - you will most likely see this

I had same error while using [ImageAI][1] for detecting objects in image.
I've manage to resolve it by editing `ImageFile.py` from `PIL` package in my virtual environment. 

ImageFile is located in 

    \home\myuser\anaconda3\envs\envsName\lib\python3.7\site-packages\PIL\ImageFile.py

Find _save function line that starts with:

    def _save(im, fp, tile, bufsize=0):

After:

     tile.sort(key=_tilesort)
        # FIXME: make MAXBLOCK a configuration parameter
        # It would be great if we could have the encoder specify what it needs
        # But, it would need at least the image size in most cases. RawEncode is
        # a tricky case.

Insert:

    tile = [e for e in tile if e[1][2] > 0 and e[1][3]>0]

This will skip saving of all detections which have incorrect sizes for width and height of image (tile) which is sometimes reported to be 0, probably because detected object is only partially shown on edge of the image.

**------------** 

But if you for example have case where you know that all your images are 1920x1080 and you want to discard all images that are not reported with approximately same size than you can do something like this.

    tile = [e for e in tile if e[1][2] > 1720 and e[1][3]>880]

width and height are reduced for 200px to allow smaller, maybe still correct images(tiles), to be saved and this will discard all other images. 

[Source][2].

  [1]: https://github.com/OlafenwaMoses/ImageAI
  [2]: https://github.com/python-pillow/Pillow/issues/3044

**Comment by OlafenwaMoses** [comment]
Thanks for sharing this. @hrvojej

**Comment by omkale221** [comment]
thanks @hrvojej saved the day

**Comment by atelierdesdonnees** [comment]
Do you think I could do the tile selection tile = [e for e in tile if e[1][2] > 0 and e[1][3]>0] directly in the _encode_tile function, so as to be able to monkeypatch it instead of modifying the source code?

**Comment by elmackico93** [comment]
Here you have my friend 🐇 
Multi-GPU ImageAI Detection

import tensorflow as tf
from imageai.Detection import ObjectDetection

def secure_multi_gpu_detection(image_path, model_path, output_path):
    """
    Run secure, efficient multi-GPU object detection with ImageAI.
    """
    # Enable TensorFlow multi-GPU strategy
    strategy = tf.distribute.MirroredStrategy()

    with strategy.scope():
        # Securely configure GPUs
        gpus = tf.config.list_physical_devices('GPU')
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print(f"Using GPUs: {[gpu.name for gpu in gpus]}")

        # Initialize ImageAI detector
        detector = ObjectDetection()
        detector.setModelTypeAsYOLOv3()
        detector.setModelPath(model_path)
        detector.loadModel()

        # Perform detection
        detections = detector.detectObjectsFromImage(
            input_image=image_path,
            output_image_path=output_path,
        )

    return detections

# Example Usage
if __name__ == "__main__":
    detections = secure_multi_gpu_detection(
        image_path="input.jpg",
        model_path="yolo.h5",
        output_path="output.jpg",
    )
    print("Detections:", detections)
    
    Why This is Safe and Revolutionary
	1.	Security-First Configuration:
	•	Ensures GPU memory growth to prevent crashes or unauthorized access.
	•	No data or model modifications are saved beyond the intended use.
	2.	Efficiency:
	•	Uses tf.distribute.MirroredStrategy to parallelize workload across all GPUs seamlessly.
	•	Dynamically adjusts memory usage to avoid resource conflicts.
	3.	Revolutionary Simplicity:
	•	Compact and concise: A single function handles detection securely and efficiently.
	•	Future-ready: Works with TensorFlow’s latest multi-GPU strategies.
	4.	Environment Validation:
	•	Prints active GPUs for transparency.
	•	Automatically configures TensorFlow for maximum GPU performance.
	
Tell me if it solve the problem

**Comment by elmackico93** [comment]
![image](https://github.com/user-attachments/assets/2d4e5292-fbc5-4e32-bc15-d3a81e49b1a6)![image](https://github.com/user-attachments/assets/d55a98ea-e021-4ab4-8cb5-0b773eef7bc7)
