### ISSUE TITLE
AttributeError: 'ObjectDetection' object has no attribute 'setModelTypeAsYOLOv3'

### ISSUE THREAD

**Issue by angelo337** [OlafenwaMoses/ImageAI#62]
hi there
when i try to run the example: FirstObjectDetection.py
I am getting this error:

`AttributeError: 'ObjectDetection' object has no attribute 'setModelTypeAsYOLOv3'`

could you please point me out some resource to solve this ?
thanks
angelo

**Comment by OlafenwaMoses** [comment]
Do you have the latest version (2.0.2) of ImageAI installed ?

**Comment by angelo337** [comment]
Sure:

pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl
Requirement already satisfied: imageai==2.0.2 from https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl in /home/creangel/.local/lib/python3.5/site-packages (2.0.2)

**Comment by shenyp09** [comment]
Seems the object detection in ImageAI only supports RetinaNet...

**Comment by OlafenwaMoses** [comment]
ImageAI supports RetinaNet, YOLOv3 and TinyYOLOv3. I will advice you uninstall ImageAI and install it again.

**Comment by angelo337** [comment]
I just follow your advice and is currently working 
thanks a lot
angelo

**Comment by OlafenwaMoses** [comment]
You are welcome.

**Comment by ksuraj82** [comment]
i am using my resnet 152 model to detect the object but it is showing error .

ValueError: You are trying to load a weight file containing 466 layers into a model with 116 layers.

how to change the detector.setModelTypeAsRetinaNet() to resnet model.

**Comment by Ashokdevarajan** [comment]
i need to built object detection with other models is there any other options like imageai
models like inception,mobilenet

**Comment by OlafenwaMoses** [comment]
Please visit the Tutorial linked belos. You can now create custom detection model with ImageAI. 

https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff

**Comment by AfiaFaith** [comment]
Hello guys,

After training my dataset on Google Colab, i am trying to apply my model to my webcam but i am getting this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\AFIAFA~1\AppData\Local\Temp/ipykernel_19392/3255609503.py in <module>
      2 from imageai import Detection
      3 yolo = Detection.ObjectDetection()
----> 4 yolo.setModelTypeAsYOLOv5()
      5 yolo.setModelPath(modelpath)
      6 yolo.loadModel()

AttributeError: 'ObjectDetection' object has no attribute 'setModelTypeAsYOLOv5'


I am new to computer vision and python.

Below is my code.

modelpath = "C:/Users/xxxxx/Downloads/project/best.pt"
from imageai import Detection
yolo = Detection.ObjectDetection()
yolo.setModelTypeAsYOLOv5()
yolo.setModelPath(modelpath)
yolo.loadModel()

import cv2
cam = cv2.VideoCapture(0) #0=front-cam, 1=back-cam
cam.set(cv2.CAP_PROP_FRAME_WIDTH, 1300)
cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 1500)


while True:    ## read frames
    ret, img = cam.read()    ## predict yolo
    img, preds = yolo.detectCustomObjectsFromImage(input_image=img, 
                      custom_objects=None, input_type="array",
                      output_type="array",
                      minimum_percentage_probability=70,
                      display_percentage_probability=False,
                      display_object_name=True)    ## display predictions
    cv2.imshow("", img)    ## press q or Esc to quit    
    if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27):
        break## close camera
cam.release()
cv2.destroyAllWindows()

**Comment by OlafenwaMoses** [comment]
@AfiaFaith  ImageAI doesn't support YOLOv5 at the moment. Use `setModelTypeAsYOLOv3` instead.

**Comment by AfiaFaith** [comment]
ok, got another error:

ModuleNotFoundError: No module named 'models'

**Comment by AfiaFaith** [comment]
Thank you.
It's working now!

**Comment by LOActualControl** [comment]
Hi @AfiaFaith ! How did you end up solving the ModuleNotFoundError: No module named 'models' error? I'm getting the same error with the code below: (traceback is below that).  Thanks!

When attempting to perform Object Detection using a pre-trained YoloV3 model, I am getting a ModuleNotFoundError. I'm attempting to detect a single class ("boat") from the 80 pre-trained classes available. My code is below (taken from the ImageAI documentation):

`from imageai.Detection import ObjectDetection

detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath("/content/gdrive/MyDrive/shipspotting_revision/yolov3.pt")
detector.loadModel()
custom = detector.CustomObjects(boat=True)
detections = detector.detectCustomObjectsFromImage(custom_objects=custom, input_image="/content/gdrive/MyDrive/shipspotting_revision/rostock/output/live_test/test_[1463].jpg", output_image_path="/content/gdrive/MyDrive/shipspotting_revision/rostock/output/live_test/test_new.jpg")

for eachObject in detections:
print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
`

The traceback for the error I'm getting is below:

ModuleNotFoundError Traceback (most recent call last)
in
4 detector.setModelTypeAsYOLOv3()
5 detector.setModelPath("/content/gdrive/MyDrive/shipspotting_revision/yolov3.pt")
----> 6 detector.loadModel()
7 custom = detector.CustomObjects(boat=True)
8 detections = detector.detectCustomObjectsFromImage(custom_objects=custom, input_image="/content/gdrive/MyDrive/shipspotting_revision/rostock/output/live_test/test_[1463].jpg", output_image_path="/content/gdrive/MyDrive/shipspotting_revision/rostock/output/live_test/test_new.jpg")

3 frames
[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in find_class(self, mod_name, name)
1122 pass
1123 mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1124 return super().find_class(mod_name, name)
1125
1126 # Load the data (which may in turn use persistent_load to load tensors)

ModuleNotFoundError: No module named 'models'
