### ISSUE TITLE
Cannot assign to variable last1/kernel:0 due to variable shape  and value shape are incompatible

### ISSUE THREAD

**Issue by UntacticalPenguin** [OlafenwaMoses/ImageAI#632]
So I'm following Moses' Tutorial/Article on Object Detection on medium.com, and my code produces this error:

`Cannot assign to variable last1/kernel:0 due to variable shape (1, 1, 1024, 18) and value shape (255, 1024, 1, 1) are incompatible`

How do I solve this error?
I don't know how to solve this since I don't know very much about tensorflow, but I would very much appreciate your help in this. 

Thanks.

**Comment by CarlChaaya** [comment]
Same error, what did you do to fix?
