### ISSUE TITLE
stuck on: Generating anchor boxes for training images and annotation...

### ISSUE THREAD

**Issue by vladzilla** [OlafenwaMoses/ImageAI#636]
Hi dear team, 
trying to train new model and proses stuck on this step:
**Generating anchor boxes for training images and annotation...**

And nothing happens. It's just hanging there. 
in  folder cache I have only one file:
detection_train_data.pkl

What can be the issue? 
Is there a way to see full log?
Training set made same way as other models, and they worked.
Thanks
V.

my config:
```
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="20210205")
trainer.setTrainConfig(object_names_array=["object"], batch_size=4, num_experiments=200, train_from_pretrained_model="pretrained-yolov3.h5")
trainer.trainModel()
```

**Comment by vladzilla** [comment]
My bad, min max issue. 
closing ticket. 
thank you.

**Comment by jillcolebourn** [comment]
Hi @vladzilla 
I'm having this same issue, how did you solve it?

**Comment by vladzilla** [comment]
> Hi @vladzilla
> I'm having this same issue, how did you solve it?

hey  @jillcolebourn  - check your top and bottom coordinates - lowest value at the bottom etc.
