### ISSUE TITLE
Issue with custom trained ResNet50 model

### ISSUE THREAD

**Issue by ag4apple** [OlafenwaMoses/ImageAI#641]
First, thanks for this awesome project. My 13 year old daughter is using it for her science fair project this year.  She is testing out how the 4 algorithms do at classifying images of different types of sharks.  So far, we've made a custom trained model for MobileNetV2 and InceptionV3, using images of 5 different types of fish (four types of sharks and one of swordfish, as a control). The results we've gotten for the first two algorithms make sense to us, and it has worked pretty well.  Next we trained a model for ResNet50 using the same images, but for some reason, the model is outputting weird and very inaccurate info.  

Here is the script we wrote to do the custom image classification using ResNet:

```python
from imageai.Classification.Custom import CustomImageClassification
import os

execution_path = os.getcwd()

prediction50 = CustomImageClassification()
prediction50.setModelPath(model_path=os.path.join(execution_path, "model_ex-058_acc-1.000000.h5"))
prediction50.setJsonPath(model_json=os.path.join(execution_path, "model_class.json"))
prediction50.setModelTypeAsResNet50()
prediction50.loadModel(num_objects=5)

results, probabilities = prediction50.classifyImage("thresher1.png", result_count=3)

for eachResult, eachProbability in zip(results, probabilities):
    print(eachResult , " : " , eachProbability)
```

After running this, no matter what type of shark image we have it try to classify, these are the results we get back:

nurse  :  100.0
thresher  :  0.0
swordfish  :  0.0

This can't possibly be right.  It doesn't even look like the right kind of output. Do you have any suggestions?

**Comment by OlafenwaMoses** [comment]
@ag4apple I am really delighted to know ImageAI is helping your daughter with her science fair project. 

As per the ResNet50 model, there is a known issue with custom models with the ResNet50 since the upgrade to **T.F 2.4** backend. I will advice that you work with the previous 2 model types you mentioned + the **DenseNet121** model for now.

I will let you know when the Resnet50 issue is fixed.

**Comment by ag4apple** [comment]
@OlafenwaMoses good info, thank you!
