### ISSUE TITLE
Module not found 'imageai'

### ISSUE THREAD

**Issue by sandy1233** [OlafenwaMoses/ImageAI#67]
I'm trying to use the ImageAI library in windows environment. When I run the python sample code which you have provided to detect images in a picture I get an error - Module not found 'imageai'. I have already installed ImageAI using PIP. I dont know why I'm getting the error. Please help

**Comment by tianshanchuan** [comment]
did you named your py file as name with imageai ?  (imageai.py)

**Comment by OlafenwaMoses** [comment]
Also, hope you didn't install ImageAI into a virtual environment? Uninstall ImageAI and install it again globally.

**Comment by josware** [comment]
I'm using conda and had this same issue as I was using a virtual environment, try uninstalling it from the virtual environment and then installing it globally

i.e. 

--In terminal access the virtual env where you installed imageai
conda activate ENV
pip3 uninstall https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl 

--Go back to base (root)
conda deactivate

--install globally
pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl 

Hope this helps in your specific scenario.
