### ISSUE TITLE
cannot import name 'get_config' from 'tensorflow.python.eager.context'

### ISSUE THREAD

**Issue by architlatkar27** [OlafenwaMoses/ImageAI#680]
I am doing an object detection project on google colab. I have installed dependencies as indicated in the following article - https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff

But when i run the code for training, it shows the following error - 
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py)

I have tried different versions of tensorflow after that but it doesnt work. How exactly can i remove this error?

Also If i am trying to detect multiple objects through a custom dataset, how should the directory structure of the dataset be? 
Is it something like this - 
Dataset -> train -> Object1 -> images, annotations
                               Object2 -> images, annotations
Dataset -> validation -> Object1
                                        Object2

**Comment by Chevelle102** [comment]
try to install tensorflow==2.5.0rco and keras==2.5.0rc0 if you using python3.8
