### ISSUE TITLE
Training on colab got error from backend.py

### ISSUE THREAD

**Issue by knwin** [OlafenwaMoses/ImageAI#684]
Recently I re run the tutorial https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff on colab.

This time i got error as follow.
`ImportError                               Traceback (most recent call last)

<ipython-input-1-152554389c3d> in <module>()
----> 1 from imageai.Detection.Custom import DetectionModelTrainer
      2 
      3 trainer = DetectionModelTrainer()
      4 trainer.setModelTypeAsYOLOv3()
      5 trainer.setDataDirectory(data_directory="hololens")

4 frames

/usr/local/lib/python3.7/dist-packages/keras/backend.py in <module>()
     35 from tensorflow.python.distribute import distribute_coordinator as dc
     36 from tensorflow.python.distribute import distribute_coordinator_context as dc_context
---> 37 from tensorflow.python.eager.context import get_config
     38 from tensorflow.python.framework import config
     39 from keras import backend_config

ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py)
`

**Comment by jkcg-learning** [comment]
I am also getting the same error, any help ?

**Comment by ekesdf** [comment]
You have to change the tensorflow version to at least 2.4.0 then it will work 
Bc image ai updated the tensorflow version it runs with

**Comment by jkcg-learning** [comment]
I got this, it looks fine after installing
tensorflow==2.5.0rc0
keras==2.5.0rc0

you may also try 
tensorflow==2.4.0
keras==2.5.0rc0

**Comment by ekesdf** [comment]
> I got this, it looks fine after installing
> tensorflow==2.5.0rc0
> keras==2.5.0rc0
> 
> you may also try 
> tensorflow==2.4.0
> keras==2.5.0rc0

Like is said @jkcg-learning

**Comment by knwin** [comment]
Thaks all, now it is fine.

**Comment by knwin** [comment]
Thanks all, it is fine now.
