### ISSUE TITLE
Can We Use Pre-Train Models and add new product to it.

### ISSUE THREAD

**Issue by syedmustafa54** [OlafenwaMoses/ImageAI#70]
Hi @OlafenwaMoses and @johnolafenwa 
For example "Train Image Recognition AI with 5 lines of code" there are (10 products)
· Chef

· Doctor

· Engineer

· Farmer

· Firefighter

· Judge

· Mechanic

· Pilot

· Police

· Waiter
and I have trained it got 80% accuracy now i wanted to add more proudcts 
example 
.ARMY 
So my question is I need to retrain the whole model or I can do someting to save my time to retrain it because i have trained for more than 2 days now i want to update my model so how can i do this

**Comment by OlafenwaMoses** [comment]
You will have to add the dataset as the eleventh class and train a new model based on the new data set. ImageAI doesn't support transfer learning for now.
