### ISSUE TITLE
UnboundLocalError: local variable 'outs' referenced before assignment

### ISSUE THREAD

**Issue by BillSJC** [OlafenwaMoses/ImageAI#73]
caught an err when using the smple code

`UnboundLocalError: local variable 'outs' referenced before assignment`

```python
  File "C:\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 358, in evaluate_generator
    if not isinstance(outs, list):
UnboundLocalError: local variable 'outs' referenced before assignment
```

```python
from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("pets")
model_trainer.trainModel(num_objects=2, num_experiments=2, enhance_data=True, batch_size=4, show_network_summary=True)
```

and here are the struct of folder `pets`

![image](https://user-images.githubusercontent.com/13696311/45194532-0be94980-b286-11e8-9ab7-37524be32a1e.png)

**Comment by OlafenwaMoses** [comment]
How many pictures are in the test and train folder for each object class?

**Comment by BillSJC** [comment]
i do it only for test so i use a small amount of pictures

test:

- cat:1
- dog:2

train:

- cat:7
- dog:9

**Comment by OlafenwaMoses** [comment]
The recommended number of training images for each object class is 500. Check out the documentation link below. 

https://imageai.readthedocs.io/en/latest/custom/index.html
