### ISSUE TITLE
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

### ISSUE THREAD

**Issue by 9614priya** [OlafenwaMoses/ImageAI#730]
Hello,
I am trying to run imageai custom detection  but I always getting this warning message
"WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model."
help me out
thanks

**Comment by Visvas07** [comment]
Have you solved this issue?

**Comment by 9614priya** [comment]
> Hello, I am trying to run imageai custom detection but I always getting this warning message "WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model." help me out thanks

Solved

**Comment by 9614priya** [comment]
> 

Yes

**Comment by 9614priya** [comment]
> Have you solved this issue?

yes

**Comment by Visvas07** [comment]
> 

Can you please explain how because i'm facing the same issue

**Comment by Visvas07** [comment]
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2/2 [==============================] - 0s 14ms/step - loss: 0.4673 - accuracy: 0.7500
2/2 [==============================] - 0s 11ms/step - loss: 0.6340 - accuracy: 0.6875
Acc Real:75.0% Acc Fake:68.75%

while starting the model training

**Comment by 9614priya** [comment]
Use Colab 
pip install tensorflow-gpu==2.4.0

It can be helpful.
I have added the def get_config.... in my yolov3 script

**Comment by Visvas07** [comment]
Can you show where you have added get_config?
