### ISSUE TITLE
Temporized real-time video detection

### ISSUE THREAD

**Issue by manuel1507** [OlafenwaMoses/ImageAI#75]
Hi,

thank you very much for your great work! I'm currently using ImageAI to do some tests on live video feeds. 
It would be nice if you could add an additional parameter to the detectObjectsFromVideo and detectCustomObjectsFromVideo to "temporarize" the detection. Let's say I want the detection to stop automatically after 5 minutes then I could something like this:

detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "traffic.mp4"),
                                output_file_path=os.path.join(execution_path, "traffic_detected_new")
                                , frames_per_second=20, log_progress=True, **timeout = 300**)

timeout would be in seconds. 

Thanks and just continue your excellent work!
Looking forward to the mobile version :-)

Best Regards,
Manuel

**Comment by OlafenwaMoses** [comment]
Thank you Manuel. I will implement in next version/update.

**Comment by OlafenwaMoses** [comment]
See this article for latest update on this.

https://towardsdatascience.com/the-story-and-future-of-imageai-one-year-anniversary-e63c80f527c8

**Comment by OlafenwaMoses** [comment]
@manuel1507 , Thanks for your patience. This feature has been added to the latest version (v.2.0.3) along with other functionalities. See the link for more details.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/VIDEO.md#detectiontimeout

**Comment by manuel1507** [comment]
Thanks and just continue this way bro!!! You should be proud of yourself!!
