### ISSUE TITLE
TypeError: trainModel() got an unexpected keyword argument 'num_objects'`

### ISSUE THREAD

**Issue by ARatcliffe101** [OlafenwaMoses/ImageAI#783]
`   line 5, in <module>
    model_trainer.trainModel(num_objects=4, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True)
TypeError: trainModel() got an unexpected keyword argument 'num_objects'`

On latest version with everything updated

**Comment by OlafenwaMoses** [comment]
Please refer to the documentation: https://imageai.readthedocs.io/en/latest/custom/index.html

The following arguments have been removed in the latest version:
- num_objects
- enhance_data 
- show_network_summary
