### ISSUE TITLE
TypeError: ClassificationModelTrainer.trainModel() got an unexpected keyword argument 'num_objects'

### ISSUE THREAD

**Issue by russellcurtis** [OlafenwaMoses/ImageAI#793]
I've been trying to follow these instructions on both Windows and Linux but I constantly come up against the error:
`TypeError: ClassificationModelTrainer.trainModel() got an unexpected keyword argument 'num_objects'`
when I run the training model.

Am I missing a dependency or something?

**Comment by OlafenwaMoses** [comment]
Kindly check the documentation: https://imageai.readthedocs.io/en/latest/customdetection/index.html

The function `trainModel()` no longer accept parameters. Parse them into `setTrainConfig()` instead
