### ISSUE TITLE
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model. W0525 15:34:09.281517 139881406207808 saving_utils.py:328] Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model. 2023-05-25 15:34:13.758020: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them. INFO:tensorflow:Assets written to: ./checkpoints/yolov4-tiny-416/assets I0525 15:34:19.957567 139881406207808 builder_impl.py:779] Assets written to: ./checkpoints/yolov4-tiny-416/assets

### ISSUE THREAD

**Issue by kateeq73** [OlafenwaMoses/ImageAI#810]
Please help me out with this problem, my tensorflow mdel is not creating, I'm using tensorflow==2.8.0 and opencv-python 4.7.0.
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
W0525 15:34:09.281517 139881406207808 saving_utils.py:328] Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2023-05-25 15:34:13.758020: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
INFO:tensorflow:Assets written to: ./checkpoints/yolov4-tiny-416/assets
I0525 15:34:19.957567 139881406207808 builder_impl.py:779] Assets written to: ./checkpoints/yolov4-tiny-416/assets

**Comment by OlafenwaMoses** [comment]
ImageAI now uses Pytorch backend. Read more about it here

https://github.com/OlafenwaMoses/ImageAI/blob/master/BACKEND_MIGRATION.md
