### ISSUE TITLE
loadModel() got an unexpected keyword argument 'detection_speed'

### ISSUE THREAD

**Issue by IT2411** [OlafenwaMoses/ImageAI#812]
Hello,

I am not using a CustomDetectionModel, and don't know why it's not working. It does not seem that threading is causing the issue or using a GUI. Any idea why it's happening?

**Comment by OlafenwaMoses** [comment]
`detection_speed` has been removed from latest version of ImageAI. Read the documentation linked below

https://github.com/OlafenwaMoses/ImageAI/blob/master/BACKEND_MIGRATION.md#deprecated-functionalities

**Comment by OlafenwaMoses** [comment]
Simply remove the `detection_speed` parameter from your imageai code.
