### ISSUE TITLE
Can't find this function,detectCustomObjectsFromImage.

### ISSUE THREAD

**Issue by Haicaji** [OlafenwaMoses/ImageAI#814]
When I tried [**Custom Object Detection**](https://github.com/OlafenwaMoses/ImageAI/tree/master/imageai/Detection#custom-object-detection),I encountered an error report:
`AttributeError: 'ObjectDetection' object has no attribute 'detectCustomObjectsFromImage'`
In this line of code:
`detections = detector.detectCustomObjectsFromImage(custom_objects=custom_objects, input_image=os.path.join(execution_path , "image3.jpg"), output_image_path=os.path.join(execution_path , "image3custom.jpg"), minimum_percentage_probability=30)
`
I can't find this function,**detectCustomObjectsFromImage**.

What's more,I found a mistake in `custom_objects = detector.CustomObjects(car=True, motorcycle=True)`.
'motorcycle' should be 'motorbike'.

Could you give me a hand?
Thanks a lot.

**Comment by toolhater** [comment]
Try DetectCustomObjectsFromImage starting with a capital D
