### ISSUE TITLE
File size reduction 

### ISSUE THREAD

**Issue by msumalague** [OlafenwaMoses/ImageAI#819]
Is there any way to reduce the file size of the trained model? 

I am using the latest version of imageAI and the trained model I've generated was 249MB. I would like to reduce the file size no more than 100MB. Is it possible?

**Comment by OlafenwaMoses** [comment]
It's possible using model [quantization](https://pytorch.org/docs/stable/quantization.html#:~:text=A%20quantized%20model%20executes%20some,operations%20on%20many%20hardware%20platforms.) but it's currently not supported by ImageAI.

**Comment by OlafenwaMoses** [comment]
We do not have plans to support it anytime soon.
