### ISSUE TITLE
Not Getting box_points in the output 

### ISSUE THREAD

**Issue by santhoshkolloju** [OlafenwaMoses/ImageAI#82]
from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
custom_objects = detector.CustomObjects(person=True, car=False)
detections = detector.detectCustomObjectsFromImage(input_image=os.path.join(execution_path , "image.png"), output_image_path=os.path.join(execution_path , "image_new.png"), custom_objects=custom_objects, minimum_percentage_probability=65)

for eachObject in detections:
   print(eachObject["name"] + " : " + eachObject["percentage_probability"] )
   print("--------------------------------")

output:
[{'name': 'person', 'percentage_probability': '99.23332929611206'},
  {'name': 'person', 'percentage_probability': '99.3953287601471'}])

**Comment by OlafenwaMoses** [comment]
Kindly upgrade your ImageAI installation to version 2.0.2
