### ISSUE TITLE
Error with My own Images weight

### ISSUE THREAD

**Issue by nakarin** [OlafenwaMoses/ImageAI#88]
I have found an error " ValueError: You are trying to load a weight file containing 107 layers into a model with 116 layers." when i try to train with my own images. Could anyone can solve it?.

---------------------------------------------------------------------------
Code for Train my own images
from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("house")
model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=8, show_network_summary=True)

---------------------------------------------------------------------------
Code for detect my images (weight file from my training)
detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join('./' , "house/models/model_ex-100_acc-1.000000.h5"))
#detector.setJsonPath(os.path.join(execution_path, "model_class.json"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "sat1.JPG"), output_image_path=os.path.join(execution_path , "image2new.jpg"), minimum_percentage_probability=30)

**Comment by Berowne** [comment]
I had a similar issue!

**Comment by OlafenwaMoses** [comment]
You are trying to load a ResNet recognition model you trained into a RetinaNet object detection class. Please not that the mode you trained is for recognition and not detection. If you want to use your trained model for recognition, use the code has provided in this[ link ](https://github.com/OlafenwaMoses/ImageAI/blob/master/examples/custom_model_prediction.py)and ensure you set the model type to the exact one you used to train it..

**Comment by nakarin** [comment]
@OlafenwaMoses  I want to make Object Detection with my own dataset. Do you have any guides or code.
Thanks for your response.

**Comment by OlafenwaMoses** [comment]
Training your own object detection model is not yet supported in ImageAI. We are working on adding that in future versions. Please refer to #8 for further discussion on this.
