### ISSUE TITLE
Custom Training for Object Detection

### ISSUE THREAD

**Issue by JimZuber** [OlafenwaMoses/ImageAI#89]
I really like what you have done with ImageAI, it has been very helpful getting me started doing hands on work with AI. Question...

It appears that the latest release supports custom training for Image detection, but not object detection. Is that on your roadmap for imageAI in the near future? I am unclear whether there are additional complexities to training the model for object detection. 

Jim

**Comment by JimZuber** [comment]
I see that you have commented on this topic in your responses to another issue, so sorry about the duplicate post. Nevertheless, it would be great if you could provide an update/estimate for this feature.

**Comment by OlafenwaMoses** [comment]
For further discussion on this, please refer to #8
