### ISSUE TITLE
ImageAI support GPU mode？

### ISSUE THREAD

**Issue by suiyuteng** [OlafenwaMoses/ImageAI#9]

**Comment by OlafenwaMoses** [comment]
ImageAI automatically runs on GPU if available. All you need to do is to ensure you have the GPU version of Tensorflow installed.

**Comment by ZhangXinNan** [comment]
I have a  computer with GTX1070 , I test images/1.jpg ,  How can I run faster ??

```
model           “normal”(default),      “fast”,     “faster” ,      “fastest”,   “flash”
retinanet       1.02                    0.678       0.630            0.592           0.590   
yolo3           0.65                    0.63        0.61            0.619           0.619
```

**Comment by OlafenwaMoses** [comment]
You will notice that for every image detected, ImageAI will save a new copy with the objects located and named. The saving of a new image ( which you specify in "output_image_path") takes a fixed about of milliseconds, irrespective of the speed mode you are using. This time latency will reflect in all detection speeds. 
However, if you want to eliminate the latency of saving the new image, you can retrieve the image without saving it by setting output_type="array" and you can simply ignore returned Numpy array and work with the detections only. See sample below:



returned_image, detections = detector.detectObjectsFromImage(input_image="image.jpg", output_type="array", minimum_percentage_probability=70)

**Comment by OlafenwaMoses** [comment]
The above will reflect true differences in the detection speeds. Learn more via documentation below. 

http://imageai.readthedocs.io/en/latest/detection/index.html

**Comment by ZhangXinNan** [comment]
@OlafenwaMoses I have simplify the code , It costs about 90 ms to detect one image. Thank you.

**Comment by woshichuanqilz** [comment]
> ImageAI automatically runs on GPU if available. All you need to do is to ensure you have the GPU version of Tensorflow installed.

hi do you know if I use the google colab, it will use GPU automatically or not?

**Comment by OlafenwaMoses** [comment]
> > ImageAI automatically runs on GPU if available. All you need to do is to ensure you have the GPU version of Tensorflow installed.
> 
> hi do you know if I use the google colab, it will use GPU automatically or not?

Yes. ImageAI will automatically run on GPU as far as your Colab is connected to a GPU runtime.

**Comment by nbischoffcog** [comment]
Do you support multi GPUs?

**Comment by vikas1291** [comment]
I am using GeForce RTX 2070.To train custom model which has 1500 images for training on 3 classes,each class has 500 images and 300 images for testing,100 images for each class.
Using following code to train:

from imageai.Detection.Custom import DetectionModelTrainer
trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="data_set")
trainer.setTrainConfig(object_names_array=["1","2","2"], batch_size=32, num_experiments=200, train_from_pretrained_model="pretrained-yolov3.h5")
trainer.trainModel()

Getting Error:
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_0/model_1/conv_0/convolution}}]]
	 [[training/Adam/gradients/replica_1/model_1/conv_104/convolution_grad/Conv2DBackpropFilter/_4779]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_0/model_1/conv_0/convolution}}]]
0 successful operations.
0 derived errors ignored.

Please help me sir.

**Comment by cagnulein** [comment]
@suiyuteng @ZhangXinNan @woshichuanqilz @nbischoffcog  Which GPU card did you use? I would like to do the same for an alarm system, and i would like help my CPU (i7 7th generation 8 core) with a GPU.

**Comment by ansh-mehta** [comment]
@vikas1291 I am facing the same issue. How did you resolve? Please help!

**Comment by ajsirsik** [comment]
Hey there,

Hope you'all doing well.

I am also getting same issue. even after setting gpu_options.allow_growth = True, and limiting process_gpu_memory_fraction, issue persists. May I know what else can be done to get rid of this and running imageai on gpu mode

Many thanks
Regards

**Comment by Usmaniatech** [comment]
> I am using GeForce RTX 2070.To train custom model which has 1500 images for training on 3 classes,each class has 500 images and 300 images for testing,100 images for each class.
> I already have
> tensorflow-gpu==1.14
> CUDNN==7.4.1
> CUDA==10.0
> updated imageai library.
> 
> Using following code to train:
> 
> from imageai.Detection.Custom import DetectionModelTrainer
> trainer = DetectionModelTrainer()
> trainer.setModelTypeAsYOLOv3()
> trainer.setDataDirectory(data_directory="data_set")
> trainer.setTrainConfig(object_names_array=["1","2","3"], batch_size=32, num_experiments=200, train_from_pretrained_model="pretrained-yolov3.h5")
> trainer.trainModel()
> 
> Getting Error:
> tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
> (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[{{node replica_0/model_1/conv_0/convolution}}]]
> [[training/Adam/gradients/replica_1/model_1/conv_104/convolution_grad/Conv2DBackpropFilter/_4779]]
> (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[{{node replica_0/model_1/conv_0/convolution}}]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> Please help me sir. How to use GPU for training?

facing the same issue. tensorflow-gpu is not working. any solutions ?
