### ISSUE TITLE
Model request: MobileNetv2 + SSD

### ISSUE THREAD

**Issue by lefnire** [OlafenwaMoses/ImageAI#90]
Would love to pit MobileNetv2 + SSD up against YOLO, Tiny-YOLO for comparative video performance/speed.

**Comment by OlafenwaMoses** [comment]
I am closing this issue has it doesn't reflect any bug present of any feature suggested for ImageAI. You can perform performance check on RetinaNet vs YOLOv3 vs TinyYOLOv3 yourself using ImageAI. SSD isn't supported yet and as per this moment, there is no plan to add SSD.
