### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Devarsh8** [OlafenwaMoses/ImageAI#92]
I am a beginner.

Can u explain what resnet50_coco_best_v2.0.1.h5 contains....

**Comment by OlafenwaMoses** [comment]
The "resnet50_coco_best_v2.0.1.h5 " is the weight file that contains numbers that have been optimized for performing object detection on images effectively. This particular contains weight values for the RetinaNet model with the ResNet50 backend. To learn more on Deep Learning and models, visit the link below.

https://www.mathworks.com/discovery/deep-learning.html
