### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zafrirron** [OlafenwaMoses/ImageAI#96]
(I may have missed something.... in the documantation)
Since the camera capture examples uses CV to capture the camera video stream and CV capable of capturing other video streams (like video files...).
I would suggest to consider using "video stream" instead of "camera"....
I should be able to create the same video files detection examples by just using CV videocapture to the file ad the detection input.

**Comment by OlafenwaMoses** [comment]
ImageAI was created for simplicity and since it already provides a video input option, thus comes the key word "camera". However, those well familiar with OpenCV can decide to load the video and then parse the instance themselves.
