### ISSUE TITLE
No module named 'tensorflow.python.keras.preprocessing'

### ISSUE THREAD

**Issue by jaimebayes** [OlafenwaMoses/ImageAI#98]
Hi, 

I  got this error message:
ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing', 

Any advice how to solve it?

Thanks in advance, Jaime

**Comment by OlafenwaMoses** [comment]
Update your Keras installation to the latest version.

**Comment by jaimebayes** [comment]
Hi, 

I installed keras 2.2.4, i think is the lastest version, but nothing different happens, the same error.

----> 2 from tensorflow.python.keras.preprocessing import image
ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'

What else I can do to overcome this?

Thanks,  Jaime

**Comment by OlafenwaMoses** [comment]
I will advice you downgrade your Tensorflow version to 1.4.0. It might appear to be a versioning problem. Will investigate further and reach back to you.

**Comment by ericzon** [comment]
As https://www.tensorflow.org/alpha/guide/keras notices, it seems that from 2 version you only need to access to tensorflow.keras to use keras.
It'll be great to enable this new version in ImageAI

**Comment by SOUMYADEEP1805** [comment]
removw .python and use the parts

**Comment by Mr-Raldo** [comment]
> 

hello, did you check what was the problem?
